import type { LoadedPersona, LoreCardSection, RetrievedEvidenceItem } from "./types";
// Pure classifier shared with the gateway (ingest) and lore/resolve. It has no
// node/gateway dependencies, so importing it into the browser runtime is safe;
// it is the "third consumer" (the card fetch) named in Plan 072.1.
import {
  designateLoreSections,
  type DesignatableLoreSection
} from "../../../deployment/gateway/lore-designation";

export const OPENAI_VECTOR_STORE_PAGE_ID_ATTRIBUTE = "page_id";

export interface OpenAIVectorStoreEqFilter {
  type: "eq";
  key: string;
  value: string | number | boolean;
}

export type OpenAIVectorStoreFilter = OpenAIVectorStoreEqFilter;

export interface LLMGenerateRequest {
  model: string;
  systemPrompt: string;
  userPrompt: string;
  maxTokens?: number;
  /** Plan 073.2 — request category the gateway maps to a server-side model
   *  env var. "summary" uses the cheap memory-summary model; anything else
   *  (default) uses the dialogue model. No model id crosses the wire. */
  purpose?: "dialogue" | "summary";
}

/** Plan 072.7 — the LLM result now carries usage + the model actually used. */
export interface LLMGenerateResult {
  text: string;
  usage: GatewayUsage | null;
  model: string | null;
}

export interface LLMProvider {
  generateStructuredTurn: (request: LLMGenerateRequest) => Promise<LLMGenerateResult>;
}

export interface VectorStoreSearchRequest {
  vectorStoreId: string;
  query: string;
  maxResults: number;
  filters?: OpenAIVectorStoreFilter | null;
}

export interface VectorStoreProvider {
  searchLore: (request: VectorStoreSearchRequest) => Promise<RetrievedEvidenceItem[]>;
}

/** Plan 072.5 — a system content block; `cache: true` marks the cache breakpoint. */
export interface GatewaySystemBlock {
  text: string;
  cache?: boolean;
}

export interface GatewayGenerateRequest {
  model?: string;
  /** Plan 073.2 — server-side model selector; the gateway maps it to a model
   *  env var. See LLMGenerateRequest.purpose. */
  purpose?: "dialogue" | "summary";
  /** Legacy string form (sugarlang). Prefer systemBlocks for caching. */
  systemPrompt?: string;
  /** Plan 072.5 — structured system with a cache breakpoint (sugaragent). */
  systemBlocks?: GatewaySystemBlock[];
  userPrompt: string;
  maxTokens?: number;
}

/** Plan 072.5 — Anthropic usage passthrough (incl. prompt-cache read/create). */
export interface GatewayUsage {
  inputTokens: number;
  outputTokens: number;
  cacheReadInputTokens: number;
  cacheCreationInputTokens: number;
}

export interface GatewayGenerateResult {
  text: string;
  requestId: string | null;
  usage?: GatewayUsage | null;
  model?: string | null;
}

export interface GatewayVectorSearchRequest {
  vectorStoreId?: string;
  query: string;
  maxResults: number;
  filters?: OpenAIVectorStoreFilter | null;
}

export interface GatewayVectorSearchResult {
  results: RetrievedEvidenceItem[];
  requestId: string | null;
}

interface VendorTextResult {
  text: string;
  requestId: string | null;
}

interface VendorVectorSearchResult {
  results: RetrievedEvidenceItem[];
  requestId: string | null;
}

// Story 46.14 — the gateway server.mjs (generated by SugarDeploy)
// owns all third-party API call shapes server-side. Browser-side
// SugarAgent talks to the gateway via the SugarAgentGateway* clients
// below; the direct-API request/response shapes that used to live
// here (AnthropicMessageRequest, OpenAIResponseRequest,
// OpenAIEmbeddingRequest, OpenAIVectorStoreSearchRequest) were
// deleted along with their client/provider classes when the
// direct-from-browser code path was removed.

function normalizeModel(model: string): string {
  const normalized = model.trim();
  if (!normalized) {
    throw new Error("Model identifier is required");
  }
  return normalized;
}

function normalizePrompt(text: string, field: string): string {
  const normalized = text.trim();
  if (!normalized) {
    throw new Error(`${field} is required`);
  }
  return normalized;
}

function normalizeMaxTokens(value: number | undefined, fallback: number): number {
  if (typeof value !== "number" || !Number.isFinite(value)) {
    return fallback;
  }
  return Math.max(1, Math.floor(value));
}

function normalizeMaxResults(value: number): number {
  if (!Number.isFinite(value)) return 4;
  return Math.max(1, Math.min(8, Math.floor(value)));
}

function normalizeBaseUrl(baseUrl: string): string {
  const normalized = baseUrl.trim().replace(/\/+$/, "");
  if (!normalized) {
    throw new Error("Gateway base URL is required");
  }
  return normalized;
}

async function parseJsonResponse<T>(response: Response, label: string): Promise<T> {
  if (!response.ok) {
    const body = await response.text();
    throw new Error(
      `${label} failed with status ${response.status}${body.trim() ? `: ${body}` : ""}`
    );
  }
  return (await response.json()) as T;
}

/**
 * Story 46.14 / Story 47.9.5 — when the gateway runs in `bearer`
 * (shared-token) OR `supabase-jwt` auth mode it requires
 * `Authorization: Bearer <token>` on every non-`/health` request.
 * The token source differs by mode:
 *
 *   - **bearer mode** (Plan 045 §45.5.8): static value baked at
 *     build time from `gateway-shared-token` Secret Manager
 *     → `VITE_SUGARMAGIC_GATEWAY_BEARER_TOKEN`. Same value for the
 *     life of the bundle.
 *   - **supabase-jwt mode** (Plan 047 §47.9): the player's live
 *     Supabase access token, pulled from the active
 *     `UserIdentityProvider` per request. Auto-refreshes mid-
 *     session; absent when the player is signed out.
 *
 * Either way, the client takes a getter so the policy lives at
 * the factory call site, not buried in the client. `null` / empty
 * = `none` auth mode; the helper omits the header so the request
 * still works against a public gateway.
 */
export type BearerTokenGetter = () => Promise<string | null>;

async function authHeaders(
  getBearerToken: BearerTokenGetter
): Promise<Record<string, string>> {
  const token = await getBearerToken();
  const trimmed = typeof token === "string" ? token.trim() : "";
  return trimmed ? { authorization: `Bearer ${trimmed}` } : {};
}

export class SugarAgentGatewayLLMClient {
  constructor(
    private readonly baseUrl: string,
    private readonly getBearerToken: BearerTokenGetter = async () => null
  ) {}

  async generate(request: GatewayGenerateRequest): Promise<GatewayGenerateResult> {
    const response = await fetch(
      `${normalizeBaseUrl(this.baseUrl)}/api/sugaragent/generate`,
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          ...(await authHeaders(this.getBearerToken))
        },
        body: JSON.stringify(request)
      }
    );

    return parseJsonResponse<GatewayGenerateResult>(
      response,
      "SugarAgent gateway generate request"
    );
  }
}

export class SugarAgentGatewayVectorStoreClient {
  constructor(
    private readonly baseUrl: string,
    private readonly getBearerToken: BearerTokenGetter = async () => null
  ) {}

  async search(
    request: GatewayVectorSearchRequest
  ): Promise<GatewayVectorSearchResult> {
    const response = await fetch(
      `${normalizeBaseUrl(this.baseUrl)}/api/sugaragent/retrieve/search`,
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          ...(await authHeaders(this.getBearerToken))
        },
        body: JSON.stringify(request)
      }
    );

    return parseJsonResponse<GatewayVectorSearchResult>(
      response,
      "SugarAgent gateway vector search"
    );
  }
}

export class SugarAgentGatewayLLMProvider implements LLMProvider {
  constructor(
    private readonly client: SugarAgentGatewayLLMClient,
    private readonly defaults: { maxTokens?: number } = {}
  ) {}

  async generateStructuredTurn(request: LLMGenerateRequest): Promise<LLMGenerateResult> {
    const response = await this.client.generate({
      model: request.model.trim() || undefined,
      purpose: request.purpose,
      // Plan 072.5 — send the system prompt as one cacheable block (a single
      // cache breakpoint at the end of the full system prompt). sugaragent's
      // system half is byte-stable per session (072.4), so this caches per-NPC.
      systemBlocks: [
        { text: normalizePrompt(request.systemPrompt, "systemPrompt"), cache: true }
      ],
      userPrompt: normalizePrompt(request.userPrompt, "userPrompt"),
      maxTokens: normalizeMaxTokens(request.maxTokens, this.defaults.maxTokens ?? 300)
    });
    return {
      text: response.text,
      usage: response.usage ?? null,
      model: response.model ?? null
    };
  }
}

// ---------------------------------------------------------------------------
// Plan 075.1 -- judge client + provider
// ---------------------------------------------------------------------------

export interface JudgeRequest {
  replyText: string;
  personaDigest: string;
  responseIntent: string;
  worldContext: string | null;
  evidenceSummary: string[];
}

export interface JudgeVerdict {
  passed: boolean;
  violations: string[];
  repairHint: string | null;
}

export interface JudgeProvider {
  judgeReply: (request: JudgeRequest) => Promise<JudgeVerdict>;
}

export class SugarAgentGatewayJudgeClient {
  constructor(
    private readonly baseUrl: string,
    private readonly getBearerToken: BearerTokenGetter = async () => null
  ) {}

  async judge(request: JudgeRequest): Promise<JudgeVerdict> {
    const response = await fetch(
      `${normalizeBaseUrl(this.baseUrl)}/api/sugaragent/generate/judge`,
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          ...(await authHeaders(this.getBearerToken))
        },
        body: JSON.stringify(request)
      }
    );
    return parseJsonResponse<JudgeVerdict>(response, "SugarAgent gateway judge request");
  }
}

export class SugarAgentGatewayJudgeProvider implements JudgeProvider {
  constructor(private readonly client: SugarAgentGatewayJudgeClient) {}

  async judgeReply(request: JudgeRequest): Promise<JudgeVerdict> {
    return this.client.judge(request);
  }
}

// ---------------------------------------------------------------------------
// Plan 075.3 -- moderation client + provider
// ---------------------------------------------------------------------------

export interface ModerationRequest {
  text: string;
}

export interface ModerationResult {
  flagged: boolean;
  categories: string[];
  blocklisted: boolean;
}

export interface ModerationProvider {
  moderate: (request: ModerationRequest) => Promise<ModerationResult>;
}

export class SugarAgentGatewayModerationClient {
  constructor(
    private readonly baseUrl: string,
    private readonly getBearerToken: BearerTokenGetter = async () => null
  ) {}

  async moderate(request: ModerationRequest): Promise<ModerationResult> {
    const response = await fetch(
      `${normalizeBaseUrl(this.baseUrl)}/api/sugaragent/generate/moderate`,
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          ...(await authHeaders(this.getBearerToken))
        },
        body: JSON.stringify(request)
      }
    );
    return parseJsonResponse<ModerationResult>(response, "SugarAgent gateway moderation request");
  }
}

export class SugarAgentGatewayModerationProvider implements ModerationProvider {
  constructor(private readonly client: SugarAgentGatewayModerationClient) {}

  async moderate(request: ModerationRequest): Promise<ModerationResult> {
    return this.client.moderate(request);
  }
}

export class SugarAgentGatewayVectorStoreProvider implements VectorStoreProvider {
  constructor(private readonly client: SugarAgentGatewayVectorStoreClient) {}

  async searchLore(request: VectorStoreSearchRequest): Promise<RetrievedEvidenceItem[]> {
    const response = await this.client.search({
      vectorStoreId: request.vectorStoreId.trim() || undefined,
      query: normalizePrompt(request.query, "query"),
      maxResults: normalizeMaxResults(request.maxResults),
      filters: request.filters ?? undefined
    });
    return response.results;
  }
}

// ---------------------------------------------------------------------------
// Plan 072.3 — persona/core knowledge load via the existing lore/resolve route
// ---------------------------------------------------------------------------

export interface LoreResolveRequest {
  pageIds: string[];
}

export interface ResolvedLorePageSection {
  heading: string;
  slug: string;
  content: string;
}

export interface ResolvedLorePage {
  pageId: string;
  title: string;
  relativePath: string;
  sectionCount: number;
  body: string;
  sections: ResolvedLorePageSection[];
}

export interface LoreResolveResult {
  ok: boolean;
  pages: ResolvedLorePage[];
  missingPageIds: string[];
}

/**
 * Thin fetch client for the gateway's `POST /api/sugaragent/lore/resolve`
 * (072.2 already excludes `## Secrets` from the response). House shape: baseUrl
 * + BearerTokenGetter, `authHeaders` + `parseJsonResponse`.
 */
export class SugarAgentGatewayLoreClient {
  constructor(
    private readonly baseUrl: string,
    private readonly getBearerToken: BearerTokenGetter = async () => null
  ) {}

  async resolve(request: LoreResolveRequest): Promise<LoreResolveResult> {
    const response = await fetch(
      `${normalizeBaseUrl(this.baseUrl)}/api/sugaragent/lore/resolve`,
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          ...(await authHeaders(this.getBearerToken))
        },
        body: JSON.stringify(request)
      }
    );

    return parseJsonResponse<LoreResolveResult>(
      response,
      "SugarAgent gateway lore resolve"
    );
  }
}

export interface PersonaLoader {
  /** Resolve + designate the NPC's page. Null/empty id -> degraded persona. */
  loadPersona: (pageId: string | null) => Promise<LoadedPersona>;
}

function degradedPersona(pageId: string | null): LoadedPersona {
  return {
    pageId,
    loaded: false,
    fallbackReason: "persona-unavailable",
    personaCard: [],
    coreKnowledge: [],
    digest: ""
  };
}

/** Plan 072.8 — the number of `## Persona` lines the drift-reminder digest keeps. */
const PERSONA_DIGEST_LINE_COUNT = 4;

/**
 * Build the compact persona digest: the first PERSONA_DIGEST_LINE_COUNT
 * non-empty lines of `## Persona`, plus the full `## Voice` section. Computed
 * once at session start; empty string when neither is authored.
 */
export function buildPersonaDigest(personaCard: LoreCardSection[]): string {
  const personaLines = personaCard
    .filter((section) => section.slug === "persona")
    .flatMap((section) => section.content.split("\n"))
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .slice(0, PERSONA_DIGEST_LINE_COUNT);
  const voiceText = personaCard
    .filter((section) => section.slug === "voice")
    .map((section) => section.content.trim())
    .filter(Boolean)
    .join("\n");

  const parts: string[] = [];
  if (personaLines.length > 0) parts.push(personaLines.join("\n"));
  if (voiceText) parts.push(`Voice: ${voiceText}`);
  return parts.join("\n");
}

export class SugarAgentGatewayPersonaProvider implements PersonaLoader {
  constructor(private readonly client: SugarAgentGatewayLoreClient) {}

  // DEFERRED (Plan 072, revisit if session-start latency is felt): the persona
  // is fetched once per conversation. If refetching the same NPC's page across
  // conversations becomes a felt cost, add a browser-side cache keyed on
  // (pageId, content hash) here.
  async loadPersona(pageId: string | null): Promise<LoadedPersona> {
    const trimmed = typeof pageId === "string" ? pageId.trim() : "";
    if (!trimmed) {
      return degradedPersona(null);
    }
    const result = await this.client.resolve({ pageIds: [trimmed] });
    const page = result.pages.find((entry) => entry.pageId === trimmed);
    if (!page) {
      // A page in missingPageIds (or absent) IS the degraded path (D3).
      return degradedPersona(trimmed);
    }
    // `page.sections` matches DesignatableLoreSection structurally.
    const { personaCard, coreKnowledge } = designateLoreSections(
      page.sections as DesignatableLoreSection[]
    );
    const toCardSection = (section: DesignatableLoreSection) => ({
      heading: section.heading,
      slug: section.slug,
      content: section.content
    });
    const card = personaCard.map(toCardSection);
    return {
      pageId: trimmed,
      loaded: true,
      fallbackReason: null,
      personaCard: card,
      coreKnowledge: coreKnowledge.map(toCardSection),
      digest: buildPersonaDigest(card)
    };
  }
}
