import type { RetrievedEvidenceItem } from "./types";

export const OPENAI_VECTOR_STORE_PAGE_ID_ATTRIBUTE = "page_id";

export interface OpenAIVectorStoreEqFilter {
  type: "eq";
  key: string;
  value: string | number | boolean;
}

export type OpenAIVectorStoreFilter = OpenAIVectorStoreEqFilter;

export interface LLMGenerateRequest {
  model: string;
  systemPrompt: string;
  userPrompt: string;
  maxTokens?: number;
}

export interface LLMProvider {
  generateStructuredTurn: (request: LLMGenerateRequest) => Promise<string>;
}

export interface EmbeddingsProvider {
  embedQuery: (input: string, model: string) => Promise<number[]>;
}

export interface VectorStoreSearchRequest {
  vectorStoreId: string;
  query: string;
  maxResults: number;
  filters?: OpenAIVectorStoreFilter | null;
}

export interface VectorStoreProvider {
  searchLore: (request: VectorStoreSearchRequest) => Promise<RetrievedEvidenceItem[]>;
}

export interface GatewayGenerateRequest {
  model?: string;
  systemPrompt: string;
  userPrompt: string;
  maxTokens?: number;
}

export interface GatewayGenerateResult {
  text: string;
  requestId: string | null;
}

export interface GatewayEmbeddingRequest {
  input: string;
  model?: string;
}

export interface GatewayEmbeddingResult {
  embedding: number[];
  requestId: string | null;
}

export interface GatewayVectorSearchRequest {
  vectorStoreId?: string;
  query: string;
  maxResults: number;
  filters?: OpenAIVectorStoreFilter | null;
}

export interface GatewayVectorSearchResult {
  results: RetrievedEvidenceItem[];
  requestId: string | null;
}

interface VendorTextResult {
  text: string;
  requestId: string | null;
}

interface VendorEmbeddingResult {
  embedding: number[];
  requestId: string | null;
}

interface VendorVectorSearchResult {
  results: RetrievedEvidenceItem[];
  requestId: string | null;
}

// Story 46.14 — the gateway server.mjs (generated by SugarDeploy)
// owns all third-party API call shapes server-side. Browser-side
// SugarAgent talks to the gateway via the SugarAgentGateway* clients
// below; the direct-API request/response shapes that used to live
// here (AnthropicMessageRequest, OpenAIResponseRequest,
// OpenAIEmbeddingRequest, OpenAIVectorStoreSearchRequest) were
// deleted along with their client/provider classes when the
// direct-from-browser code path was removed.

function normalizeModel(model: string): string {
  const normalized = model.trim();
  if (!normalized) {
    throw new Error("Model identifier is required");
  }
  return normalized;
}

function normalizePrompt(text: string, field: string): string {
  const normalized = text.trim();
  if (!normalized) {
    throw new Error(`${field} is required`);
  }
  return normalized;
}

function normalizeMaxTokens(value: number | undefined, fallback: number): number {
  if (typeof value !== "number" || !Number.isFinite(value)) {
    return fallback;
  }
  return Math.max(1, Math.floor(value));
}

function normalizeMaxResults(value: number): number {
  if (!Number.isFinite(value)) return 4;
  return Math.max(1, Math.min(8, Math.floor(value)));
}

function normalizeBaseUrl(baseUrl: string): string {
  const normalized = baseUrl.trim().replace(/\/+$/, "");
  if (!normalized) {
    throw new Error("Gateway base URL is required");
  }
  return normalized;
}

async function parseJsonResponse<T>(response: Response, label: string): Promise<T> {
  if (!response.ok) {
    const body = await response.text();
    throw new Error(
      `${label} failed with status ${response.status}${body.trim() ? `: ${body}` : ""}`
    );
  }
  return (await response.json()) as T;
}

export class SugarAgentGatewayLLMClient {
  constructor(private readonly baseUrl: string) {}

  async generate(request: GatewayGenerateRequest): Promise<GatewayGenerateResult> {
    const response = await fetch(
      `${normalizeBaseUrl(this.baseUrl)}/api/sugaragent/generate`,
      {
        method: "POST",
        headers: {
          "content-type": "application/json"
        },
        body: JSON.stringify(request)
      }
    );

    return parseJsonResponse<GatewayGenerateResult>(
      response,
      "SugarAgent gateway generate request"
    );
  }
}

export class SugarAgentGatewayEmbeddingsClient {
  constructor(private readonly baseUrl: string) {}

  async createEmbedding(
    request: GatewayEmbeddingRequest
  ): Promise<GatewayEmbeddingResult> {
    const response = await fetch(
      `${normalizeBaseUrl(this.baseUrl)}/api/sugaragent/retrieve/embed`,
      {
        method: "POST",
        headers: {
          "content-type": "application/json"
        },
        body: JSON.stringify(request)
      }
    );

    return parseJsonResponse<GatewayEmbeddingResult>(
      response,
      "SugarAgent gateway embedding request"
    );
  }
}

export class SugarAgentGatewayVectorStoreClient {
  constructor(private readonly baseUrl: string) {}

  async search(
    request: GatewayVectorSearchRequest
  ): Promise<GatewayVectorSearchResult> {
    const response = await fetch(
      `${normalizeBaseUrl(this.baseUrl)}/api/sugaragent/retrieve/search`,
      {
        method: "POST",
        headers: {
          "content-type": "application/json"
        },
        body: JSON.stringify(request)
      }
    );

    return parseJsonResponse<GatewayVectorSearchResult>(
      response,
      "SugarAgent gateway vector search"
    );
  }
}

export class SugarAgentGatewayLLMProvider implements LLMProvider {
  constructor(
    private readonly client: SugarAgentGatewayLLMClient,
    private readonly defaults: { maxTokens?: number } = {}
  ) {}

  async generateStructuredTurn(request: LLMGenerateRequest): Promise<string> {
    const response = await this.client.generate({
      model: request.model.trim() || undefined,
      systemPrompt: normalizePrompt(request.systemPrompt, "systemPrompt"),
      userPrompt: normalizePrompt(request.userPrompt, "userPrompt"),
      maxTokens: normalizeMaxTokens(request.maxTokens, this.defaults.maxTokens ?? 300)
    });
    return response.text;
  }
}

export class SugarAgentGatewayEmbeddingsProvider implements EmbeddingsProvider {
  constructor(private readonly client: SugarAgentGatewayEmbeddingsClient) {}

  async embedQuery(input: string, model: string): Promise<number[]> {
    const response = await this.client.createEmbedding({
      input: normalizePrompt(input, "embedding input"),
      model: model.trim() || undefined
    });
    return response.embedding;
  }
}

export class SugarAgentGatewayVectorStoreProvider implements VectorStoreProvider {
  constructor(private readonly client: SugarAgentGatewayVectorStoreClient) {}

  async searchLore(request: VectorStoreSearchRequest): Promise<RetrievedEvidenceItem[]> {
    const response = await this.client.search({
      vectorStoreId: request.vectorStoreId.trim() || undefined,
      query: normalizePrompt(request.query, "query"),
      maxResults: normalizeMaxResults(request.maxResults),
      filters: request.filters ?? undefined
    });
    return response.results;
  }
}
