// GENERATED BY SUGARMAGIC - DO NOT EDIT directly in server.mjs.
// This file is typechecked TypeScript, compiled to JavaScript and written as
// server.mjs by buildGatewayServerFile. Do NOT import from @sugarmagic/* packages.

import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, extname, join, relative } from "node:path";
import {
  createHmac,
  createPublicKey,
  timingSafeEqual,
  verify as cryptoVerify
} from "node:crypto";
// Load-bearing despite looking unused: treeShaking is disabled in
// compile-options.ts precisely so this import survives into the compiled
// bundle for the supabase-jwt auth gate that buildGatewayServerFile injects.
import { verifySupabaseJwt } from "./supabase-jwt";
import { isSecretSection, composeLoreBody } from "./lore-designation";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface Route {
  routeId: string;
  path: string;
  protocol: string;
  consumer: string;
}

interface RouteManifest {
  serviceUnitId: string;
  targetId: string;
  authMode?: string;
  containerPort?: number;
  label?: string;
  owners?: string[];
  routes: Route[];
}

interface LoreIngestState {
  active: boolean;
  phase: string;
  pageCount: number;
  chunkCount: number;
  uploadedCount: number;
  currentChunkId: string | null;
  message: string;
  warnings: string[];
  startedAt: string | null;
  completedAt: string | null;
}

interface LoreSection {
  heading: string;
  slug: string;
  content: string;
}

interface LorePage {
  pageId: string;
  title: string;
  relativePath: string;
  sectionCount: number;
  body: string;
  sections: LoreSection[];
}

interface LoreChunk {
  pageId: string;
  chunkId: string;
  title: string;
  sectionHeading: string;
  sectionSlug: string;
  relativePath: string;
  embeddingText: string;
}

interface LoreSource {
  sourceKind: string;
  sourcePath: string | null;
  repositoryUrl: string;
  repositoryRef: string;
  sourceReady: boolean;
  warning: string | null;
}

// ---------------------------------------------------------------------------
// Module-level state (set by initGateway; empty until called)
// ---------------------------------------------------------------------------

let _routes: Route[] = [];
let _serviceUnitId = "";
let _targetId = "";

const _loreIngestState: LoreIngestState = {
  active: false,
  phase: "idle",
  pageCount: 0,
  chunkCount: 0,
  uploadedCount: 0,
  currentChunkId: null,
  message: "Idle",
  warnings: [],
  startedAt: null,
  completedAt: null
};

// Story 46.9 — CORS allowed-origin patterns come from terraform via
// SUGARMAGIC_GATEWAY_ALLOWED_ORIGINS (comma-joined). Each entry is
// either an exact origin ("https://foo.com") or a single-'*'
// wildcard pattern ("https://*--site.netlify.app"). The gateway
// pattern-matches each request's Origin header at request time and
// only emits Access-Control-Allow-Origin when there's a hit. Empty
// list = no ACAO header emitted, blocking browsers.
let _allowedOriginPatterns: string[] = [];

export function initGateway(manifest: RouteManifest): void {
  _routes = manifest.routes ?? [];
  _serviceUnitId = manifest.serviceUnitId ?? "";
  _targetId = manifest.targetId ?? "";
  _allowedOriginPatterns = (
    process.env["SUGARMAGIC_GATEWAY_ALLOWED_ORIGINS"] ?? ""
  )
    .split(",")
    .map((entry) => entry.trim())
    .filter((entry) => entry.length > 0);
}

export function resetLoreIngestState(): void {
  Object.assign(_loreIngestState, {
    active: false,
    phase: "idle",
    pageCount: 0,
    chunkCount: 0,
    uploadedCount: 0,
    currentChunkId: null,
    message: "Idle",
    warnings: [],
    startedAt: null,
    completedAt: null
  });
}

// ---------------------------------------------------------------------------
// CORS helpers
// ---------------------------------------------------------------------------

export function resolveAllowedOrigin(origin: string | undefined): string | null {
  if (!origin) return null;
  for (const pattern of _allowedOriginPatterns) {
    if (pattern === origin) return origin;
    const wildcardIndex = pattern.indexOf("*");
    if (wildcardIndex >= 0) {
      const prefix = pattern.slice(0, wildcardIndex);
      const suffix = pattern.slice(wildcardIndex + 1);
      if (
        origin.length >= prefix.length + suffix.length &&
        origin.startsWith(prefix) &&
        origin.endsWith(suffix)
      ) {
        return origin;
      }
    }
  }
  return null;
}

const _baseHeaders = {
  "content-type": "application/json; charset=utf-8"
};

export function resolveCorsHeaders(req: IncomingMessage): Record<string, string> {
  const headers: Record<string, string> = { vary: "origin" };
  const origin = req?.headers?.origin;
  const echoOrigin = resolveAllowedOrigin(origin);
  if (echoOrigin) {
    headers["access-control-allow-origin"] = echoOrigin;
    headers["access-control-allow-credentials"] = "true";
  }
  return headers;
}

// Stash the per-request resolved CORS headers on the response so the
// many sendJson call sites stay one-arg and don't have to thread req
// through every helper. The top of createServer sets it once per req.
export function sendJson(res: ServerResponse & { __sugarmagicCors?: Record<string, string> }, statusCode: number, payload: unknown): void {
  res.writeHead(statusCode, {
    ..._baseHeaders,
    ...(res.__sugarmagicCors ?? {})
  });
  res.end(JSON.stringify(payload, null, 2));
}

export function logInfo(message: string, payload?: unknown): void {
  const suffix =
    payload && typeof payload === "object"
      ? " " + JSON.stringify(payload)
      : payload != null
        ? " " + String(payload)
        : "";
  console.log("[sugardeploy] " + message + suffix);
}

export function logError(message: string, error: unknown, payload?: Record<string, unknown>): void {
  const details = {
    ...(payload && typeof payload === "object" ? payload : {}),
    error: error instanceof Error ? error.message : String(error)
  };
  console.error("[sugardeploy] " + message + " " + JSON.stringify(details));
}

function updateLoreIngestState(patch: Partial<LoreIngestState>): void {
  Object.assign(_loreIngestState, patch);
}

export function sendMethodNotAllowed(res: ServerResponse & { __sugarmagicCors?: Record<string, string> }, allowed: string[]): void {
  res.writeHead(405, {
    ..._baseHeaders,
    ...(res.__sugarmagicCors ?? {}),
    allow: allowed.join(", ")
  });
  res.end(
    JSON.stringify(
      {
        ok: false,
        error: "MethodNotAllowed",
        allowed
      },
      null,
      2
    )
  );
}

export function normalizePath(url: string | undefined): string {
  return (url || "/").split("?")[0] || "/";
}

// Story 45.5.8 — bearer-token authorization. Constant-time compare via
// node:crypto.timingSafeEqual prevents timing-based token guessing. Length
// mismatch short-circuits with false (timingSafeEqual requires equal-length
// buffers). The expected token comes from the deployment secret env var
// resolved at request time; missing env var (e.g. secret wasn't Set Value'd
// after enabling bearer mode) means the gate denies everything except /health.
export function authorizeBearer(req: IncomingMessage): boolean {
  const expected = process.env["SUGARMAGIC_GATEWAY_SHARED_TOKEN"] || "";
  if (!expected) return false;
  const header = (req.headers && req.headers["authorization"]) || "";
  const prefix = "Bearer ";
  if (typeof header !== "string" || !header.startsWith(prefix)) return false;
  const presented = header.slice(prefix.length).trim();
  if (!presented) return false;
  const expectedBuf = Buffer.from(expected, "utf8");
  const presentedBuf = Buffer.from(presented, "utf8");
  if (expectedBuf.length !== presentedBuf.length) return false;
  try {
    return timingSafeEqual(expectedBuf, presentedBuf);
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------
// Utility helpers
// ---------------------------------------------------------------------------

function resolveEnv(name: string, fallback = ""): string {
  const value = process.env[name];
  return typeof value === "string" ? value.trim() || fallback : fallback;
}

function requireEnv(name: string): string {
  const value = resolveEnv(name);
  if (!value) {
    throw new Error("Missing required environment variable: " + name);
  }
  return value;
}

async function readJsonBody(req: IncomingMessage): Promise<Record<string, unknown>> {
  let requestBody = "";
  for await (const chunk of req) {
    requestBody += chunk.toString();
  }
  if (!requestBody.trim()) {
    return {};
  }
  try {
    return JSON.parse(requestBody) as Record<string, unknown>;
  } catch {
    throw new Error("Request body must be valid JSON.");
  }
}

async function parseApiJsonResponse(response: Response, label: string): Promise<unknown> {
  const raw = await response.text();
  let payload: unknown = null;
  if (raw.trim()) {
    try {
      payload = JSON.parse(raw);
    } catch {
      payload = raw;
    }
  }
  if (!response.ok) {
    throw new Error(
      label +
        " failed with status " +
        response.status +
        (raw.trim() ? ": " + raw : "")
    );
  }
  return payload;
}

async function requestJson(
  url: string,
  options: RequestInit,
  label: string
): Promise<{ payload: unknown; headers: Headers }> {
  logInfo("upstream:request", {
    label,
    url,
    method: options?.method ?? "GET"
  });
  const response = await fetch(url, options);
  const raw = await response.text();
  let payload: unknown = null;
  if (raw.trim()) {
    try {
      payload = JSON.parse(raw);
    } catch {
      payload = raw;
    }
  }
  if (!response.ok) {
    logError(label + " failed", new Error("upstream non-2xx"), {
      url,
      status: response.status,
      body: raw
    });
    throw new Error(
      label +
        " failed with status " +
        response.status +
        (typeof payload === "string"
          ? ": " + payload
          : payload && typeof payload === "object" && "error" in payload
            ? ": " + JSON.stringify(payload)
            : "")
    );
  }
  return {
    payload,
    headers: response.headers
  };
}

// ---------------------------------------------------------------------------
// Lore helpers
// ---------------------------------------------------------------------------

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "section";
}

function sanitizeFilename(value: string): string {
  return value.replace(/[^a-z0-9._-]+/gi, "-").replace(/-+/g, "-");
}

export function parseFrontmatter(raw: string): { metadata: Record<string, string>; body: string } {
  if (!raw.startsWith("---\n")) {
    return {
      metadata: {},
      body: raw
    };
  }

  const closingIndex = raw.indexOf("\n---\n", 4);
  if (closingIndex === -1) {
    return {
      metadata: {},
      body: raw
    };
  }

  const frontmatter = raw.slice(4, closingIndex);
  const body = raw.slice(closingIndex + 5);
  const metadata: Record<string, string> = {};
  for (const line of frontmatter.split("\n")) {
    const separatorIndex = line.indexOf(":");
    if (separatorIndex === -1) continue;
    const key = line.slice(0, separatorIndex).trim();
    const value = line.slice(separatorIndex + 1).trim();
    if (!key) continue;
    metadata[key] = value.replace(/^['"]|['"]$/g, "");
  }
  return {
    metadata,
    body
  };
}

export function splitLoreSections(markdown: string): LoreSection[] {
  const lines = markdown.split("\n");
  const sections: LoreSection[] = [];
  let current: { heading: string; slug: string; contentLines: string[] } = {
    heading: "Overview",
    slug: "overview",
    contentLines: []
  };

  for (const line of lines) {
    const headingMatch = /^(#{1,6})\s+(.+)$/.exec(line.trim());
    if (headingMatch) {
      const content = current.contentLines.join("\n").trim();
      if (content) {
        sections.push({
          heading: current.heading,
          slug: current.slug,
          content
        });
      }
      const heading = headingMatch[2]!.trim();
      current = {
        heading,
        slug: slugify(heading),
        contentLines: []
      };
      continue;
    }
    current.contentLines.push(line);
  }

  const trailingContent = current.contentLines.join("\n").trim();
  if (trailingContent) {
    sections.push({
      heading: current.heading,
      slug: current.slug,
      content: trailingContent
    });
  }

  return sections.length > 0
    ? sections
    : [
        {
          heading: "Overview",
          slug: "overview",
          content: markdown.trim()
        }
      ];
}

function walkMarkdownFiles(rootDir: string, currentDir = rootDir, files: string[] = []): string[] {
  for (const entry of readdirSync(currentDir, { withFileTypes: true })) {
    const absolutePath = join(currentDir, entry.name);
    if (entry.isDirectory()) {
      walkMarkdownFiles(rootDir, absolutePath, files);
      continue;
    }
    const extension = extname(entry.name).toLowerCase();
    if (extension === ".md" || extension === ".markdown") {
      files.push(absolutePath);
    }
  }
  return files;
}

function resolveLoreSource(): LoreSource {
  const sourceKind = resolveEnv("SUGARMAGIC_LORE_SOURCE_KIND", "local");
  const sourcePath = resolveEnv("SUGARMAGIC_LORE_SOURCE_PATH");
  const repositoryUrl = resolveEnv("SUGARMAGIC_LORE_SOURCE_REPOSITORY_URL");
  const repositoryRef = resolveEnv("SUGARMAGIC_LORE_SOURCE_REPOSITORY_REF", "main");

  if (sourceKind === "github") {
    return {
      sourceKind,
      sourcePath: null,
      repositoryUrl,
      repositoryRef,
      sourceReady: false,
      warning:
        "GitHub-backed lore source resolution is planned but not implemented yet. Use a local checked-out lore repo for now."
    };
  }

  if (!sourcePath) {
    return {
      sourceKind: "local",
      sourcePath: null,
      repositoryUrl,
      repositoryRef,
      sourceReady: false,
      warning: "SUGARMAGIC_LORE_SOURCE_PATH is not configured in the gateway environment."
    };
  }

  try {
    const stats = statSync(sourcePath);
    if (!stats.isDirectory()) {
      return {
        sourceKind: "local",
        sourcePath,
        repositoryUrl,
        repositoryRef,
        sourceReady: false,
        warning: "Configured lore source path is not a directory: " + sourcePath
      };
    }
  } catch (error) {
    return {
      sourceKind: "local",
      sourcePath,
      repositoryUrl,
      repositoryRef,
      sourceReady: false,
      warning:
        "Configured lore source path is not readable: " +
        sourcePath +
        " (" +
        (error instanceof Error ? error.message : String(error)) +
        ")"
    };
  }

  return {
    sourceKind: "local",
    sourcePath,
    repositoryUrl,
    repositoryRef,
    sourceReady: true,
    warning: null
  };
}

export function readLorePages(): { source: LoreSource; pages: LorePage[]; chunks: LoreChunk[]; warnings: string[] } {
  const source = resolveLoreSource();
  if (!source.sourceReady || !source.sourcePath) {
    return {
      source,
      pages: [],
      chunks: [],
      warnings: source.warning ? [source.warning] : []
    };
  }

  const warnings: string[] = source.warning ? [source.warning] : [];
  const pages: LorePage[] = [];
  const chunks: LoreChunk[] = [];
  const markdownFiles = walkMarkdownFiles(source.sourcePath);

  for (const absolutePath of markdownFiles) {
    const raw = readFileSync(absolutePath, "utf8");
    const { metadata, body } = parseFrontmatter(raw);
    const pageId = typeof metadata["id"] === "string" ? metadata["id"].trim() : "";
    if (!pageId) {
      warnings.push(
        "Skipped lore page without frontmatter id: " +
          relative(source.sourcePath, absolutePath)
      );
      continue;
    }

    const relativePath = relative(source.sourcePath, absolutePath);
    const title =
      (typeof metadata["title"] === "string" && metadata["title"].trim()) ||
      pageId.split(".").at(-1) ||
      pageId;
    const sections = splitLoreSections(body);

    pages.push({
      pageId,
      title,
      relativePath,
      sectionCount: sections.length,
      body,
      sections
    });

    for (const section of sections) {
      // Plan 072.1: `## Secrets` never enters the vector index. The section
      // stays in `pages[].sections` (072.2 strips it from lore/resolve); only
      // the ingest chunks exclude it here.
      if (isSecretSection(section)) continue;
      const chunkId = pageId + "#" + section.slug;
      const embeddingText = [
        "Page ID: " + pageId,
        "Title: " + title,
        "Section: " + section.heading,
        section.content
      ]
        .filter(Boolean)
        .join("\n\n");

      chunks.push({
        pageId,
        chunkId,
        title,
        sectionHeading: section.heading,
        sectionSlug: section.slug,
        relativePath,
        embeddingText
      });
    }
  }

  pages.sort((left, right) => left.pageId.localeCompare(right.pageId));
  chunks.sort((left, right) => left.chunkId.localeCompare(right.chunkId));

  return {
    source,
    pages,
    chunks,
    warnings
  };
}

// ---------------------------------------------------------------------------
// Vector store helpers
// ---------------------------------------------------------------------------

async function listVectorStoreFiles(vectorStoreId: string): Promise<Record<string, unknown>[]> {
  const items: Record<string, unknown>[] = [];
  let after = "";

  while (true) {
    const query = after ? "?after=" + encodeURIComponent(after) : "";
    const { payload } = await requestJson(
      "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/files" + query,
      {
        method: "GET",
        headers: {
          authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
        }
      },
      "OpenAI vector store file list"
    );

    const batch = Array.isArray((payload as { data?: unknown })?.data)
      ? (payload as { data: Record<string, unknown>[] }).data
      : [];
    items.push(...batch);
    if (!(payload as { has_more?: boolean })?.has_more || batch.length === 0) {
      break;
    }
    after = typeof batch[batch.length - 1]?.["id"] === "string"
      ? batch[batch.length - 1]!["id"] as string
      : "";
    if (!after) break;
  }

  return items;
}

async function deleteVectorStoreFile(vectorStoreId: string, vectorStoreFileId: string): Promise<void> {
  await requestJson(
    "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/files/" + vectorStoreFileId,
    {
      method: "DELETE",
      headers: {
        authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
      }
    },
    "OpenAI vector store file delete"
  );
}

async function uploadChunkToVectorStore(
  vectorStoreId: string,
  chunk: LoreChunk,
  onProgress: ((progress: { phase: string; currentChunkId: string; message: string }) => void) | null = null
): Promise<Record<string, unknown>> {
  onProgress?.({
    phase: "uploading",
    currentChunkId: chunk.chunkId,
    message: "Uploading chunk " + chunk.chunkId
  });
  const fileUpload = new FormData();
  fileUpload.append("purpose", "user_data");
  fileUpload.append(
    "file",
    new Blob([chunk.embeddingText], { type: "text/markdown" }),
    sanitizeFilename(chunk.chunkId) + ".md"
  );

  const uploadResponse = await fetch("https://api.openai.com/v1/files", {
    method: "POST",
    headers: {
      authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
    },
    body: fileUpload
  });
  const uploadPayload = await parseApiJsonResponse(
    uploadResponse,
    "OpenAI file upload"
  ) as Record<string, unknown>;

  const attachResponse = await fetch(
    "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/files",
    {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
      },
      body: JSON.stringify({
        file_id: uploadPayload["id"],
        attributes: {
          page_id: chunk.pageId,
          chunk_id: chunk.chunkId,
          section_slug: chunk.sectionSlug,
          section_heading: chunk.sectionHeading,
          title: chunk.title,
          relative_path: chunk.relativePath
        }
      })
    }
  );
  const vectorStoreFile = await parseApiJsonResponse(
    attachResponse,
    "OpenAI vector store file attach"
  ) as Record<string, unknown>;

  let attempts = 0;
  while (attempts < 30) {
    onProgress?.({
      phase: "waiting-for-indexing",
      currentChunkId: chunk.chunkId,
      message: "Waiting for indexing for " + chunk.chunkId
    });
    const statusResponse = await fetch(
      "https://api.openai.com/v1/vector_stores/" +
        vectorStoreId +
        "/files/" +
        vectorStoreFile["id"],
      {
        method: "GET",
        headers: {
          authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
        }
      }
    );
    const statusPayload = await parseApiJsonResponse(
      statusResponse,
      "OpenAI vector store file status"
    ) as Record<string, unknown>;
    if (statusPayload["status"] === "completed") {
      return vectorStoreFile;
    }
    if (statusPayload["status"] === "failed" || statusPayload["status"] === "cancelled") {
      throw new Error(
        "Vector store file processing failed for " +
          chunk.chunkId +
          " with status " +
          statusPayload["status"]
      );
    }
    await new Promise((resolve) => setTimeout(resolve, 1000));
    attempts += 1;
  }

  throw new Error(
    "Timed out waiting for vector store processing for chunk " + chunk.chunkId
  );
}

function findManagedRoute(path: string): Route | undefined {
  return _routes.find(
    (route) => path === route.path || path.startsWith(route.path + "/")
  );
}

// ---------------------------------------------------------------------------
// Request handlers
// ---------------------------------------------------------------------------

export async function handleSugarAgentGenerate(
  req: IncomingMessage,
  res: ServerResponse & { __sugarmagicCors?: Record<string, string> }
): Promise<void> {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }

  const body = await readJsonBody(req);
  const model =
    typeof body["model"] === "string" && body["model"].trim()
      ? body["model"].trim()
      : resolveEnv("SUGARMAGIC_SUGARAGENT_ANTHROPIC_MODEL", "claude-sonnet-4-5");
  const systemPrompt =
    typeof body["systemPrompt"] === "string" ? body["systemPrompt"].trim() : "";
  const userPrompt =
    typeof body["userPrompt"] === "string" ? body["userPrompt"].trim() : "";
  const maxTokens =
    typeof body["maxTokens"] === "number" && Number.isFinite(body["maxTokens"])
      ? Math.max(1, Math.floor(body["maxTokens"]))
      : 300;

  if (!systemPrompt || !userPrompt) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidRequest",
      message: "systemPrompt and userPrompt are required."
    });
    return;
  }

  const { payload, headers } = await requestJson(
    "https://api.anthropic.com/v1/messages",
    {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": requireEnv("SUGARMAGIC_ANTHROPIC_API_KEY"),
        "anthropic-version": "2023-06-01"
      },
      body: JSON.stringify({
        model,
        max_tokens: maxTokens,
        system: systemPrompt,
        messages: [
          {
            role: "user",
            content: userPrompt
          }
        ]
      })
    },
    "Anthropic request"
  );

  const text = Array.isArray((payload as { content?: unknown[] })?.content)
    ? (payload as { content: Array<{ type: string; text?: string }> }).content
        .filter((block) => block?.type === "text" && typeof block.text === "string")
        .map((block) => block.text!.trim())
        .filter(Boolean)
        .join("\n\n")
    : "";

  if (!text) {
    throw new Error("Anthropic response did not include text content.");
  }

  sendJson(res, 200, {
    text,
    requestId: headers.get("request-id")
  });
}

export async function handleSugarAgentSearch(
  req: IncomingMessage,
  res: ServerResponse & { __sugarmagicCors?: Record<string, string> }
): Promise<void> {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }

  const body = await readJsonBody(req);
  const query = typeof body["query"] === "string" ? body["query"].trim() : "";
  const vectorStoreId =
    typeof body["vectorStoreId"] === "string" && body["vectorStoreId"].trim()
      ? body["vectorStoreId"].trim()
      : resolveEnv("SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID");
  const maxResults =
    typeof body["maxResults"] === "number" && Number.isFinite(body["maxResults"])
      ? Math.max(1, Math.min(8, Math.floor(body["maxResults"])))
      : 4;

  if (!query || !vectorStoreId) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidRequest",
      message: "query and vectorStoreId are required."
    });
    return;
  }

  const { payload, headers } = await requestJson(
    "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/search",
    {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
      },
      body: JSON.stringify({
        query,
        max_num_results: maxResults,
        filters:
          body["filters"] && typeof body["filters"] === "object" && !Array.isArray(body["filters"])
            ? body["filters"]
            : undefined
      })
    },
    "OpenAI vector search"
  );

  const results = Array.isArray((payload as { data?: unknown[] })?.data)
    ? (payload as { data: Array<Record<string, unknown>> }).data.map((result, index) => ({
        fileId:
          typeof result?.["file_id"] === "string" ? result["file_id"] : "vector-result-" + index,
        filename: typeof result?.["filename"] === "string" ? result["filename"] : "unknown",
        score: typeof result?.["score"] === "number" ? result["score"] : 0,
        attributes:
          result?.["attributes"] && typeof result["attributes"] === "object"
            ? result["attributes"]
            : {},
        text: Array.isArray(result?.["content"])
          ? (result["content"] as Array<{ type: string; text?: string }>)
              .filter((item) => item?.type === "text" && typeof item.text === "string")
              .map((item) => item.text!.trim())
              .filter(Boolean)
              .join("\n\n")
          : ""
      }))
    : [];

  sendJson(res, 200, {
    results,
    requestId: headers.get("x-request-id")
  });
}

export async function handleSugarAgentLoreStatus(
  req: IncomingMessage,
  res: ServerResponse & { __sugarmagicCors?: Record<string, string> }
): Promise<void> {
  if (req.method !== "GET") {
    sendMethodNotAllowed(res, ["GET", "OPTIONS"]);
    return;
  }

  const lore = readLorePages();
  const vectorStoreId = resolveEnv("SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID") || null;
  sendJson(res, 200, {
    ok: true,
    sourceKind: lore.source.sourceKind,
    sourceReady: lore.source.sourceReady,
    sourcePath: lore.source.sourcePath,
    vectorStoreId,
    pageCount: lore.pages.length,
    chunkCount: lore.chunks.length,
    warnings: lore.warnings,
    ingest: { ..._loreIngestState }
  });
}

export async function handleSugarAgentLorePages(
  req: IncomingMessage,
  res: ServerResponse & { __sugarmagicCors?: Record<string, string> }
): Promise<void> {
  if (req.method !== "GET") {
    sendMethodNotAllowed(res, ["GET", "OPTIONS"]);
    return;
  }

  const lore = readLorePages();
  sendJson(res, 200, {
    ok: true,
    pages: lore.pages.map((page) => ({
      pageId: page.pageId,
      title: page.title,
      relativePath: page.relativePath,
      sectionCount: page.sectionCount
    })),
    warnings: lore.warnings
  });
}

export async function handleSugarAgentLoreResolve(
  req: IncomingMessage,
  res: ServerResponse & { __sugarmagicCors?: Record<string, string> }
): Promise<void> {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }

  const body = await readJsonBody(req);
  const rawPageIds = Array.isArray(body?.["pageIds"]) ? body["pageIds"] as unknown[] : [];
  const pageIds = [...new Set(
    rawPageIds
      .filter((value) => typeof value === "string")
      .map((value) => (value as string).trim())
      .filter(Boolean)
  )].sort((left, right) => left.localeCompare(right));

  if (pageIds.length === 0) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidRequest",
      message: "pageIds must contain at least one non-empty lore page id."
    });
    return;
  }

  const lore = readLorePages();
  const pagesById = new Map(
    lore.pages.map((page) => [page.pageId, page])
  );
  const resolvedPages: LorePage[] = [];
  const missingPageIds: string[] = [];

  for (const pageId of pageIds) {
    const page = pagesById.get(pageId);
    if (!page) {
      missingPageIds.push(pageId);
      continue;
    }
    // Plan 072.2: `## Secrets` must not leave the gateway. Strip it from BOTH
    // `sections` and `body` (sugarlang's consumer feeds each into the scene
    // lexicon). Pages without a secret section pass through byte-identical --
    // only recompute `body` when a secret is actually being removed, so the
    // raw markdown is preserved for the common case.
    const hasSecret = page.sections.some(isSecretSection);
    if (!hasSecret) {
      resolvedPages.push({
        pageId: page.pageId,
        title: page.title,
        relativePath: page.relativePath,
        sectionCount: page.sectionCount,
        body: page.body,
        sections: page.sections
      });
      continue;
    }
    const visibleSections = page.sections.filter(
      (section) => !isSecretSection(section)
    );
    resolvedPages.push({
      pageId: page.pageId,
      title: page.title,
      relativePath: page.relativePath,
      sectionCount: visibleSections.length,
      body: composeLoreBody(visibleSections),
      sections: visibleSections
    });
  }

  sendJson(res, 200, {
    ok: true,
    pages: resolvedPages,
    missingPageIds,
    warnings: lore.warnings
  });
}

export async function handleSugarAgentLoreIngest(
  req: IncomingMessage,
  res: ServerResponse & { __sugarmagicCors?: Record<string, string> }
): Promise<void> {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }

  const body = await readJsonBody(req);
  const mode = "overwrite";
  const vectorStoreId =
    typeof body["vectorStoreId"] === "string" && body["vectorStoreId"].trim()
      ? body["vectorStoreId"].trim()
      : resolveEnv("SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID");

  if (!vectorStoreId) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidRequest",
      message: "vectorStoreId is required."
    });
    return;
  }

  const lore = readLorePages();
  if (!lore.source.sourceReady) {
    sendJson(res, 400, {
      ok: false,
      error: "LoreSourceUnavailable",
      message: lore.warnings[0] ?? "Lore source is not available."
    });
    return;
  }

  if (lore.chunks.length === 0) {
    sendJson(res, 400, {
      ok: false,
      error: "LoreSourceEmpty",
      message: "No lore pages with canonical frontmatter ids were found in the configured lore source.",
      warnings: lore.warnings
    });
    return;
  }

  updateLoreIngestState({
    active: true,
    phase: "parsed",
    pageCount: lore.pages.length,
    chunkCount: lore.chunks.length,
    uploadedCount: 0,
    currentChunkId: null,
    message: "Parsed " + lore.pages.length + " pages into " + lore.chunks.length + " chunks.",
    warnings: lore.warnings,
    startedAt: new Date().toISOString(),
    completedAt: null
  });

  try {
    if (mode === "overwrite") {
      updateLoreIngestState({
        phase: "clearing-store",
        message: "Clearing existing vector store contents before overwrite."
      });
      const existingFiles = await listVectorStoreFiles(vectorStoreId);
      for (const item of existingFiles) {
        if (typeof item?.["id"] === "string") {
          await deleteVectorStoreFile(vectorStoreId, item["id"] as string);
        }
      }
    }

    let uploadedCount = 0;
    for (const chunk of lore.chunks) {
      await uploadChunkToVectorStore(vectorStoreId, chunk, (progress) => {
        updateLoreIngestState({
          phase: progress.phase,
          currentChunkId: progress.currentChunkId ?? null,
          message: progress.message,
          uploadedCount
        });
      });
      uploadedCount += 1;
      updateLoreIngestState({
        phase: "uploading",
        currentChunkId: chunk.chunkId,
        uploadedCount,
        message: "Uploaded " + uploadedCount + " / " + lore.chunks.length + " chunks."
      });
    }

    updateLoreIngestState({
      active: false,
      phase: "completed",
      currentChunkId: null,
      uploadedCount,
      message: "Completed lore ingest.",
      completedAt: new Date().toISOString()
    });

    sendJson(res, 200, {
      ok: true,
      mode,
      vectorStoreId,
      pageCount: lore.pages.length,
      chunkCount: lore.chunks.length,
      uploadedCount,
      warnings: lore.warnings
    });
  } catch (error) {
    updateLoreIngestState({
      active: false,
      phase: "failed",
      message: error instanceof Error ? error.message : String(error),
      completedAt: new Date().toISOString()
    });
    throw error;
  }
}

// ---------------------------------------------------------------------------
// Server
// ---------------------------------------------------------------------------

type GatewayRequest = IncomingMessage & { __sugarmagicCors?: Record<string, string>; user?: { userId: string; email: string | null } };
type GatewayResponse = ServerResponse & { __sugarmagicCors?: Record<string, string> };

export const server = createServer(async (req: GatewayRequest, res: GatewayResponse) => {
  // Story 46.9 — resolve CORS headers once per request, stash on the
  // response, then sendJson / sendMethodNotAllowed read them off the
  // response so call sites don't have to thread req.
  res.__sugarmagicCors = resolveCorsHeaders(req);

  if (req.method === "OPTIONS") {
    // CORS preflight. Echo the request's
    // access-control-request-headers verbatim when present so we don't
    // have to enumerate them; fall back to a safe default.
    const requestedHeaders = req.headers["access-control-request-headers"];
    res.writeHead(204, {
      ..._baseHeaders,
      ...res.__sugarmagicCors,
      "access-control-allow-methods": "GET,POST,PUT,PATCH,DELETE,OPTIONS",
      "access-control-allow-headers":
        typeof requestedHeaders === "string" && requestedHeaders.length > 0
          ? requestedHeaders
          : "content-type, authorization",
      "access-control-max-age": "86400"
    });
    res.end();
    return;
  }

  const path = normalizePath(req.url);
  logInfo("gateway:request", {
    method: req.method ?? "GET",
    path
  });
  // /health (not /healthz): Cloud Run's frontend reserves /healthz
  // specifically — it gets intercepted before reaching the container,
  // returning Google's generic 404 page with no x-cloud-trace-context
  // header. Discovered the hard way during 45.5.7 verification.
  if (path === "/" || path === "/health") {
    sendJson(res, 200, {
      ok: true,
      target: _targetId,
      serviceUnitId: _serviceUnitId,
      routes: _routes
    });
    return;
  }

  // Story 45.5.8 / Story 47.9 — auth gate. Assembled based on the effective
  // gatewayAuthMode at plan time:
  //   - "none"          -> no gate
  //   - "bearer"        -> shared-token check (45.5.8)
  //   - "supabase-jwt"  -> Supabase HS256/ES256 verification (47.9)
  // /health stays public above; this gate runs on EVERY other path before
  // the route dispatcher.
  /*! __GATEWAY_AUTH_GATE__ */

  const match = findManagedRoute(path);
  if (!match) {
    logInfo("gateway:route-not-managed", {
      path,
      knownRoutes: _routes.map((route) => route.path)
    });
    sendJson(res, 404, {
      ok: false,
      error: "RouteNotManaged",
      message: "SugarDeploy generated this gateway scaffold, but the requested route is not declared for this service unit.",
      path,
      knownRoutes: _routes.map((route) => route.path)
    });
    return;
  }

  try {
    if (match.routeId === "sugaragent-generate" && path === match.path) {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentGenerate(req, res);
      return;
    }

    if (match.routeId === "sugaragent-retrieve" && path === match.path + "/search") {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentSearch(req, res);
      return;
    }

    if (match.routeId === "sugaragent-lore" && path === match.path + "/status") {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentLoreStatus(req, res);
      return;
    }

    if (match.routeId === "sugaragent-lore" && path === match.path + "/pages") {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentLorePages(req, res);
      return;
    }

    if (match.routeId === "sugaragent-lore" && path === match.path + "/resolve") {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentLoreResolve(req, res);
      return;
    }

    if (match.routeId === "sugaragent-lore" && path === match.path + "/ingest") {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentLoreIngest(req, res);
      return;
    }

    logInfo("gateway:route-unimplemented", {
      routeId: match.routeId,
      path
    });
    sendJson(res, 501, {
      ok: false,
      error: "ProxyHandlerNotImplemented",
      target: _targetId,
      serviceUnitId: _serviceUnitId,
      route: match,
      request: {
        method: req.method,
        path
      },
      message:
        "SugarDeploy generated the backend gateway scaffold for this route, but no concrete handler is registered for this path yet."
    });
  } catch (error) {
    logError("gateway:handler-failure", error, {
      routeId: match.routeId,
      path
    });
    sendJson(res, 500, {
      ok: false,
      error: "GatewayProxyFailure",
      target: _targetId,
      serviceUnitId: _serviceUnitId,
      route: match,
      path,
      message: error instanceof Error ? error.message : String(error)
    });
  }
});

// ---------------------------------------------------------------------------
// Entry point (only when run as a script, not when imported for testing)
// ---------------------------------------------------------------------------

const __gatewayFilename = fileURLToPath(import.meta.url);
if (process.argv[1] === __gatewayFilename) {
  const __dir = dirname(__gatewayFilename);
  const manifest = JSON.parse(readFileSync(join(__dir, "routes.json"), "utf8")) as RouteManifest;
  initGateway(manifest);
  const port = Number(process.env["PORT"] || manifest.containerPort || 8080);
  server.listen(port, () => {
    console.log("[sugardeploy] gateway " + manifest.serviceUnitId + " listening on port " + port);
  });
}
