// GENERATED BY SUGARMAGIC - DO NOT EDIT directly in server.mjs.
// This file is typechecked TypeScript, compiled to JavaScript and written as
// server.mjs by buildGatewayServerFile. Do NOT import from @sugarmagic/* packages.

import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, extname, join, relative } from "node:path";
import {
  createHash,
  createHmac,
  createPublicKey,
  timingSafeEqual,
  verify as cryptoVerify
} from "node:crypto";
// Load-bearing despite looking unused: treeShaking is disabled in
// compile-options.ts precisely so this import survives into the compiled
// bundle for the supabase-jwt auth gate that buildGatewayServerFile injects.
import { verifySupabaseJwt } from "./supabase-jwt";
import { isSecretSection, composeLoreBody } from "./lore-designation";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface Route {
  routeId: string;
  path: string;
  protocol: string;
  consumer: string;
}

interface RouteManifest {
  serviceUnitId: string;
  targetId: string;
  authMode?: string;
  containerPort?: number;
  label?: string;
  owners?: string[];
  routes: Route[];
}

interface LoreIngestState {
  active: boolean;
  phase: string;
  pageCount: number;
  chunkCount: number;
  uploadedCount: number;
  currentChunkId: string | null;
  message: string;
  warnings: string[];
  startedAt: string | null;
  completedAt: string | null;
}

interface LoreSection {
  heading: string;
  slug: string;
  content: string;
}

interface LorePage {
  pageId: string;
  title: string;
  relativePath: string;
  sectionCount: number;
  body: string;
  sections: LoreSection[];
}

interface LoreChunk {
  pageId: string;
  chunkId: string;
  title: string;
  sectionHeading: string;
  sectionSlug: string;
  relativePath: string;
  embeddingText: string;
}

interface LoreSource {
  sourceKind: string;
  sourcePath: string | null;
  repositoryUrl: string;
  repositoryRef: string;
  sourceReady: boolean;
  warning: string | null;
}

// ---------------------------------------------------------------------------
// Module-level state (set by initGateway; empty until called)
// ---------------------------------------------------------------------------

let _routes: Route[] = [];
let _serviceUnitId = "";
let _targetId = "";

const _loreIngestState: LoreIngestState = {
  active: false,
  phase: "idle",
  pageCount: 0,
  chunkCount: 0,
  uploadedCount: 0,
  currentChunkId: null,
  message: "Idle",
  warnings: [],
  startedAt: null,
  completedAt: null
};

// Story 46.9 — CORS allowed-origin patterns come from terraform via
// SUGARMAGIC_GATEWAY_ALLOWED_ORIGINS (comma-joined). Each entry is
// either an exact origin ("https://foo.com") or a single-'*'
// wildcard pattern ("https://*--site.netlify.app"). The gateway
// pattern-matches each request's Origin header at request time and
// only emits Access-Control-Allow-Origin when there's a hit. Empty
// list = no ACAO header emitted, blocking browsers.
let _allowedOriginPatterns: string[] = [];

export function initGateway(manifest: RouteManifest): void {
  _routes = manifest.routes ?? [];
  _serviceUnitId = manifest.serviceUnitId ?? "";
  _targetId = manifest.targetId ?? "";
  _allowedOriginPatterns = (
    process.env["SUGARMAGIC_GATEWAY_ALLOWED_ORIGINS"] ?? ""
  )
    .split(",")
    .map((entry) => entry.trim())
    .filter((entry) => entry.length > 0);
}

export function resetLoreIngestState(): void {
  Object.assign(_loreIngestState, {
    active: false,
    phase: "idle",
    pageCount: 0,
    chunkCount: 0,
    uploadedCount: 0,
    currentChunkId: null,
    message: "Idle",
    warnings: [],
    startedAt: null,
    completedAt: null
  });
}

// ---------------------------------------------------------------------------
// CORS helpers
// ---------------------------------------------------------------------------

export function resolveAllowedOrigin(origin: string | undefined): string | null {
  if (!origin) return null;
  for (const pattern of _allowedOriginPatterns) {
    if (pattern === origin) return origin;
    const wildcardIndex = pattern.indexOf("*");
    if (wildcardIndex >= 0) {
      const prefix = pattern.slice(0, wildcardIndex);
      const suffix = pattern.slice(wildcardIndex + 1);
      if (
        origin.length >= prefix.length + suffix.length &&
        origin.startsWith(prefix) &&
        origin.endsWith(suffix)
      ) {
        return origin;
      }
    }
  }
  return null;
}

const _baseHeaders = {
  "content-type": "application/json; charset=utf-8"
};

export function resolveCorsHeaders(req: IncomingMessage): Record<string, string> {
  const headers: Record<string, string> = { vary: "origin" };
  const origin = req?.headers?.origin;
  const echoOrigin = resolveAllowedOrigin(origin);
  if (echoOrigin) {
    headers["access-control-allow-origin"] = echoOrigin;
    headers["access-control-allow-credentials"] = "true";
  }
  return headers;
}

// Stash the per-request resolved CORS headers on the response so the
// many sendJson call sites stay one-arg and don't have to thread req
// through every helper. The top of createServer sets it once per req.
export function sendJson(res: ServerResponse & { __sugarmagicCors?: Record<string, string> }, statusCode: number, payload: unknown): void {
  res.writeHead(statusCode, {
    ..._baseHeaders,
    ...(res.__sugarmagicCors ?? {})
  });
  res.end(JSON.stringify(payload, null, 2));
}

export function logInfo(message: string, payload?: unknown): void {
  const suffix =
    payload && typeof payload === "object"
      ? " " + JSON.stringify(payload)
      : payload != null
        ? " " + String(payload)
        : "";
  console.log("[sugardeploy] " + message + suffix);
}

export function logError(message: string, error: unknown, payload?: Record<string, unknown>): void {
  const details = {
    ...(payload && typeof payload === "object" ? payload : {}),
    error: error instanceof Error ? error.message : String(error)
  };
  console.error("[sugardeploy] " + message + " " + JSON.stringify(details));
}

function updateLoreIngestState(patch: Partial<LoreIngestState>): void {
  Object.assign(_loreIngestState, patch);
}

export function sendMethodNotAllowed(res: ServerResponse & { __sugarmagicCors?: Record<string, string> }, allowed: string[]): void {
  res.writeHead(405, {
    ..._baseHeaders,
    ...(res.__sugarmagicCors ?? {}),
    allow: allowed.join(", ")
  });
  res.end(
    JSON.stringify(
      {
        ok: false,
        error: "MethodNotAllowed",
        allowed
      },
      null,
      2
    )
  );
}

export function normalizePath(url: string | undefined): string {
  return (url || "/").split("?")[0] || "/";
}

// Story 45.5.8 — bearer-token authorization. Constant-time compare via
// node:crypto.timingSafeEqual prevents timing-based token guessing. Length
// mismatch short-circuits with false (timingSafeEqual requires equal-length
// buffers). The expected token comes from the deployment secret env var
// resolved at request time; missing env var (e.g. secret wasn't Set Value'd
// after enabling bearer mode) means the gate denies everything except /health.
export function authorizeBearer(req: IncomingMessage): boolean {
  const expected = process.env["SUGARMAGIC_GATEWAY_SHARED_TOKEN"] || "";
  if (!expected) return false;
  const header = (req.headers && req.headers["authorization"]) || "";
  const prefix = "Bearer ";
  if (typeof header !== "string" || !header.startsWith(prefix)) return false;
  const presented = header.slice(prefix.length).trim();
  if (!presented) return false;
  const expectedBuf = Buffer.from(expected, "utf8");
  const presentedBuf = Buffer.from(presented, "utf8");
  if (expectedBuf.length !== presentedBuf.length) return false;
  try {
    return timingSafeEqual(expectedBuf, presentedBuf);
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------
// Utility helpers
// ---------------------------------------------------------------------------

function resolveEnv(name: string, fallback = ""): string {
  const value = process.env[name];
  return typeof value === "string" ? value.trim() || fallback : fallback;
}

function requireEnv(name: string): string {
  const value = resolveEnv(name);
  if (!value) {
    throw new Error("Missing required environment variable: " + name);
  }
  return value;
}

async function readJsonBody(req: IncomingMessage): Promise<Record<string, unknown>> {
  let requestBody = "";
  for await (const chunk of req) {
    requestBody += chunk.toString();
  }
  if (!requestBody.trim()) {
    return {};
  }
  try {
    return JSON.parse(requestBody) as Record<string, unknown>;
  } catch {
    throw new Error("Request body must be valid JSON.");
  }
}

async function parseApiJsonResponse(response: Response, label: string): Promise<unknown> {
  const raw = await response.text();
  let payload: unknown = null;
  if (raw.trim()) {
    try {
      payload = JSON.parse(raw);
    } catch {
      payload = raw;
    }
  }
  if (!response.ok) {
    throw new Error(
      label +
        " failed with status " +
        response.status +
        (raw.trim() ? ": " + raw : "")
    );
  }
  return payload;
}

async function requestJson(
  url: string,
  options: RequestInit,
  label: string
): Promise<{ payload: unknown; headers: Headers }> {
  logInfo("upstream:request", {
    label,
    url,
    method: options?.method ?? "GET"
  });
  const response = await fetch(url, options);
  const raw = await response.text();
  let payload: unknown = null;
  if (raw.trim()) {
    try {
      payload = JSON.parse(raw);
    } catch {
      payload = raw;
    }
  }
  if (!response.ok) {
    logError(label + " failed", new Error("upstream non-2xx"), {
      url,
      status: response.status,
      body: raw
    });
    throw new Error(
      label +
        " failed with status " +
        response.status +
        (typeof payload === "string"
          ? ": " + payload
          : payload && typeof payload === "object" && "error" in payload
            ? ": " + JSON.stringify(payload)
            : "")
    );
  }
  return {
    payload,
    headers: response.headers
  };
}

// ---------------------------------------------------------------------------
// Lore helpers
// ---------------------------------------------------------------------------

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "section";
}

function sanitizeFilename(value: string): string {
  return value.replace(/[^a-z0-9._-]+/gi, "-").replace(/-+/g, "-");
}

export function parseFrontmatter(raw: string): { metadata: Record<string, string>; body: string } {
  if (!raw.startsWith("---\n")) {
    return {
      metadata: {},
      body: raw
    };
  }

  const closingIndex = raw.indexOf("\n---\n", 4);
  if (closingIndex === -1) {
    return {
      metadata: {},
      body: raw
    };
  }

  const frontmatter = raw.slice(4, closingIndex);
  const body = raw.slice(closingIndex + 5);
  const metadata: Record<string, string> = {};
  for (const line of frontmatter.split("\n")) {
    const separatorIndex = line.indexOf(":");
    if (separatorIndex === -1) continue;
    const key = line.slice(0, separatorIndex).trim();
    const value = line.slice(separatorIndex + 1).trim();
    if (!key) continue;
    metadata[key] = value.replace(/^['"]|['"]$/g, "");
  }
  return {
    metadata,
    body
  };
}

export function splitLoreSections(markdown: string): LoreSection[] {
  const lines = markdown.split("\n");
  const sections: LoreSection[] = [];
  let current: { heading: string; slug: string; contentLines: string[] } = {
    heading: "Overview",
    slug: "overview",
    contentLines: []
  };

  for (const line of lines) {
    const headingMatch = /^(#{1,6})\s+(.+)$/.exec(line.trim());
    if (headingMatch) {
      const content = current.contentLines.join("\n").trim();
      if (content) {
        sections.push({
          heading: current.heading,
          slug: current.slug,
          content
        });
      }
      const heading = headingMatch[2]!.trim();
      current = {
        heading,
        slug: slugify(heading),
        contentLines: []
      };
      continue;
    }
    current.contentLines.push(line);
  }

  const trailingContent = current.contentLines.join("\n").trim();
  if (trailingContent) {
    sections.push({
      heading: current.heading,
      slug: current.slug,
      content: trailingContent
    });
  }

  return sections.length > 0
    ? sections
    : [
        {
          heading: "Overview",
          slug: "overview",
          content: markdown.trim()
        }
      ];
}

function walkMarkdownFiles(rootDir: string, currentDir = rootDir, files: string[] = []): string[] {
  for (const entry of readdirSync(currentDir, { withFileTypes: true })) {
    const absolutePath = join(currentDir, entry.name);
    if (entry.isDirectory()) {
      walkMarkdownFiles(rootDir, absolutePath, files);
      continue;
    }
    const extension = extname(entry.name).toLowerCase();
    if (extension === ".md" || extension === ".markdown") {
      files.push(absolutePath);
    }
  }
  return files;
}

function resolveLoreSource(): LoreSource {
  const sourceKind = resolveEnv("SUGARMAGIC_LORE_SOURCE_KIND", "local");
  const sourcePath = resolveEnv("SUGARMAGIC_LORE_SOURCE_PATH");
  const repositoryUrl = resolveEnv("SUGARMAGIC_LORE_SOURCE_REPOSITORY_URL");
  const repositoryRef = resolveEnv("SUGARMAGIC_LORE_SOURCE_REPOSITORY_REF", "main");

  if (sourceKind === "github") {
    return {
      sourceKind,
      sourcePath: null,
      repositoryUrl,
      repositoryRef,
      sourceReady: false,
      warning:
        "GitHub-backed lore source resolution is planned but not implemented yet. Use a local checked-out lore repo for now."
    };
  }

  if (!sourcePath) {
    return {
      sourceKind: "local",
      sourcePath: null,
      repositoryUrl,
      repositoryRef,
      sourceReady: false,
      warning: "SUGARMAGIC_LORE_SOURCE_PATH is not configured in the gateway environment."
    };
  }

  try {
    const stats = statSync(sourcePath);
    if (!stats.isDirectory()) {
      return {
        sourceKind: "local",
        sourcePath,
        repositoryUrl,
        repositoryRef,
        sourceReady: false,
        warning: "Configured lore source path is not a directory: " + sourcePath
      };
    }
  } catch (error) {
    return {
      sourceKind: "local",
      sourcePath,
      repositoryUrl,
      repositoryRef,
      sourceReady: false,
      warning:
        "Configured lore source path is not readable: " +
        sourcePath +
        " (" +
        (error instanceof Error ? error.message : String(error)) +
        ")"
    };
  }

  return {
    sourceKind: "local",
    sourcePath,
    repositoryUrl,
    repositoryRef,
    sourceReady: true,
    warning: null
  };
}

export function readLorePages(): { source: LoreSource; pages: LorePage[]; chunks: LoreChunk[]; warnings: string[] } {
  const source = resolveLoreSource();
  if (!source.sourceReady || !source.sourcePath) {
    return {
      source,
      pages: [],
      chunks: [],
      warnings: source.warning ? [source.warning] : []
    };
  }

  const warnings: string[] = source.warning ? [source.warning] : [];
  const pages: LorePage[] = [];
  const chunks: LoreChunk[] = [];
  const markdownFiles = walkMarkdownFiles(source.sourcePath);

  for (const absolutePath of markdownFiles) {
    const raw = readFileSync(absolutePath, "utf8");
    const { metadata, body } = parseFrontmatter(raw);
    const pageId = typeof metadata["id"] === "string" ? metadata["id"].trim() : "";
    if (!pageId) {
      warnings.push(
        "Skipped lore page without frontmatter id: " +
          relative(source.sourcePath, absolutePath)
      );
      continue;
    }

    const relativePath = relative(source.sourcePath, absolutePath);
    const title =
      (typeof metadata["title"] === "string" && metadata["title"].trim()) ||
      pageId.split(".").at(-1) ||
      pageId;
    const sections = splitLoreSections(body);

    pages.push({
      pageId,
      title,
      relativePath,
      sectionCount: sections.length,
      body,
      sections
    });

    for (const section of sections) {
      // Plan 072.1: `## Secrets` never enters the vector index. The section
      // stays in `pages[].sections` (072.2 strips it from lore/resolve); only
      // the ingest chunks exclude it here.
      if (isSecretSection(section)) continue;
      const chunkId = pageId + "#" + section.slug;
      const embeddingText = [
        "Page ID: " + pageId,
        "Title: " + title,
        "Section: " + section.heading,
        section.content
      ]
        .filter(Boolean)
        .join("\n\n");

      chunks.push({
        pageId,
        chunkId,
        title,
        sectionHeading: section.heading,
        sectionSlug: section.slug,
        relativePath,
        embeddingText
      });
    }
  }

  pages.sort((left, right) => left.pageId.localeCompare(right.pageId));
  chunks.sort((left, right) => left.chunkId.localeCompare(right.chunkId));

  return {
    source,
    pages,
    chunks,
    warnings
  };
}

// ---------------------------------------------------------------------------
// Vector store helpers
// ---------------------------------------------------------------------------

/**
 * Retry an async operation up to `maxAttempts` times on transient OpenAI
 * errors (5xx, 429). Exponential backoff: 1s, 2s between retries.
 */
async function withOpenAIRetry<T>(label: string, fn: () => Promise<T>, maxAttempts = 3): Promise<T> {
  let lastError: unknown;
  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    try {
      return await fn();
    } catch (error) {
      lastError = error;
      const isTransient =
        error instanceof Error && /status (?:429|50[234])/.test(error.message);
      if (!isTransient || attempt === maxAttempts - 1) throw error;
      const delayMs = 1000 * (attempt + 1);
      logInfo("upstream:retry", { label, attempt: attempt + 1, delayMs });
      await new Promise<void>((r) => setTimeout(r, delayMs));
    }
  }
  throw lastError;
}

async function listVectorStoreFiles(vectorStoreId: string): Promise<Record<string, unknown>[]> {
  const items: Record<string, unknown>[] = [];
  let after = "";

  while (true) {
    const query = after ? "?after=" + encodeURIComponent(after) : "";
    const { payload } = await requestJson(
      "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/files" + query,
      {
        method: "GET",
        headers: {
          authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
        }
      },
      "OpenAI vector store file list"
    );

    const batch = Array.isArray((payload as { data?: unknown })?.data)
      ? (payload as { data: Record<string, unknown>[] }).data
      : [];
    items.push(...batch);
    if (!(payload as { has_more?: boolean })?.has_more || batch.length === 0) {
      break;
    }
    after = typeof batch[batch.length - 1]?.["id"] === "string"
      ? batch[batch.length - 1]!["id"] as string
      : "";
    if (!after) break;
  }

  return items;
}

/**
 * Is this vector-store file something the lore ingest put there?
 *
 * Every real lore chunk is attached with `page_id` and friends
 * (`chunkAttributes`, applied by `attachChunkBatch`). The health probe
 * attaches with `{ file_id }`
 * and nothing else. Those are the only two things that attach to this store, so
 * a file carrying no `page_id` did not come from lore.
 *
 * Keyed on the ATTRIBUTE rather than the filename for the same reason the
 * relevance floor is not a filename filter: a name check answers "is this the
 * probe", and the question worth asking is "did this come from lore", which
 * also catches whatever gets uploaded by hand next.
 *
 * `attributes` is on the list response -- verified against openai-node's
 * `VectorStoreFile`, which declares
 * `attributes?: { [key: string]: string | number | boolean } | null`.
 */
export function isLoreVectorStoreFile(item: Record<string, unknown>): boolean {
  const attributes = item["attributes"];
  if (typeof attributes !== "object" || attributes === null) return false;
  const pageId = (attributes as Record<string, unknown>)["page_id"];
  return typeof pageId === "string" && pageId.length > 0;
}

/**
 * Removes files that did not come from the lore ingest.
 *
 * WHY THIS EXISTS. The probe used to leave its file behind whenever it failed
 * partway -- cleanup was the last step, so any early return orphaned it. That
 * is fixed, and a relevance floor was added so junk could not be retrieved.
 * Neither of those deletes what already leaked, and on 2026-08-05 four orphans
 * were still being handed to an NPC as the entire evidence block for a turn.
 *
 * Runs before the probe uploads its own file, so anything unattributed at that
 * moment is from a previous run and there is no "except mine" case to get
 * wrong.
 *
 * Returns what it removed rather than logging and swallowing: the count is the
 * only evidence the spill existed, and a sweep that silently finds nothing and
 * a sweep that silently fails look identical.
 */
async function sweepNonLoreVectorStoreFiles(
  vectorStoreId: string
): Promise<{ removed: string[]; failed: number }> {
  const files = await listVectorStoreFiles(vectorStoreId);
  const removed: string[] = [];
  let failed = 0;

  for (const item of files) {
    const id = item["id"];
    if (typeof id !== "string" || isLoreVectorStoreFile(item)) continue;
    try {
      await deleteVectorStoreFile(vectorStoreId, id);
      removed.push(id);
    } catch {
      // One failed delete must not abandon the rest, and must not fail the
      // caller: this is housekeeping attached to a health check.
      failed += 1;
    }
  }

  return { removed, failed };
}

async function deleteVectorStoreFile(vectorStoreId: string, vectorStoreFileId: string): Promise<void> {
  await requestJson(
    "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/files/" + vectorStoreFileId,
    {
      method: "DELETE",
      headers: {
        authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
      }
    },
    "OpenAI vector store file delete"
  );
}

/**
 * The most files one attach call may carry. The API maximum, verified against
 * openai-node's `FileBatchCreateParams` ("maximum of 2000 files").
 */
const MAX_FILES_PER_BATCH = 2000;

/**
 * How many chunk files upload at once.
 *
 * The uploads are independent, so this is only a politeness/rate-limit dial.
 * openai-node's own `uploadAndPoll` defaults to 5; 8 is a small step up that
 * still leaves headroom on a shared key.
 */
const UPLOAD_CONCURRENCY = 8;

/** How long one batch may take to index before the ingest calls it stuck. */
const BATCH_INDEX_DEADLINE_MS = 30 * 60 * 1000;
const BATCH_POLL_INTERVAL_MS = 2000;

/**
 * A fingerprint of the text that actually gets embedded.
 *
 * OVER `embeddingText` AND NOTHING ELSE. That is the exact string uploaded as
 * the file body (`uploadChunkFile`), so it is the only input whose change
 * should force a re-embed. Hashing the id, the filename or the attributes
 * instead would produce an ingest that looks incremental, finishes in seconds,
 * and serves stale lore forever -- worse than the full rebuild it replaces.
 */
export function chunkContentHash(chunk: LoreChunk): string {
  return createHash("sha256").update(chunk.embeddingText, "utf8").digest("hex");
}

/**
 * The attributes a chunk is attached with.
 *
 * `page_id` marks it as lore (`isLoreVectorStoreFile`). `chunk_id` is its
 * ADDRESS -- stable across an edit, so it keeps meaning "this section" -- and
 * `content_hash` is its VERSION. Address plus version, like a file path and the
 * hash of its contents: you do not rename a file because you edited it.
 *
 * Seven of an allowed sixteen keys, values well inside the 512-character limit
 * (openai-node `VectorStoreFile`).
 */
export function chunkAttributes(chunk: LoreChunk): Record<string, string> {
  return {
    page_id: chunk.pageId,
    chunk_id: chunk.chunkId,
    section_slug: chunk.sectionSlug,
    section_heading: chunk.sectionHeading,
    title: chunk.title,
    relative_path: chunk.relativePath,
    content_hash: chunkContentHash(chunk)
  };
}

/** One file sitting at a chunk address. */
interface IndexedChunk {
  fileId: string;
  contentHash: string;
  /** OpenAI's per-file indexing status. Only `completed` is retrievable. */
  status: string;
}

/**
 * Reads the store back as a manifest of what is already indexed.
 *
 * The store IS the manifest -- no separate state file to drift out of sync with
 * it. Only files carrying `page_id` are considered, so a probe leftover or
 * anything uploaded by hand is invisible here and is left to the sweep rather
 * than mistaken for a chunk.
 *
 * A LIST PER ADDRESS, not one file per address. Two files can share a
 * `chunk_id` -- a stale copy whose delete failed, a page with two identically
 * named headings -- and a Map that keeps only the last one seen makes the other
 * invisible to BOTH replacement and removal, so it stays retrievable forever.
 * Keeping every copy is what lets the plan converge on one.
 *
 * A file with no `content_hash` predates this and is reported with an empty
 * one, which never matches a real hash -- so it re-uploads once and then
 * settles. That is the whole migration: no version flag, no backfill.
 */
export function indexedChunksByAddress(
  files: Array<Record<string, unknown>>
): Map<string, IndexedChunk[]> {
  const byAddress = new Map<string, IndexedChunk[]>();
  for (const file of files) {
    if (!isLoreVectorStoreFile(file)) continue;
    const id = file["id"];
    const attributes = file["attributes"] as Record<string, unknown>;
    const chunkId = attributes["chunk_id"];
    if (typeof id !== "string" || typeof chunkId !== "string") continue;
    const hash = attributes["content_hash"];
    const status = file["status"];
    const entry: IndexedChunk = {
      fileId: id,
      contentHash: typeof hash === "string" ? hash : "",
      status: typeof status === "string" ? status : "unknown"
    };
    byAddress.set(chunkId, [...(byAddress.get(chunkId) ?? []), entry]);
  }
  return byAddress;
}

/**
 * What an incremental ingest has to do, given the source and what is indexed.
 *
 * Pure so the decision can be tested without a vector store: this is the part
 * that must not be wrong, because getting it wrong either re-uploads everything
 * (merely slow) or skips a changed chunk (silently stale).
 *
 * IT TRUSTS ONLY A COMPLETED FILE WHOSE HASH MATCHES. Attributes are set at
 * ATTACH time, before indexing succeeds or fails, so a chunk that failed to
 * index still carries a correct `chunk_id` and a matching `content_hash`.
 * Counting that as indexed means the section is unretrievable and every future
 * run reports "nothing to do" -- permanently stale, while the tool says it is
 * fine. Overwrite could never do that, so trusting the attributes alone would
 * be a regression on the behaviour this replaces.
 *
 * IT CONVERGES ON ONE FILE PER ADDRESS. Every copy beyond the one it keeps goes
 * on `remove`, so a failed cleanup heals on the next run instead of leaving two
 * versions of a section retrievable side by side.
 */
export function planIncrementalIngest(
  chunks: LoreChunk[],
  indexed: Map<string, IndexedChunk[]>
): {
  upload: LoreChunk[];
  unchanged: LoreChunk[];
  remove: string[];
  duplicateAddresses: string[];
} {
  const upload: LoreChunk[] = [];
  const unchanged: LoreChunk[] = [];
  const remove: string[] = [];
  const duplicateAddresses: string[] = [];
  const seen = new Set<string>();

  for (const chunk of chunks) {
    // Two SOURCE chunks at one address: `chunkId` is pageId + section slug and
    // slugify does not de-duplicate, so two identically named headings on a
    // page collide. Reported rather than resolved -- silently keeping one would
    // drop a section the author wrote, and each run would fight the last.
    if (seen.has(chunk.chunkId)) {
      duplicateAddresses.push(chunk.chunkId);
      continue;
    }
    seen.add(chunk.chunkId);

    const entries = indexed.get(chunk.chunkId) ?? [];
    const hash = chunkContentHash(chunk);
    const usable = entries.filter(
      (entry) => entry.status === "completed" && entry.contentHash === hash
    );

    if (usable.length > 0) {
      unchanged.push(chunk);
      // Keep one, drop every other copy at this address.
      const keep = usable[0]!.fileId;
      for (const entry of entries) {
        if (entry.fileId !== keep) remove.push(entry.fileId);
      }
    } else {
      // New, edited, or previously failed. Every copy currently there is stale.
      upload.push(chunk);
      for (const entry of entries) remove.push(entry.fileId);
    }
  }

  // Indexed under an address the source no longer has: the page or section was
  // deleted, or a heading was renamed. Only lore files reach this map, so
  // nothing else can be caught by it.
  for (const [chunkId, entries] of indexed) {
    if (seen.has(chunkId)) continue;
    for (const entry of entries) remove.push(entry.fileId);
  }

  return { upload, unchanged, remove, duplicateAddresses };
}

/**
 * Uploads one chunk's text and returns its file id. Does NOT attach it.
 *
 * Attaching is what the batch does, and separating the two is the whole point:
 * uploads are independent and can run concurrently, while attaching is one call
 * for up to 2000 files.
 */
async function uploadChunkFile(chunk: LoreChunk): Promise<string> {
  const fileUpload = new FormData();
  fileUpload.append("purpose", "user_data");
  fileUpload.append(
    "file",
    new Blob([chunk.embeddingText], { type: "text/markdown" }),
    sanitizeFilename(chunk.chunkId) + ".md"
  );

  const uploadResponse = await fetch("https://api.openai.com/v1/files", {
    method: "POST",
    headers: {
      authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
    },
    body: fileUpload
  });
  const payload = await parseApiJsonResponse(
    uploadResponse,
    "OpenAI file upload"
  ) as Record<string, unknown>;
  const fileId = payload["id"];
  if (typeof fileId !== "string") {
    throw new Error("OpenAI file upload returned no id for chunk " + chunk.chunkId);
  }
  return fileId;
}

/**
 * Runs `worker` over `items`, at most `limit` at a time, preserving order.
 *
 * Deliberately not Promise.all over everything: 7,500 simultaneous uploads is a
 * different way to fail than 7,500 sequential ones, not a better one.
 */
export async function mapWithConcurrency<TIn, TOut>(
  items: TIn[],
  limit: number,
  worker: (item: TIn, index: number) => Promise<TOut>
): Promise<TOut[]> {
  const results = new Array<TOut>(items.length);
  let next = 0;
  // ONE FAILURE STOPS THE REST. `Promise.all` rejects on the first throw, but
  // the other runners are still looping -- they keep working, and keep writing
  // progress, so they overwrite the "failed" state the caller just set with
  // cheerful "uploaded N / M" messages. The run reads as still going after it
  // has already lost.
  let aborted = false;

  async function runner(): Promise<void> {
    while (!aborted) {
      const index = next;
      next += 1;
      if (index >= items.length) return;
      try {
        results[index] = await worker(items[index]!, index);
      } catch (error) {
        aborted = true;
        throw error;
      }
    }
  }

  await Promise.all(
    Array.from({ length: Math.max(1, Math.min(limit, items.length)) }, runner)
  );
  return results;
}

/**
 * Attaches up to `MAX_FILES_PER_BATCH` already-uploaded files in one call and
 * waits for the batch to finish indexing.
 *
 * WHY A BATCH RATHER THAN A FILE AT A TIME. The previous shape uploaded,
 * attached and then polled EACH chunk to completion before starting the next,
 * so a 98-chunk ingest cost 98 index waits and took about a quarter of an hour.
 * The wait is now once per batch instead of once per file.
 *
 * The per-chunk poll also had a fixed 30-attempt / 1s deadline, which is what
 * killed a real ingest at 19/98: one chunk indexed slowly and took the whole
 * run with it. A batch has its own status, so no single file gets a private
 * deadline, and the deadline here is sized for a batch rather than for one
 * small file.
 *
 * `files` rather than `file_ids` because the entries carry per-file
 * `attributes` -- `page_id` is what marks a file as lore, both for retrieval
 * and for `isLoreVectorStoreFile`. The two parameters are mutually exclusive,
 * so this is the only form that keeps the metadata.
 */
export async function attachChunkBatch(
  vectorStoreId: string,
  entries: Array<{ fileId: string; chunk: LoreChunk }>,
  onProgress: ((indexed: number, total: number) => void) | null = null
): Promise<number> {
  // Only the CREATE is retried. Retrying the whole function would re-attach
  // files that are already attached and leave a second batch running over them.
  const batchId = await withOpenAIRetry("attach-batch-create", async () => {
    const createResponse = await fetch(
      "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/file_batches",
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
        },
        body: JSON.stringify({
          files: entries.map((entry) => ({
            file_id: entry.fileId,
            attributes: chunkAttributes(entry.chunk)
          }))
        })
      }
    );
    const batch = await parseApiJsonResponse(
      createResponse,
      "OpenAI vector store file batch create"
    ) as Record<string, unknown>;
    const id = batch["id"];
    if (typeof id !== "string") {
      throw new Error("OpenAI file batch create returned no id.");
    }
    return id;
  });

  const deadline = Date.now() + BATCH_INDEX_DEADLINE_MS;
  while (Date.now() < deadline) {
    let payload: Record<string, unknown>;
    try {
      const statusResponse = await fetch(
        "https://api.openai.com/v1/vector_stores/" +
          vectorStoreId +
          "/file_batches/" +
          batchId,
        {
          method: "GET",
          headers: {
            authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
          }
        }
      );
      payload = await parseApiJsonResponse(
        statusResponse,
        "OpenAI vector store file batch status"
      ) as Record<string, unknown>;
    } catch (error) {
      // A failed STATUS read says nothing about the batch, which is still
      // indexing server-side. Poll again rather than abandon it -- the deadline
      // below is what bounds this, not the first transient 503.
      logInfo("ingest:batch-status-retry", {
        batchId,
        reason: error instanceof Error ? error.message : String(error)
      });
      await new Promise((resolve) => setTimeout(resolve, BATCH_POLL_INTERVAL_MS));
      continue;
    }

    const counts = (payload["file_counts"] ?? {}) as Record<string, unknown>;
    const completed = typeof counts["completed"] === "number" ? counts["completed"] : 0;
    const failed = typeof counts["failed"] === "number" ? counts["failed"] : 0;
    onProgress?.(completed, entries.length);

    const status = payload["status"];
    if (status === "completed" || status === "failed" || status === "cancelled") {
      // A BATCH IS "completed" WHEN EVERY FILE IS PROCESSED, NOT WHEN EVERY
      // FILE SUCCEEDED. openai-node's own poll helper says so: "this will
      // return even if one of the files failed to process, you need to check
      // batch.file_counts.failed_count to handle this case."
      //
      // So the count is the verdict, not the status. Treating `completed` as
      // success is how an ingest reports 98/98 while silently missing chunks
      // that no NPC will ever retrieve -- and the failed files keep their
      // page_id, so the sweep will not surface them either.
      //
      // Loud rather than degraded: this is an authoring pass, and a half-built
      // store that claims to be whole is the failure worth refusing.
      if (status !== "completed" || failed > 0) {
        throw new Error(
          "Vector store file batch " +
            String(status) +
            ": " + completed + " indexed, " + failed + " failed of " +
            entries.length + " files."
        );
      }
      return completed;
    }
    await new Promise((resolve) => setTimeout(resolve, BATCH_POLL_INTERVAL_MS));
  }

  throw new Error(
    "Timed out waiting for vector store batch indexing after " +
      Math.round(BATCH_INDEX_DEADLINE_MS / 60000) +
      " minutes."
  );
}

function findManagedRoute(path: string): Route | undefined {
  return _routes.find(
    (route) => path === route.path || path.startsWith(route.path + "/")
  );
}

// ---------------------------------------------------------------------------
// Request handlers
// ---------------------------------------------------------------------------

export async function handleSugarAgentGenerate(
  req: IncomingMessage,
  res: ServerResponse & { __sugarmagicCors?: Record<string, string> }
): Promise<void> {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }

  const body = await readJsonBody(req);
  // Plan 073.2 — model selection stays SERVER-SIDE. The browser sends a
  // `purpose` category, never a model id, so model choice is a deploy-time env
  // decision the player can't see or tamper with. An explicit `body.model` is
  // still honored for back-compat / tooling, but the runtime no longer sends one.
  //
  // This route is a GENERIC Claude proxy, not a sugaragent-private one:
  // sugarlang posts here too. Each purpose therefore resolves from the env var
  // owned by the PLUGIN that makes the call, declared in that plugin's own
  // `gatewayRuntimeConfigKeys` — which is why "teacher" reads a
  // SUGARMAGIC_SUGARLANG_* name while the sugaragent purposes read
  // SUGARMAGIC_SUGARAGENT_*. Adding a purpose here means adding it there too,
  // or it silently falls through to the dialogue model.
  const purpose =
    typeof body["purpose"] === "string" ? body["purpose"].trim() : "";
  const dialogueModel = (): string =>
    resolveEnv("SUGARMAGIC_SUGARAGENT_ANTHROPIC_MODEL", "claude-haiku-4-5");
  // Table, not a ternary chain — a fourth purpose made the nesting unreadable.
  // Each entry is (env var, fallback). Unknown purpose => dialogue.
  const PURPOSE_MODELS: Record<string, () => string> = {
    // sugaragent: the cheap end-of-conversation memory pass.
    summary: () => resolveEnv("SUGARMAGIC_SUGARAGENT_SUMMARY_MODEL", "claude-haiku-4-5"),
    // sugaragent: regenerating a reply that failed the judge.
    regen: () => resolveEnv("SUGARMAGIC_SUGARAGENT_REGEN_MODEL", dialogueModel()),
    // sugarlang: the Teacher's pedagogical judgment call. Deliberately its own
    // env var — this is the most reasoning-heavy call in the product and must
    // not silently ride the cheap dialogue model (which it did until 2026-07-28).
    teacher: () => resolveEnv("SUGARMAGIC_SUGARLANG_TEACHER_MODEL", "claude-sonnet-4-6"),
    // sugarlang: COMPILE-time extraction over authored content — multi-word
    // expressions, line intent, and scene concepts. Authoring-time and cached
    // by content hash, so it is paid once per content change rather than per
    // turn; that budget buys a stronger model than the dialogue default.
    extraction: () =>
      resolveEnv("SUGARMAGIC_SUGARLANG_EXTRACTION_MODEL", "claude-sonnet-4-6")
  };
  const model = (PURPOSE_MODELS[purpose] ?? dialogueModel)();
  // The ground-truth record of which model each call used — grep it in
  // `docker compose logs` to verify a model config change actually landed.
  logInfo("sugaragent.generate", { purpose: purpose || "dialogue", model });
  const systemPrompt =
    typeof body["systemPrompt"] === "string" ? body["systemPrompt"].trim() : "";
  const userPrompt =
    typeof body["userPrompt"] === "string" ? body["userPrompt"].trim() : "";
  const maxTokens =
    typeof body["maxTokens"] === "number" && Number.isFinite(body["maxTokens"])
      ? Math.max(1, Math.floor(body["maxTokens"]))
      : 300;

  // Plan 072.5 — structured system blocks with a cache breakpoint. When
  // `systemBlocks` is present, the gateway maps it to Anthropic `system`
  // content blocks and marks `cache: true` blocks with cache_control:ephemeral
  // (prompt caching is GA; no beta header). When absent it falls back to the
  // legacy `systemPrompt` string. The sugarlang TEACHER moved to cached
  // systemBlocks in 222.9 (confirmed in production: cacheRead=2778 on warm
  // calls); verify/scripted/chunk still send the legacy string, uncached.
  const rawSystemBlocks = Array.isArray(body["systemBlocks"])
    ? (body["systemBlocks"] as unknown[])
    : null;
  const systemBlocks = rawSystemBlocks
    ? rawSystemBlocks
        .filter(
          (entry): entry is { text: string; cache?: boolean } =>
            !!entry &&
            typeof entry === "object" &&
            typeof (entry as { text?: unknown }).text === "string" &&
            (entry as { text: string }).text.trim().length > 0
        )
        .map((entry) => ({
          text: entry.text.trim(),
          cache: (entry as { cache?: unknown }).cache === true
        }))
    : null;
  const hasSystemBlocks = !!systemBlocks && systemBlocks.length > 0;

  if ((!systemPrompt && !hasSystemBlocks) || !userPrompt) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidRequest",
      message:
        "userPrompt and one of systemPrompt or systemBlocks are required."
    });
    return;
  }

  // Plan 075.4 -- blocklist defense-in-depth: applied against the composed
  // user prompt. Tradeoff (documented): a blocklisted term in world evidence
  // can false-positive here; acceptable for the curl-direct threat it covers.
  {
    const blocklistRaw = resolveEnv("SUGARMAGIC_SUGARAGENT_BLOCKLIST", "");
    if (blocklistRaw) {
      const blockTerms = blocklistRaw.split(",").map((t) => t.trim().toLowerCase()).filter(Boolean);
      const loweredPrompt = userPrompt.toLowerCase();
      const blockHit = blockTerms.find((t) => loweredPrompt.includes(t));
      if (blockHit) {
        logInfo("sugaragent.generate-blocklist-hit", { term: blockHit });
        sendJson(res, 200, {
          text: "I'm not sure I can help with that right now.",
          requestId: null,
          usage: { inputTokens: 0, outputTokens: 0, cacheReadInputTokens: 0, cacheCreationInputTokens: 0 },
          model: "deterministic"
        });
        return;
      }
    }
  }

  const anthropicSystem = hasSystemBlocks
    ? systemBlocks!.map((block) => ({
        type: "text",
        text: block.text,
        ...(block.cache ? { cache_control: { type: "ephemeral" } } : {})
      }))
    : systemPrompt;

  const { payload, headers } = await requestJson(
    "https://api.anthropic.com/v1/messages",
    {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": requireEnv("SUGARMAGIC_ANTHROPIC_API_KEY"),
        "anthropic-version": "2023-06-01"
      },
      body: JSON.stringify({
        model,
        max_tokens: maxTokens,
        system: anthropicSystem,
        messages: [
          {
            role: "user",
            content: userPrompt
          }
        ]
      })
    },
    "Anthropic request"
  );

  const text = Array.isArray((payload as { content?: unknown[] })?.content)
    ? (payload as { content: Array<{ type: string; text?: string }> }).content
        .filter((block) => block?.type === "text" && typeof block.text === "string")
        .map((block) => block.text!.trim())
        .filter(Boolean)
        .join("\n\n")
    : "";

  if (!text) {
    throw new Error("Anthropic response did not include text content.");
  }

  // Plan 072.5 — pass usage through (incl. cache read/create) so the browser
  // and 072.7 diagnostics can observe cache behavior. Coerce to numbers.
  const rawUsage = (payload as { usage?: Record<string, unknown> }).usage ?? {};
  const usageNumber = (key: string): number => {
    const value = rawUsage[key];
    return typeof value === "number" && Number.isFinite(value) ? value : 0;
  };

  // Plan 072.7 (mini-review) — report the model Anthropic actually served
  // (its response `model`), not just the requested alias/tier; fall back to
  // the requested id when the response omits it.
  const servedModel =
    typeof (payload as { model?: unknown }).model === "string" &&
    (payload as { model: string }).model.trim().length > 0
      ? (payload as { model: string }).model
      : model;

  sendJson(res, 200, {
    text,
    requestId: headers.get("request-id"),
    usage: {
      inputTokens: usageNumber("input_tokens"),
      outputTokens: usageNumber("output_tokens"),
      cacheReadInputTokens: usageNumber("cache_read_input_tokens"),
      cacheCreationInputTokens: usageNumber("cache_creation_input_tokens")
    },
    model: servedModel
  });
}

// ---------------------------------------------------------------------------
// Plan 075.1 -- /api/sugaragent/generate/judge
// A dedicated route so the structured verdict lands in server-side logs
// (Cloud Run queryable) and never round-trips through the browser unlogged.
// Vendor base URL is env-overridable (SUGARMAGIC_SUGARAGENT_JUDGE_BASE_URL)
// so outage behavior is testable locally.
// ---------------------------------------------------------------------------

/**
 * Plan 084.2 -- pure helper, exported for testability.
 * Builds the judge user prompt. When externalDirectives are present, a
 * directive block is spliced after the persona summary; rubric 1 gains a
 * guard sentence; the block closes with a SAFETY-override prohibition so a
 * directive can never soften rubric 3.
 */
export function buildJudgeUserPrompt(
  worldPremise: string,
  personaDigest: string,
  responseIntent: string,
  worldContext: string | null,
  loreContextLines: string,
  replyText: string,
  externalDirectives: string[]
): string {
  const directivesBlock =
    externalDirectives.length > 0
      ? `Established directives from game systems (in-world by definition; behavior they direct is never an IN-CHARACTER violation):\n` +
        externalDirectives.map((d, i) => `${i + 1}. ${d}`).join("\n") + "\n" +
        `Directives never override the SAFETY rule.\n\n`
      : "";

  const inCharacterGuard =
    externalDirectives.length > 0
      ? " Behavior directed by an established directive above is never an IN-CHARACTER violation."
      : "";

  return (
    (worldPremise ? `World premise:\n${worldPremise}\n\n` : "") +
    `NPC persona summary (this is the NPC's established identity — treat all facts here as in-world):\n${personaDigest || "(none)"}\n\n` +
    directivesBlock +
    `Response intent: ${responseIntent}\n\n` +
    (worldContext ? `World context right now:\n${worldContext}\n\n` : "") +
    (loreContextLines ? `Lore context available to this NPC:\n${loreContextLines}\n\n` : "") +
    `NPC reply to score:\n"${replyText}"\n\n` +
    `Rubric (each must PASS for overall pass):\n` +
    `1. IN-CHARACTER: The reply matches the NPC persona voice, temperament, and knowledge level.${inCharacterGuard}\n` +
    `2. WORLD-GROUNDED: The reply does not introduce facts incompatible with the world premise or the NPC persona. Facts stated in either are established and must not be flagged as violations.\n` +
    `3. SAFETY: No out-of-character references to the real world, game mechanics, AI/developer, or secrets.\n\n` +
    `Use the score_reply tool.`
  );
}

export async function handleSugarAgentJudge(
  req: IncomingMessage,
  res: ServerResponse & { __sugarmagicCors?: Record<string, string> }
): Promise<void> {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }

  const body = await readJsonBody(req);
  const replyText =
    typeof body["replyText"] === "string" ? body["replyText"].trim() : "";
  const personaDigest =
    typeof body["personaDigest"] === "string" ? body["personaDigest"].trim() : "";
  const responseIntent =
    typeof body["responseIntent"] === "string" ? body["responseIntent"].trim() : "chat";
  const worldContext =
    typeof body["worldContext"] === "string" ? body["worldContext"].trim() : null;
  const rawLoreContext = Array.isArray(body["loreContextSummary"])
    ? (body["loreContextSummary"] as unknown[]).filter((e): e is string => typeof e === "string")
    : [];
  const worldPremise =
    typeof body["worldPremise"] === "string" ? body["worldPremise"].trim() : "";
  const externalDirectives = Array.isArray(body["externalDirectives"])
    ? (body["externalDirectives"] as unknown[]).filter((e): e is string => typeof e === "string")
    : [];

  if (!replyText) {
    sendJson(res, 400, { ok: false, error: "InvalidRequest", message: "replyText is required." });
    return;
  }

  const model = resolveEnv("SUGARMAGIC_SUGARAGENT_JUDGE_MODEL", "claude-haiku-4-5");
  const baseUrl = resolveEnv("SUGARMAGIC_SUGARAGENT_JUDGE_BASE_URL", "https://api.anthropic.com");

  const loreContextLines = rawLoreContext
    .map((e, i) => `[${i + 1}] ${e.slice(0, 300)}`)
    .join("\n");

  const judgeUserPrompt = buildJudgeUserPrompt(
    worldPremise,
    personaDigest,
    responseIntent,
    worldContext,
    loreContextLines,
    replyText,
    externalDirectives
  );

  const judgeSystemPrompt =
    "You are a quality reviewer for NPC dialogue in a cozy fantasy RPG. " +
    "Score the NPC reply strictly against the rubric. " +
    "The world premise and NPC persona define what is real in this world — any fact stated there is in-world by definition and must never be flagged as a violation. " +
    "Flag any violation that a player would notice as immersion-breaking or unsafe. " +
    "Be strict on SAFETY; be reasonable on IN-CHARACTER (minor voice slips are ok if the content is sound).";

  const tool = {
    name: "score_reply",
    description: "Record the verdict for an NPC reply against the rubric.",
    input_schema: {
      type: "object",
      properties: {
        passed: {
          type: "boolean",
          description: "true only when ALL rubric dimensions pass"
        },
        violations: {
          type: "array",
          items: { type: "string" },
          description: "List of failed dimension labels, e.g. [\"IN-CHARACTER\", \"SAFETY\"]. Empty when passed."
        },
        repairHint: {
          type: ["string", "null"],
          description: "One-line instruction for how to fix the reply, or null when passed."
        }
      },
      required: ["passed", "violations", "repairHint"]
    }
  };

  const startedAt = Date.now();
  const { payload } = await requestJson(
    baseUrl.replace(/\/+$/, "") + "/v1/messages",
    {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": requireEnv("SUGARMAGIC_ANTHROPIC_API_KEY"),
        "anthropic-version": "2023-06-01"
      },
      body: JSON.stringify({
        model,
        max_tokens: 512,
        system: judgeSystemPrompt,
        tools: [tool],
        tool_choice: { type: "tool", name: "score_reply" },
        messages: [{ role: "user", content: judgeUserPrompt }]
      })
    },
    "Anthropic judge request"
  );

  const toolUseBlock = Array.isArray((payload as { content?: unknown[] })?.content)
    ? (payload as { content: Array<{ type: string; name?: string; input?: unknown }> })
        .content.find((block) => block?.type === "tool_use" && block.name === "score_reply")
    : null;

  if (!toolUseBlock || typeof toolUseBlock.input !== "object" || !toolUseBlock.input) {
    throw new Error("Judge response did not include a score_reply tool call.");
  }

  const input = toolUseBlock.input as Record<string, unknown>;
  const passed = input["passed"] === true;
  const violations = Array.isArray(input["violations"])
    ? (input["violations"] as unknown[]).filter((v): v is string => typeof v === "string")
    : [];
  const repairHint =
    typeof input["repairHint"] === "string" ? input["repairHint"].trim() || null : null;

  logInfo("sugaragent.judge", {
    passed,
    violations,
    repairHint,
    model,
    durationMs: Date.now() - startedAt,
    responseIntent
  });

  sendJson(res, 200, { passed, violations, repairHint });
}

// ---------------------------------------------------------------------------
// Plan 075.3 -- /api/sugaragent/generate/moderate
// Wraps the moderation vendor (OpenAI by default; vendor base URL
// env-overridable via SUGARMAGIC_MODERATION_BASE_URL). Fail-open on errors:
// the conversation continues, the error is logged loudly.
// ---------------------------------------------------------------------------

export async function handleSugarAgentModerate(
  req: IncomingMessage,
  res: ServerResponse & { __sugarmagicCors?: Record<string, string> }
): Promise<void> {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }

  const body = await readJsonBody(req);
  const text =
    typeof body["text"] === "string" ? body["text"].trim() : "";

  if (!text) {
    sendJson(res, 400, { ok: false, error: "InvalidRequest", message: "text is required." });
    return;
  }

  // Plan 075.4 -- blocklist pre-check (cheapest layer first).
  const blocklist = resolveEnv("SUGARMAGIC_SUGARAGENT_BLOCKLIST", "");
  if (blocklist) {
    const terms = blocklist.split(",").map((t) => t.trim().toLowerCase()).filter(Boolean);
    const lowered = text.toLowerCase();
    const hitTerm = terms.find((t) => lowered.includes(t));
    if (hitTerm) {
      logInfo("sugaragent.blocklist-hit", { term: hitTerm });
      sendJson(res, 200, { flagged: true, categories: ["blocklist"], blocklisted: true });
      return;
    }
  }

  const moderationBaseUrl = resolveEnv(
    "SUGARMAGIC_MODERATION_BASE_URL",
    "https://api.openai.com"
  );

  try {
    const startedAt = Date.now();
    const { payload } = await requestJson(
      moderationBaseUrl.replace(/\/+$/, "") + "/v1/moderations",
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
        },
        body: JSON.stringify({ input: text })
      },
      "OpenAI moderation request"
    );

    const result = payload as {
      results?: Array<{
        flagged: boolean;
        categories: Record<string, boolean>;
      }>;
    };

    const topResult = result?.results?.[0];
    const flagged = topResult?.flagged === true;
    const categories = flagged && topResult?.categories
      ? Object.entries(topResult.categories)
          .filter(([, v]) => v === true)
          .map(([k]) => k)
      : [];

    if (flagged) {
      logInfo("sugaragent.moderation-flagged", { categories, durationMs: Date.now() - startedAt });
    }

    sendJson(res, 200, { flagged, categories, blocklisted: false });
  } catch (error) {
    logError("sugaragent.moderation-error", error, {
      text: text.slice(0, 40)
    });
    // Fail-open: don't gate the conversation on a moderation outage.
    sendJson(res, 200, { flagged: false, categories: [], blocklisted: false, error: "moderation-unavailable" });
  }
}

export async function handleSugarAgentSearch(
  req: IncomingMessage,
  res: ServerResponse & { __sugarmagicCors?: Record<string, string> }
): Promise<void> {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }

  const body = await readJsonBody(req);
  const query = typeof body["query"] === "string" ? body["query"].trim() : "";
  const vectorStoreId =
    typeof body["vectorStoreId"] === "string" && body["vectorStoreId"].trim()
      ? body["vectorStoreId"].trim()
      : resolveEnv("SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID");
  const maxResults =
    typeof body["maxResults"] === "number" && Number.isFinite(body["maxResults"])
      ? Math.max(1, Math.min(8, Math.floor(body["maxResults"])))
      : 4;

  // RELEVANCE FLOOR. Search used to return `max_num_results` regardless of how
  // well anything matched, so a query with one good hit came back with one good
  // hit and three pieces of whatever else was in the store -- which is how
  // orphaned "smprobe_*" test files ended up handed to an NPC as world context.
  //
  // This is the principled fix rather than filtering by filename: junk got in
  // because nothing asked whether a result was RELEVANT, and a name-based guard
  // would leave the same hole open for the next irrelevant document.
  //
  // `ranking_options.score_threshold` is an OpenAI vector-store search parameter
  // (verified against openai-node's VectorStoreSearchParams.RankingOptions).
  // Callers may override; 0.3 is deliberately low -- the goal is excluding
  // near-zero noise, not second-guessing the ranker.
  const scoreThreshold =
    typeof body["scoreThreshold"] === "number" && Number.isFinite(body["scoreThreshold"])
      ? Math.max(0, Math.min(1, body["scoreThreshold"]))
      : 0.3;

  if (!query || !vectorStoreId) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidRequest",
      message: "query and vectorStoreId are required."
    });
    return;
  }

  const { payload, headers } = await requestJson(
    "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/search",
    {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
      },
      body: JSON.stringify({
        query,
        max_num_results: maxResults,
        ranking_options: { score_threshold: scoreThreshold },
        filters:
          body["filters"] && typeof body["filters"] === "object" && !Array.isArray(body["filters"])
            ? body["filters"]
            : undefined
      })
    },
    "OpenAI vector search"
  );

  const results = Array.isArray((payload as { data?: unknown[] })?.data)
    ? (payload as { data: Array<Record<string, unknown>> }).data.map((result, index) => ({
        fileId:
          typeof result?.["file_id"] === "string" ? result["file_id"] : "vector-result-" + index,
        filename: typeof result?.["filename"] === "string" ? result["filename"] : "unknown",
        score: typeof result?.["score"] === "number" ? result["score"] : 0,
        attributes:
          result?.["attributes"] && typeof result["attributes"] === "object"
            ? result["attributes"]
            : {},
        text: Array.isArray(result?.["content"])
          ? (result["content"] as Array<{ type: string; text?: string }>)
              .filter((item) => item?.type === "text" && typeof item.text === "string")
              .map((item) => item.text!.trim())
              .filter(Boolean)
              .join("\n\n")
          : ""
      }))
    : [];

  sendJson(res, 200, {
    results,
    requestId: headers.get("x-request-id")
  });
}

export async function handleSugarAgentLoreStatus(
  req: IncomingMessage,
  res: ServerResponse & { __sugarmagicCors?: Record<string, string> }
): Promise<void> {
  if (req.method !== "GET") {
    sendMethodNotAllowed(res, ["GET", "OPTIONS"]);
    return;
  }

  const lore = readLorePages();
  const vectorStoreId = resolveEnv("SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID") || null;

  // WHAT IS ACTUALLY INDEXED, which is a different question from what is on
  // disk. `pageCount` and `chunkCount` describe the SOURCE; retrieval reads the
  // STORE, and the two drift -- a failed ingest, a partial upload, or a probe
  // that orphaned its file. Nothing reported the store at all, so the drift was
  // invisible until an NPC was handed four test files as world context.
  //
  // `null` rather than 0 when it cannot be read. "No lore is indexed" and "we
  // could not ask" are different facts, and only one of them means re-ingest.
  let store: {
    fileCount: number;
    loreFileCount: number;
    nonLoreFileCount: number;
  } | null = null;
  if (vectorStoreId) {
    try {
      const files = await listVectorStoreFiles(vectorStoreId);
      const loreFiles = files.filter(isLoreVectorStoreFile);
      store = {
        fileCount: files.length,
        loreFileCount: loreFiles.length,
        nonLoreFileCount: files.length - loreFiles.length
      };
    } catch {
      // Status must answer even when OpenAI does not.
    }
  }

  sendJson(res, 200, {
    ok: true,
    sourceKind: lore.source.sourceKind,
    sourceReady: lore.source.sourceReady,
    sourcePath: lore.source.sourcePath,
    vectorStoreId,
    pageCount: lore.pages.length,
    chunkCount: lore.chunks.length,
    store,
    warnings: lore.warnings,
    ingest: { ..._loreIngestState }
  });
}

export async function handleSugarAgentLorePages(
  req: IncomingMessage,
  res: ServerResponse & { __sugarmagicCors?: Record<string, string> }
): Promise<void> {
  if (req.method !== "GET") {
    sendMethodNotAllowed(res, ["GET", "OPTIONS"]);
    return;
  }

  const lore = readLorePages();
  sendJson(res, 200, {
    ok: true,
    pages: lore.pages.map((page) => ({
      pageId: page.pageId,
      title: page.title,
      relativePath: page.relativePath,
      sectionCount: page.sectionCount
    })),
    warnings: lore.warnings
  });
}

export async function handleSugarAgentLoreResolve(
  req: IncomingMessage,
  res: ServerResponse & { __sugarmagicCors?: Record<string, string> }
): Promise<void> {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }

  const body = await readJsonBody(req);
  const rawPageIds = Array.isArray(body?.["pageIds"]) ? body["pageIds"] as unknown[] : [];
  const pageIds = [...new Set(
    rawPageIds
      .filter((value) => typeof value === "string")
      .map((value) => (value as string).trim())
      .filter(Boolean)
  )].sort((left, right) => left.localeCompare(right));

  if (pageIds.length === 0) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidRequest",
      message: "pageIds must contain at least one non-empty lore page id."
    });
    return;
  }

  const lore = readLorePages();
  const pagesById = new Map(
    lore.pages.map((page) => [page.pageId, page])
  );
  const resolvedPages: LorePage[] = [];
  const missingPageIds: string[] = [];

  for (const pageId of pageIds) {
    const page = pagesById.get(pageId);
    if (!page) {
      missingPageIds.push(pageId);
      continue;
    }
    // Plan 072.2: `## Secrets` must not leave the gateway. Strip it from BOTH
    // `sections` and `body` (sugarlang's consumer feeds each into the scene
    // lexicon). Pages without a secret section pass through byte-identical --
    // only recompute `body` when a secret is actually being removed, so the
    // raw markdown is preserved for the common case.
    //
    // DEFERRED (Plan 072, revisit epic C/D): quest-stage-scoped knowledge
    // gating. This exclusion point is the natural gate -- when quest state +
    // memory feed the card fetch, filter sections by story stage here (an NPC
    // knows different things at different points). `## Secrets` is the static
    // precursor of that dynamic gate.
    const hasSecret = page.sections.some(isSecretSection);
    if (!hasSecret) {
      resolvedPages.push({
        pageId: page.pageId,
        title: page.title,
        relativePath: page.relativePath,
        sectionCount: page.sectionCount,
        body: page.body,
        sections: page.sections
      });
      continue;
    }
    const visibleSections = page.sections.filter(
      (section) => !isSecretSection(section)
    );
    resolvedPages.push({
      pageId: page.pageId,
      title: page.title,
      relativePath: page.relativePath,
      sectionCount: visibleSections.length,
      body: composeLoreBody(visibleSections),
      sections: visibleSections
    });
  }

  sendJson(res, 200, {
    ok: true,
    pages: resolvedPages,
    missingPageIds,
    warnings: lore.warnings
  });
}

async function runIngestWork(
  vectorStoreId: string,
  mode: string,
  lore: ReturnType<typeof readLorePages>
): Promise<void> {
  try {
    if (mode === "overwrite") {
      updateLoreIngestState({
        phase: "clearing-store",
        message: "Clearing existing vector store contents before overwrite."
      });
      // Clear is best-effort: if the list endpoint is degraded we still
      // proceed to upload so new content is searchable. Stale files in the
      // vector store are wasteful but not broken.
      try {
        const existingFiles = await withOpenAIRetry("list-vector-store-files", () =>
          listVectorStoreFiles(vectorStoreId)
        );
        for (const item of existingFiles) {
          if (typeof item?.["id"] === "string") {
            await withOpenAIRetry("delete-vector-store-file", () =>
              deleteVectorStoreFile(vectorStoreId, item["id"] as string)
            );
          }
        }
      } catch (clearErr) {
        logInfo("ingest:clear-skipped", {
          reason: clearErr instanceof Error ? clearErr.message : String(clearErr)
        });
        updateLoreIngestState({
          phase: "uploading",
          message: "Could not clear existing files (will upload on top). Proceeding with upload."
        });
      }
    }

    // ONLY WHAT CHANGED. An overwrite rebuilds the store from scratch; the
    // normal path asks what is already indexed and does the difference. Editing
    // one page should cost one page, not the whole wiki -- and a run with
    // nothing changed should be one list call and no uploads at all.
    let pending = lore.chunks;
    let staleFileIds: string[] = [];
    if (mode !== "overwrite") {
      updateLoreIngestState({
        phase: "comparing",
        message: "Checking which chunks have changed."
      });
      const indexed = indexedChunksByAddress(
        await withOpenAIRetry("list-vector-store-files", () =>
          listVectorStoreFiles(vectorStoreId)
        )
      );
      const plan = planIncrementalIngest(lore.chunks, indexed);
      pending = plan.upload;
      // The stale copies go AFTER the new ones are indexed, not before: a
      // delete-then-upload leaves the section missing from retrieval if the
      // upload then fails, and a half-second of two copies is cheaper than a
      // section that silently vanished.
      staleFileIds = plan.remove;

      logInfo("ingest:plan", {
        toUpload: plan.upload.length,
        unchanged: plan.unchanged.length,
        toRemove: plan.remove.length,
        duplicateAddresses: plan.duplicateAddresses.length
      });

      // An authoring bug, surfaced rather than absorbed: two sections on one
      // page whose headings slugify the same share a chunk address, so only one
      // of them can ever be indexed.
      for (const address of plan.duplicateAddresses) {
        lore.warnings.push(
          "Two sections share the chunk address " + address +
            "; rename one heading or only one will be indexed."
        );
      }

      // `uploadedCount` counts this run's work, so `chunkCount` has to as well
      // or the panel reads "4 / 102" -- two numbers with different
      // denominators, which looks like a stall rather than a short run. The
      // SOURCE total stays visible as the top-level `chunkCount` on status.
      updateLoreIngestState({ chunkCount: pending.length });

      if (pending.length === 0 && staleFileIds.length === 0) {
        updateLoreIngestState({
          active: false,
          phase: "completed",
          currentChunkId: null,
          uploadedCount: 0,
          message:
            "Nothing to do -- all " + lore.chunks.length + " chunks are already indexed.",
          completedAt: new Date().toISOString()
        });
        return;
      }
    }

    // TWO PHASES, NOT ONE PER CHUNK. Upload every chunk file concurrently, then
    // attach them in batches and wait once per batch. The old shape waited for
    // each chunk to finish indexing before starting the next, which is what
    // made 98 chunks take a quarter of an hour and what let one slow chunk end
    // the run at 19/98.
    const total = pending.length;
    let uploadedCount = 0;

    const uploaded = await mapWithConcurrency(
      pending,
      UPLOAD_CONCURRENCY,
      async (chunk) => {
        const fileId = await withOpenAIRetry("upload-chunk-" + chunk.chunkId, () =>
          uploadChunkFile(chunk)
        );
        uploadedCount += 1;
        updateLoreIngestState({
          phase: "uploading",
          currentChunkId: chunk.chunkId,
          uploadedCount,
          message: "Uploaded " + uploadedCount + " / " + total + " chunks."
        });
        return { fileId, chunk };
      }
    );

    // `uploadedCount` keeps meaning "chunks safely in the store", so it counts
    // INDEXED files from here rather than uploaded ones. A file that uploaded
    // but failed to index is not ingested, and a progress number that says
    // otherwise is the kind that gets believed.
    let indexedCount = 0;
    for (let start = 0; start < uploaded.length; start += MAX_FILES_PER_BATCH) {
      const slice = uploaded.slice(start, start + MAX_FILES_PER_BATCH);
      const batchBase = indexedCount;
      updateLoreIngestState({
        phase: "waiting-for-indexing",
        currentChunkId: slice[0]?.chunk.chunkId ?? null,
        uploadedCount: indexedCount,
        message:
          "Indexing " + slice.length + " chunks (" + indexedCount + " / " + total + " done)."
      });
      // Not wrapped in withOpenAIRetry: attachChunkBatch retries its own CREATE
      // and tolerates transient status reads, and retrying from out here would
      // re-attach files that are already attached.
      const indexed = await attachChunkBatch(vectorStoreId, slice, (indexedInBatch) => {
        updateLoreIngestState({
          phase: "waiting-for-indexing",
          uploadedCount: batchBase + indexedInBatch,
          message:
            "Indexed " + (batchBase + indexedInBatch) + " / " + total + " chunks."
        });
      });
      // What the batch REPORTED, not how many were handed to it. The two differ
      // exactly when something failed to index, which is the case this number
      // exists to make visible.
      indexedCount += indexed;
    }
    uploadedCount = indexedCount;

    // ONLY NOW. Everything replacing these is indexed and retrievable, so
    // removing the old copies cannot leave a gap. Best-effort: a stale file
    // that outlives its replacement is duplicate content, which is worse than
    // tidy but far better than a missing section -- and it still carries a
    // page_id and chunk_id, so the next incremental run finds and replaces it.
    let removedStale = 0;
    for (const fileId of staleFileIds) {
      try {
        await withOpenAIRetry("delete-stale-file", () =>
          deleteVectorStoreFile(vectorStoreId, fileId)
        );
        removedStale += 1;
      } catch (removeErr) {
        logInfo("ingest:stale-delete-failed", {
          fileId,
          reason: removeErr instanceof Error ? removeErr.message : String(removeErr)
        });
      }
    }

    updateLoreIngestState({
      active: false,
      phase: "completed",
      currentChunkId: null,
      uploadedCount,
      message:
        "Completed lore ingest: " + uploadedCount + " chunk(s) indexed" +
        (removedStale > 0 ? ", " + removedStale + " stale removed" : "") + ".",
      completedAt: new Date().toISOString()
    });
  } catch (error) {
    updateLoreIngestState({
      active: false,
      phase: "failed",
      message: error instanceof Error ? error.message : String(error),
      completedAt: new Date().toISOString()
    });
  }
}

export async function handleSugarAgentLoreIngest(
  req: IncomingMessage,
  res: ServerResponse & { __sugarmagicCors?: Record<string, string> }
): Promise<void> {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }

  if (_loreIngestState.active) {
    sendJson(res, 409, {
      ok: false,
      error: "IngestAlreadyRunning",
      message: "An ingest is already in progress. Poll /status to track it."
    });
    return;
  }

  const body = await readJsonBody(req);
  // Incremental by default. `{"mode":"overwrite"}` still rebuilds from scratch,
  // which is the escape hatch for a store believed to be wrong rather than
  // merely out of date.
  //
  // THE DEFAULT CHANGED. This route used to overwrite whatever the caller sent,
  // so an existing caller that omits `mode` now gets incremental. That is the
  // intended behaviour -- Studio's two buttons send the mode explicitly -- but
  // any other caller relying on the old silence gets the cheaper answer, which
  // is only wrong if it wanted a rebuild.
  const mode = body["mode"] === "overwrite" ? "overwrite" : "incremental";
  const vectorStoreId =
    typeof body["vectorStoreId"] === "string" && body["vectorStoreId"].trim()
      ? body["vectorStoreId"].trim()
      : resolveEnv("SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID");

  if (!vectorStoreId) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidRequest",
      message: "vectorStoreId is required."
    });
    return;
  }

  const lore = readLorePages();
  if (!lore.source.sourceReady) {
    sendJson(res, 400, {
      ok: false,
      error: "LoreSourceUnavailable",
      message: lore.warnings[0] ?? "Lore source is not available."
    });
    return;
  }

  if (lore.chunks.length === 0) {
    sendJson(res, 400, {
      ok: false,
      error: "LoreSourceEmpty",
      message: "No lore pages with canonical frontmatter ids were found in the configured lore source.",
      warnings: lore.warnings
    });
    return;
  }

  updateLoreIngestState({
    active: true,
    phase: "parsed",
    pageCount: lore.pages.length,
    chunkCount: lore.chunks.length,
    uploadedCount: 0,
    currentChunkId: null,
    message: "Parsed " + lore.pages.length + " pages into " + lore.chunks.length + " chunks.",
    warnings: lore.warnings,
    startedAt: new Date().toISOString(),
    completedAt: null
  });

  // Fire the upload work in the background so the HTTP request returns
  // immediately. Studio polls /status at 700ms for progress.
  void runIngestWork(vectorStoreId, mode, lore);

  sendJson(res, 202, {
    ok: true,
    started: true,
    pageCount: lore.pages.length,
    chunkCount: lore.chunks.length,
    warnings: lore.warnings
  });
}

export async function handleSugarAgentLorePing(
  req: IncomingMessage,
  res: ServerResponse & { __sugarmagicCors?: Record<string, string> }
): Promise<void> {
  if (req.method !== "GET") {
    sendMethodNotAllowed(res, ["GET", "OPTIONS"]);
    return;
  }

  const vectorStoreId = resolveEnv("SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID");
  if (!vectorStoreId) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidConfig",
      message: "SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID is not configured."
    });
    return;
  }

  const apiKey = requireEnv("SUGARMAGIC_OPENAI_API_KEY");
  const steps: Record<string, unknown> = {};

  // Read: GET vector store metadata -- proves API key + VS reachability
  try {
    const readRes = await fetch(
      "https://api.openai.com/v1/vector_stores/" + vectorStoreId,
      { method: "GET", headers: { authorization: "Bearer " + apiKey } }
    );
    const readPayload = await parseApiJsonResponse(readRes, "OpenAI vector store read") as Record<string, unknown>;
    steps["read"] = { ok: true, id: readPayload["id"], name: readPayload["name"], status: readPayload["status"] };
  } catch (err) {
    steps["read"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
    sendJson(res, 502, { ok: false, failedAt: "read", steps });
    return;
  }

  // Write: upload a tiny synthetic file -- proves file upload works
  let uploadedFileId: string | null = null;
  try {
    const form = new FormData();
    form.append("purpose", "user_data");
    form.append(
      "file",
      new Blob(["# Ping\n\nTemporary connectivity test."], { type: "text/markdown" }),
      "sugarmagic-ping.md"
    );
    const writeRes = await fetch("https://api.openai.com/v1/files", {
      method: "POST",
      headers: { authorization: "Bearer " + apiKey },
      body: form
    });
    const writePayload = await parseApiJsonResponse(writeRes, "OpenAI file upload") as Record<string, unknown>;
    uploadedFileId = typeof writePayload["id"] === "string" ? writePayload["id"] : null;
    steps["write"] = { ok: true, fileId: uploadedFileId };
  } catch (err) {
    steps["write"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
    sendJson(res, 502, { ok: false, failedAt: "write", steps });
    return;
  }

  // Cleanup: delete the test file
  if (uploadedFileId) {
    try {
      const deleteRes = await fetch("https://api.openai.com/v1/files/" + uploadedFileId, {
        method: "DELETE",
        headers: { authorization: "Bearer " + apiKey }
      });
      await parseApiJsonResponse(deleteRes, "OpenAI file delete");
      steps["cleanup"] = { ok: true };
    } catch (err) {
      steps["cleanup"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
    }
  }

  // Search probe: POST /v1/vector_stores/{id}/search with a known term.
  // This is the exact same endpoint the quest-context middleware uses.
  try {
    const searchRes = await fetch(
      "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/search",
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          authorization: "Bearer " + apiKey
        },
        body: JSON.stringify({ query: "lost baggage claim", max_num_results: 2 })
      }
    );
    const searchPayload = await parseApiJsonResponse(searchRes, "OpenAI vector search probe") as Record<string, unknown>;
    const hits = Array.isArray((searchPayload as { data?: unknown[] })?.data)
      ? (searchPayload as { data: unknown[] }).data.length
      : 0;
    steps["search"] = { ok: true, hits };
  } catch (err) {
    steps["search"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
  }

  sendJson(res, 200, { ok: true, steps });
}

/**
 * POST /sugaragent/lore/probe
 *
 * Full write-then-read roundtrip E2E test driven by the gateway (which holds
 * the API key). Steps:
 *   1. Upload a synthetic file containing a unique probe phrase to /v1/files
 *   2. Attach it to the configured vector store
 *   3. Poll until the file reaches status "completed" (up to 90s)
 *   4. Search the vector store for the probe phrase
 *   5. Verify the phrase appears in at least one result
 *   6. Delete the probe file from the VS and from /v1/files
 *
 * Returns { ok: true, durationMs, steps } on success or
 *         { ok: false, failedAt, error, steps } on failure.
 */
export async function handleSugarAgentLoreProbe(
  req: IncomingMessage,
  res: ServerResponse & { __sugarmagicCors?: Record<string, string> }
): Promise<void> {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }

  const vectorStoreId = resolveEnv("SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID");
  if (!vectorStoreId) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidConfig",
      message: "SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID is not configured."
    });
    return;
  }

  const apiKey = requireEnv("SUGARMAGIC_OPENAI_API_KEY");
  const startMs = Date.now();
  const probePhrase = "smprobe_" + startMs.toString(36) + "_lore_roundtrip_test";
  const steps: Record<string, unknown> = {};
  let uploadedFileId: string | null = null;

  const authHeader = { authorization: "Bearer " + apiKey };

  // Step 0: clear anything a previous probe left behind.
  //
  // Before the upload, so "unattributed" unambiguously means "from an earlier
  // run" and this never has to except its own file.
  //
  // Best-effort on purpose: this is housekeeping bolted to a health check, and
  // a store that cannot be listed is a thing the probe should go on to REPORT,
  // not something it should die of.
  try {
    const swept = await sweepNonLoreVectorStoreFiles(vectorStoreId);
    steps["sweep"] = {
      ok: true,
      removed: swept.removed.length,
      failed: swept.failed,
      fileIds: swept.removed
    };
  } catch (err) {
    steps["sweep"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
  }

  // Step 1: upload probe file
  try {
    const form = new FormData();
    form.append("purpose", "user_data");
    form.append(
      "file",
      new Blob(
        ["# Lore Probe\n\n" + probePhrase + "\n\nThis is a temporary roundtrip test file.\n"],
        { type: "text/markdown" }
      ),
      "smprobe.md"
    );
    const uploadRes = await fetch("https://api.openai.com/v1/files", {
      method: "POST",
      headers: authHeader,
      body: form
    });
    const uploadPayload = await parseApiJsonResponse(uploadRes, "probe:upload") as Record<string, unknown>;
    uploadedFileId = typeof uploadPayload["id"] === "string" ? uploadPayload["id"] : null;
    steps["upload"] = { ok: true, fileId: uploadedFileId };
  } catch (err) {
    steps["upload"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
    sendJson(res, 502, { ok: false, failedAt: "upload", error: steps["upload"], steps, durationMs: Date.now() - startMs });
    return;
  }

  if (!uploadedFileId) {
    sendJson(res, 502, { ok: false, failedAt: "upload", error: "no file id in response", steps, durationMs: Date.now() - startMs });
    return;
  }

  /**
   * CLEANUP ALWAYS RUNS FROM HERE ON.
   *
   * It used to be step 5, in tail position -- so a probe that failed at attach,
   * index or search returned early and left its file PERMANENTLY attached to the
   * vector store. Three such orphans (2026-07-24 x2, 2026-07-27) were found being
   * retrieved as real world context and handed to an NPC mid-conversation.
   *
   * A `finally` is the fix rather than a cleanup call before each early return:
   * the latter is correct only until someone adds a sixth exit.
   */
  let hitFound = false;
  let cleanupDone = false;
  const cleanupProbeFile = async (): Promise<void> => {
    if (cleanupDone || !uploadedFileId) return;
    cleanupDone = true;
    try {
      await fetch(
        "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/files/" + uploadedFileId,
        { method: "DELETE", headers: authHeader }
      );
      await fetch("https://api.openai.com/v1/files/" + uploadedFileId, {
        method: "DELETE",
        headers: authHeader
      });
      steps["cleanup"] = { ok: true };
    } catch (err) {
      // Best effort on the DELETEs themselves -- but the ATTEMPT is now
      // guaranteed, which is the part that was missing.
      steps["cleanup"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
    }
  };

  try {
  // Step 2: attach to vector store
  try {
    const attachRes = await fetch(
      "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/files",
      {
        method: "POST",
        headers: { "content-type": "application/json", ...authHeader },
        body: JSON.stringify({ file_id: uploadedFileId })
      }
    );
    await parseApiJsonResponse(attachRes, "probe:attach");
    steps["attach"] = { ok: true };
  } catch (err) {
    steps["attach"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
    sendJson(res, 502, { ok: false, failedAt: "attach", error: steps["attach"], steps, durationMs: Date.now() - startMs });
    return;
  }

  // Step 3: poll until indexed (90s deadline)
  const deadline = startMs + 90_000;
  let indexed = false;
  let lastStatus = "unknown";
  try {
    while (Date.now() < deadline) {
      await new Promise<void>((r) => setTimeout(r, 2000));
      const statusRes = await fetch(
        "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/files/" + uploadedFileId,
        { method: "GET", headers: authHeader }
      );
      const statusPayload = await parseApiJsonResponse(statusRes, "probe:status") as Record<string, unknown>;
      lastStatus = typeof statusPayload["status"] === "string" ? statusPayload["status"] : "unknown";
      if (lastStatus === "completed") { indexed = true; break; }
      if (lastStatus === "failed" || lastStatus === "cancelled") break;
    }
    steps["index"] = indexed
      ? { ok: true, status: lastStatus }
      : { ok: false, error: "Timed out or failed waiting for indexing: " + lastStatus };
  } catch (err) {
    steps["index"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
  }

  if (!indexed) {
    sendJson(res, 502, { ok: false, failedAt: "index", steps, durationMs: Date.now() - startMs });
    return;
  }

  // Step 4: search for the probe phrase
  try {
    const searchRes = await fetch(
      "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/search",
      {
        method: "POST",
        headers: { "content-type": "application/json", ...authHeader },
        body: JSON.stringify({ query: probePhrase, max_num_results: 4 })
      }
    );
    const searchPayload = await parseApiJsonResponse(searchRes, "probe:search") as Record<string, unknown>;
    const hits = Array.isArray((searchPayload as { data?: unknown[] }).data)
      ? (searchPayload as { data: Array<Record<string, unknown>> }).data
      : [];
    hitFound = hits.some((h) =>
      Array.isArray(h["content"]) &&
      (h["content"] as Array<Record<string, unknown>>).some(
        (c) => typeof c["text"] === "string" && (c["text"] as string).includes(probePhrase)
      )
    );
    steps["search"] = { ok: true, hits: hits.length, hitFound };
  } catch (err) {
    steps["search"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
    sendJson(res, 502, { ok: false, failedAt: "search", steps, durationMs: Date.now() - startMs });
    return;
  }


  } finally {
    await cleanupProbeFile();
  }

  const durationMs = Date.now() - startMs;
  if (!hitFound) {
    sendJson(res, 502, { ok: false, failedAt: "search", error: "probe phrase not found in search results", steps, durationMs });
    return;
  }
  sendJson(res, 200, { ok: true, steps, durationMs });
}

// Plan 081.2 -- /api/sugarlang/telemetry
// DEFERRED (081): events land in Cloud Run structured logs via stdout only.
// BigQuery export is a log-sink config flip on the Cloud Run project; revisit
// when the first real tuning question needs SQL over months of events.

// Server-side re-strip of player-text PII before events hit stdout/logs.
// The client (GatewaySugarlangTelemetrySink.stripPii) already strips these;
// this is a cheap defense-in-depth pass for old or misbehaving clients.
// Keep in sync with SERVER_BOUND_PII_FIELDS in
// packages/plugins/src/catalog/sugarlang/runtime/telemetry/telemetry.ts
// (the gateway compiles standalone and cannot import from that package).
const SUGARLANG_TELEMETRY_PII_FIELDS = [
  "inputText",
  "originalText",
  "repairedText",
  "playerResponseText"
];

function scrubSugarlangTelemetryEvent(event: Record<string, unknown>): void {
  for (const field of SUGARLANG_TELEMETRY_PII_FIELDS) {
    delete event[field];
  }
  // observe.observations-applied nests player-typed text at
  // observations[].observation.inputText.
  const observations = event.observations;
  if (!Array.isArray(observations)) {
    return;
  }
  for (const entry of observations) {
    if (typeof entry !== "object" || entry === null) {
      continue;
    }
    const observation = (entry as { observation?: unknown }).observation;
    if (typeof observation === "object" && observation !== null) {
      delete (observation as Record<string, unknown>).inputText;
    }
  }
}

async function handleSugarlangTelemetry(
  req: IncomingMessage,
  res: ServerResponse
): Promise<void> {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST"]);
    return;
  }

  const BODY_LIMIT = 200 * 1024;
  let raw = "";
  for await (const chunk of req) {
    raw += chunk.toString();
    if (raw.length > BODY_LIMIT) {
      sendJson(res, 413, { ok: false, error: "RequestBodyTooLarge" });
      return;
    }
  }

  let body: Record<string, unknown>;
  try {
    body = JSON.parse(raw || "{}") as Record<string, unknown>;
  } catch {
    sendJson(res, 400, { ok: false, error: "InvalidJson" });
    return;
  }

  const events = Array.isArray(body.events) ? body.events : [];
  const accepted = Math.min(events.length, 100);
  for (let i = 0; i < accepted; i++) {
    const event = events[i];
    if (typeof event === "object" && event !== null) {
      scrubSugarlangTelemetryEvent(event as Record<string, unknown>);
      process.stdout.write(JSON.stringify(event) + "\n");
    }
  }

  sendJson(res, 200, { ok: true, accepted });
}

// ---------------------------------------------------------------------------
// Server
// ---------------------------------------------------------------------------

type GatewayRequest = IncomingMessage & { __sugarmagicCors?: Record<string, string>; user?: { userId: string; email: string | null } };
type GatewayResponse = ServerResponse & { __sugarmagicCors?: Record<string, string> };

export const server = createServer(async (req: GatewayRequest, res: GatewayResponse) => {
  // Story 46.9 — resolve CORS headers once per request, stash on the
  // response, then sendJson / sendMethodNotAllowed read them off the
  // response so call sites don't have to thread req.
  res.__sugarmagicCors = resolveCorsHeaders(req);

  if (req.method === "OPTIONS") {
    // CORS preflight. Echo the request's
    // access-control-request-headers verbatim when present so we don't
    // have to enumerate them; fall back to a safe default.
    const requestedHeaders = req.headers["access-control-request-headers"];
    res.writeHead(204, {
      ..._baseHeaders,
      ...res.__sugarmagicCors,
      "access-control-allow-methods": "GET,POST,PUT,PATCH,DELETE,OPTIONS",
      "access-control-allow-headers":
        typeof requestedHeaders === "string" && requestedHeaders.length > 0
          ? requestedHeaders
          : "content-type, authorization",
      "access-control-max-age": "86400"
    });
    res.end();
    return;
  }

  const path = normalizePath(req.url);
  logInfo("gateway:request", {
    method: req.method ?? "GET",
    path
  });
  // /health (not /healthz): Cloud Run's frontend reserves /healthz
  // specifically — it gets intercepted before reaching the container,
  // returning Google's generic 404 page with no x-cloud-trace-context
  // header. Discovered the hard way during 45.5.7 verification.
  if (path === "/" || path === "/health") {
    sendJson(res, 200, {
      ok: true,
      target: _targetId,
      serviceUnitId: _serviceUnitId,
      routes: _routes
    });
    return;
  }

  // Story 45.5.8 / Story 47.9 — auth gate. Assembled based on the effective
  // gatewayAuthMode at plan time:
  //   - "none"          -> no gate
  //   - "bearer"        -> shared-token check (45.5.8)
  //   - "supabase-jwt"  -> Supabase HS256/ES256 verification (47.9)
  // /health stays public above; this gate runs on EVERY other path before
  // the route dispatcher.
  /*! __GATEWAY_AUTH_GATE__ */

  const match = findManagedRoute(path);
  if (!match) {
    logInfo("gateway:route-not-managed", {
      path,
      knownRoutes: _routes.map((route) => route.path)
    });
    sendJson(res, 404, {
      ok: false,
      error: "RouteNotManaged",
      message: "SugarDeploy generated this gateway scaffold, but the requested route is not declared for this service unit.",
      path,
      knownRoutes: _routes.map((route) => route.path)
    });
    return;
  }

  try {
    if (match.routeId === "sugaragent-generate" && path === match.path) {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentGenerate(req, res);
      return;
    }

    if (match.routeId === "sugaragent-generate" && path === match.path + "/judge") {
      logInfo("gateway:dispatch", { routeId: match.routeId, path });
      await handleSugarAgentJudge(req, res);
      return;
    }

    if (match.routeId === "sugaragent-generate" && path === match.path + "/moderate") {
      logInfo("gateway:dispatch", { routeId: match.routeId, path });
      await handleSugarAgentModerate(req, res);
      return;
    }

    if (match.routeId === "sugaragent-retrieve" && path === match.path + "/search") {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentSearch(req, res);
      return;
    }

    if (match.routeId === "sugaragent-lore" && path === match.path + "/status") {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentLoreStatus(req, res);
      return;
    }

    if (match.routeId === "sugaragent-lore" && path === match.path + "/pages") {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentLorePages(req, res);
      return;
    }

    if (match.routeId === "sugaragent-lore" && path === match.path + "/resolve") {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentLoreResolve(req, res);
      return;
    }

    if (match.routeId === "sugaragent-lore" && path === match.path + "/ingest") {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentLoreIngest(req, res);
      return;
    }

    if (match.routeId === "sugaragent-lore" && path === match.path + "/ping") {
      logInfo("gateway:dispatch", { routeId: match.routeId, path });
      await handleSugarAgentLorePing(req, res);
      return;
    }

    if (match.routeId === "sugaragent-lore" && path === match.path + "/probe") {
      logInfo("gateway:dispatch", { routeId: match.routeId, path });
      await handleSugarAgentLoreProbe(req, res);
      return;
    }

    if (match.routeId === "sugarlang-telemetry" && path === match.path) {
      logInfo("gateway:dispatch", { routeId: match.routeId, path });
      await handleSugarlangTelemetry(req, res);
      return;
    }

    logInfo("gateway:route-unimplemented", {
      routeId: match.routeId,
      path
    });
    sendJson(res, 501, {
      ok: false,
      error: "ProxyHandlerNotImplemented",
      target: _targetId,
      serviceUnitId: _serviceUnitId,
      route: match,
      request: {
        method: req.method,
        path
      },
      message:
        "SugarDeploy generated the backend gateway scaffold for this route, but no concrete handler is registered for this path yet."
    });
  } catch (error) {
    logError("gateway:handler-failure", error, {
      routeId: match.routeId,
      path
    });
    sendJson(res, 500, {
      ok: false,
      error: "GatewayProxyFailure",
      target: _targetId,
      serviceUnitId: _serviceUnitId,
      route: match,
      path,
      message: error instanceof Error ? error.message : String(error)
    });
  }
});

// ---------------------------------------------------------------------------
// Entry point (only when run as a script, not when imported for testing)
// ---------------------------------------------------------------------------

const __gatewayFilename = fileURLToPath(import.meta.url);
if (process.argv[1] === __gatewayFilename) {
  const __dir = dirname(__gatewayFilename);
  const manifest = JSON.parse(readFileSync(join(__dir, "routes.json"), "utf8")) as RouteManifest;
  initGateway(manifest);
  const port = Number(process.env["PORT"] || manifest.containerPort || 8080);
  server.listen(port, () => {
    console.log("[sugardeploy] gateway " + manifest.serviceUnitId + " listening on port " + port);
  });
}
