// GENERATED BY SUGARMAGIC - DO NOT EDIT directly in server.mjs.
// This file is compiled and concatenated into server.mjs by buildGatewayServerFile
// for supabase-jwt auth mode. It has no imports from @sugarmagic/* packages.
// logError is NOT imported here to avoid a circular dep with core.ts;
// error paths use console.error directly.

import {
  createHmac,
  createPublicKey,
  timingSafeEqual,
  verify as cryptoVerify
} from "node:crypto";
import type { IncomingMessage } from "node:http";

function decodeBase64Url(segment: string): Buffer {
  // Supabase tokens are base64url; Buffer.from(..., "base64") accepts
  // base64url-style input on Node 18+, but we normalize defensively
  // so older runtimes still decode cleanly.
  const normalized = segment.replace(/-/g, "+").replace(/_/g, "/");
  const padding = normalized.length % 4 === 0 ? 0 : 4 - (normalized.length % 4);
  return Buffer.from(normalized + "=".repeat(padding), "base64");
}

// Module-level JWKS cache. 10-minute TTL covers normal key rotation
// without thrashing the upstream; a manual restart drops the cache
// faster if needed.
const __jwksCache: { url: string; expiresAt: number; keys: Record<string, unknown>[] } = {
  url: "",
  expiresAt: 0,
  keys: []
};
const __JWKS_TTL_MS = 10 * 60 * 1000;

async function __fetchJwks(jwksUrl: string): Promise<Record<string, unknown>[] | null> {
  const now = Date.now();
  if (__jwksCache.url === jwksUrl && __jwksCache.expiresAt > now) {
    return __jwksCache.keys;
  }
  let response: Response;
  try {
    response = await fetch(jwksUrl);
  } catch (error) {
    console.error("[sugardeploy] supabase-jwt:jwks-fetch-failed " + JSON.stringify({
      jwksUrl,
      error: error instanceof Error ? error.message : String(error)
    }));
    return null;
  }
  if (!response.ok) {
    console.error("[sugardeploy] supabase-jwt:jwks-non-2xx " + JSON.stringify({
      jwksUrl,
      status: response.status
    }));
    return null;
  }
  let body: unknown;
  try {
    body = await response.json();
  } catch (error) {
    console.error("[sugardeploy] supabase-jwt:jwks-bad-json " + JSON.stringify({
      jwksUrl,
      error: error instanceof Error ? error.message : String(error)
    }));
    return null;
  }
  const keys = Array.isArray(body && (body as { keys?: unknown }).keys)
    ? (body as { keys: Record<string, unknown>[] }).keys
    : [];
  __jwksCache.url = jwksUrl;
  __jwksCache.expiresAt = now + __JWKS_TTL_MS;
  __jwksCache.keys = keys;
  return keys;
}

// Convert a JWS-format ES256 signature (raw concat r||s, 64 bytes
// total) to DER-encoded ECDSA signature, which is what Node's
// crypto.verify expects.
function __jwsSigToDer(rawSig: Buffer): Buffer | null {
  if (rawSig.length !== 64) return null;
  const r = rawSig.subarray(0, 32);
  const s = rawSig.subarray(32);
  function trim(buf: Buffer): Buffer {
    let i = 0;
    while (i < buf.length - 1 && buf[i] === 0) i++;
    let trimmed = buf.subarray(i);
    if (trimmed[0]! & 0x80) {
      trimmed = Buffer.concat([Buffer.from([0]), trimmed]);
    }
    return trimmed;
  }
  const rTrimmed = trim(r);
  const sTrimmed = trim(s);
  const seqBody = Buffer.concat([
    Buffer.from([0x02, rTrimmed.length]),
    rTrimmed,
    Buffer.from([0x02, sTrimmed.length]),
    sTrimmed
  ]);
  return Buffer.concat([Buffer.from([0x30, seqBody.length]), seqBody]);
}

export async function verifySupabaseJwt(
  req: IncomingMessage
): Promise<{ userId: string; email: string | null } | null> {
  const supabaseUrl = (process.env["SUGARMAGIC_SUGARPROFILE_SUPABASE_URL"] || "").trim();
  if (!supabaseUrl) return null;
  const jwksUrl = supabaseUrl.replace(/\/+$/, "") + "/auth/v1/.well-known/jwks.json";

  const authHeader = (req.headers && req.headers["authorization"]) || "";
  const prefix = "Bearer ";
  if (typeof authHeader !== "string" || !authHeader.startsWith(prefix)) return null;
  const token = authHeader.slice(prefix.length).trim();
  if (!token) return null;
  const parts = token.split(".");
  if (parts.length !== 3) return null;
  const [headerB64, payloadB64, signatureB64] = parts as [string, string, string];

  let jwtHeader: Record<string, unknown>;
  try {
    jwtHeader = JSON.parse(decodeBase64Url(headerB64).toString("utf8")) as Record<string, unknown>;
  } catch {
    return null;
  }
  if (!jwtHeader || typeof jwtHeader !== "object") return null;
  const alg = jwtHeader["alg"];
  const kid = jwtHeader["kid"];
  if (typeof alg !== "string" || typeof kid !== "string" || !kid) return null;
  if (alg !== "ES256" && alg !== "HS256") return null;

  const keys = await __fetchJwks(jwksUrl);
  if (!keys) return null;
  const jwk = keys.find((entry) => entry && entry["kid"] === kid);
  if (!jwk) return null;
  if (jwk["alg"] && jwk["alg"] !== alg) return null;

  let signature: Buffer;
  try {
    signature = decodeBase64Url(signatureB64);
  } catch {
    return null;
  }
  const signingInput = Buffer.from(headerB64 + "." + payloadB64, "utf8");

  if (alg === "ES256") {
    if (jwk["kty"] !== "EC" || jwk["crv"] !== "P-256") return null;
    let publicKey: ReturnType<typeof createPublicKey>;
    try {
      publicKey = createPublicKey({ key: jwk, format: "jwk" } as unknown as Parameters<typeof createPublicKey>[0]);
    } catch (error) {
      console.error("[sugardeploy] supabase-jwt:jwk-import-failed " + JSON.stringify({
        kid,
        error: error instanceof Error ? error.message : String(error)
      }));
      return null;
    }
    const derSig = __jwsSigToDer(signature);
    if (!derSig) return null;
    let valid: boolean;
    try {
      valid = cryptoVerify("SHA256", signingInput, publicKey, derSig);
    } catch {
      return null;
    }
    if (!valid) return null;
  } else {
    if (jwk["kty"] !== "oct" || typeof jwk["k"] !== "string") return null;
    let secretBytes: Buffer;
    try {
      secretBytes = decodeBase64Url(jwk["k"] as string);
    } catch {
      return null;
    }
    const expectedSig = createHmac("sha256", secretBytes)
      .update(signingInput)
      .digest();
    if (expectedSig.length !== signature.length) return null;
    try {
      if (!timingSafeEqual(expectedSig, signature)) return null;
    } catch {
      return null;
    }
  }

  let payload: Record<string, unknown>;
  try {
    payload = JSON.parse(decodeBase64Url(payloadB64).toString("utf8")) as Record<string, unknown>;
  } catch {
    return null;
  }
  if (payload === null || typeof payload !== "object") return null;
  if (payload["aud"] !== "authenticated") return null;
  const nowSeconds = Math.floor(Date.now() / 1000);
  if (typeof payload["exp"] !== "number" || payload["exp"] <= nowSeconds) return null;
  if (typeof payload["sub"] !== "string" || !payload["sub"]) return null;

  return {
    userId: payload["sub"] as string,
    email: typeof payload["email"] === "string" ? payload["email"] : null
  };
}
