/**
 * Cloud Run plugin-owned terraform generators.
 *
 * Emits the terraform that stands up the slow-changing infrastructure around a
 * game's Cloud Run deployment slot: Artifact Registry repo, runtime service
 * account, Workload Identity Federation pool/provider scoped to the configured
 * GitHub repo, IAM bindings (run.admin / artifactregistry.writer /
 * secretmanager.viewer for the WIF principal; secretAccessor for the runtime
 * SA), and empty Secret Manager containers for each declared secret.
 *
 * Terraform deliberately does NOT own the `google_cloud_run_v2_service`
 * resource — the Cloud Run service lifecycle is `gcloud`-managed by the
 * generated `deploy.sh` (and, later, the Stop / Health host actions). See
 * Plan 045 for the rationale.
 */
import type { DeploymentPlan, DeploymentServiceUnit } from "./index";
import type { GoogleCloudRunDeploymentTargetOverrides } from "./overrides";

/**
 * Template version stamped into every generated terraform file. Bump this when
 * any generated resource address changes, and add an entry to
 * `TERRAFORM_RENAME_LEDGER` so existing games get a non-destructive `moved {}`
 * chain on regeneration.
 */
// Story 46.10 — bumped 3 → 4 for the new
// `github_impersonates_runtime_token_creator` IAM binding (lets the
// WIF principal call iam.serviceAccounts.getAccessToken on the
// runtime SA so google-github-actions/auth@v2 can impersonate it).
// Story 46.9 bumped 2 → 3 for the new `allowed_origins` variable +
// output (CORS plumbing). No `moved {}` blocks needed; the change is
// additive (new variable + new output, no resource renames).
export const CLOUD_RUN_TEMPLATE_VERSION = 4;

export interface TerraformResourceMove {
  from: string;
  to: string;
}

export interface TerraformRenameEntry {
  fromVersion: number;
  toVersion: number;
  moves: TerraformResourceMove[];
}

/**
 * Historical rename ledger for Cloud Run terraform. Empty for v1; future
 * template-version bumps append entries here and the generator walks the
 * ledger to emit the union of `moved {}` blocks needed for any on-disk version
 * < current.
 */
export const TERRAFORM_RENAME_LEDGER: TerraformRenameEntry[] = [];

const DEPLOYMENT_HEADER = "GENERATED BY SUGARMAGIC - DO NOT EDIT";
const TEMPLATE_VERSION_STAMP_PREFIX = "# SUGARMAGIC TEMPLATE VERSION:";
const TERRAFORM_HEADER = [
  `# ${DEPLOYMENT_HEADER}`,
  `${TEMPLATE_VERSION_STAMP_PREFIX} ${CLOUD_RUN_TEMPLATE_VERSION}`,
  ""
].join("\n");

/**
 * Secret Manager naming source of truth.
 * Produces `${serviceNamePrefix}-${secretKey}` with GCP-safe slugification:
 * lowercase, replace any char NOT in [a-z0-9-] with `-`, collapse runs, trim,
 * and prepend `s-` if the result starts with a digit (Secret Manager IDs
 * cannot start with a digit). Caps the final name at 80 chars and throws
 * if exceeded.
 *
 * Called by the terraform tfvars generator here, and (when 45.5 lands) by the
 * deploy-script generator, the `set-secret-value` host action, and the
 * `secret-status` host action. Those four call sites must route through this
 * helper or the names will drift.
 */
export function resolveSecretManagerName(
  serviceNamePrefix: string,
  secretKey: string
): string {
  if (!serviceNamePrefix) {
    throw new Error(
      "resolveSecretManagerName: serviceNamePrefix is empty; caller should resolve the prefix (default `${slug}-v${majorVersion}` or the user override) before invoking this helper."
    );
  }
  if (!secretKey) {
    throw new Error("resolveSecretManagerName: secretKey is empty");
  }
  const composed = `${serviceNamePrefix}-${secretKey}`;
  let slug = composed
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "");
  if (/^\d/.test(slug)) {
    slug = `s-${slug}`;
  }
  if (slug.length > 80) {
    throw new Error(
      `resolveSecretManagerName: resolved name "${slug}" exceeds 80 characters; shorten the service prefix or secret key`
    );
  }
  return slug;
}

/**
 * Pure parser for the `# SUGARMAGIC TEMPLATE VERSION: NN` stamp at the top of
 * a generated `main.tf`. Returns the parsed version, or `null` when no stamp
 * is present (e.g. terraform was never generated, or it was hand-edited and
 * the stamp removed). The Studio side calls this via a thin FS-reading
 * wrapper (added in 45.7 when the drift banner lands).
 */
export function parseTemplateVersionStamp(mainTfContent: string | null): number | null {
  if (!mainTfContent) return null;
  const match = mainTfContent.match(/^#\s*SUGARMAGIC TEMPLATE VERSION:\s*(\d+)/m);
  if (!match) return null;
  const parsed = Number.parseInt(match[1], 10);
  return Number.isFinite(parsed) && parsed >= 1 ? parsed : null;
}

function collectUniqueSecretKeys(plan: DeploymentPlan): string[] {
  const seen = new Set<string>();
  for (const unit of plan.serviceUnits) {
    for (const secret of unit.secrets) {
      if (secret.secretKey) seen.add(secret.secretKey);
    }
  }
  return Array.from(seen).sort();
}

/**
 * Resolve the env-var-name → Secret-Manager-name bindings for `gcloud run
 * deploy --set-secrets=KEY=NAME:latest`. The env var name comes from each
 * SecretRequirement's `mappingHint` (e.g. `SUGARMAGIC_ANTHROPIC_API_KEY`);
 * when absent we derive it as `secretKey.toUpperCase().replace(/-/g, "_")`
 * so the binding still works for plugins that haven't bothered with the
 * hint. Story 45.5. Single source of truth used by the deploy-script
 * generator AND (when 45.5's set-secret-value action lands) by the host
 * action to look up the Secret Manager name from the requirement.
 */
export interface SecretEnvBinding {
  secretKey: string;
  envVarName: string;
  secretManagerName: string;
}

export function collectSecretEnvBindings(
  plan: DeploymentPlan,
  serviceNamePrefix: string
): SecretEnvBinding[] {
  const byKey = new Map<string, SecretEnvBinding>();
  for (const unit of plan.serviceUnits) {
    for (const secret of unit.secrets) {
      if (!secret.secretKey || byKey.has(secret.secretKey)) continue;
      const envVarName =
        secret.mappingHint && secret.mappingHint.trim().length > 0
          ? secret.mappingHint.trim()
          : secret.secretKey.toUpperCase().replace(/-/g, "_");
      byKey.set(secret.secretKey, {
        secretKey: secret.secretKey,
        envVarName,
        secretManagerName: resolveSecretManagerName(
          serviceNamePrefix,
          secret.secretKey
        )
      });
    }
  }
  return Array.from(byKey.values()).sort((left, right) =>
    left.secretKey.localeCompare(right.secretKey)
  );
}

function resolveRuntimeServiceAccountId(
  overrides: GoogleCloudRunDeploymentTargetOverrides
): string {
  const explicit = overrides.runtimeServiceAccountName.trim();
  if (explicit.length > 0) return explicit;
  return `${overrides.serviceNamePrefix}-runtime`;
}

function emitMovedBlocks(onDiskVersion: number | null): string {
  // For each ledger entry where toVersion is in (onDiskVersion, current],
  // emit one `moved { from = "..."; to = "..." }` block per move. Ledger is
  // empty in v1 so this returns an empty string.
  if (onDiskVersion === null || onDiskVersion >= CLOUD_RUN_TEMPLATE_VERSION) {
    return "";
  }
  const blocks: string[] = [];
  for (const entry of TERRAFORM_RENAME_LEDGER) {
    if (entry.toVersion > onDiskVersion && entry.toVersion <= CLOUD_RUN_TEMPLATE_VERSION) {
      for (const move of entry.moves) {
        blocks.push(
          `moved {\n  from = ${move.from}\n  to   = ${move.to}\n}`
        );
      }
    }
  }
  if (blocks.length === 0) return "";
  return [
    "",
    `# moved {} blocks emitted to upgrade an on-disk template version ${onDiskVersion}`,
    `# to current ${CLOUD_RUN_TEMPLATE_VERSION} without destroying existing resources.`,
    blocks.join("\n\n"),
    ""
  ].join("\n");
}

export interface BuildCloudRunTerraformOptions {
  /**
   * The version stamp already on disk (parsed via parseTemplateVersionStamp).
   * Passed in by the host action that drives regeneration; the generator uses
   * it to emit the right `moved {}` chain. `null` for fresh / never-generated
   * terraform.
   */
  onDiskTemplateVersion?: number | null;
}

export function buildCloudRunTerraformMainFile(
  plan: DeploymentPlan,
  overrides: GoogleCloudRunDeploymentTargetOverrides,
  options: BuildCloudRunTerraformOptions = {}
): string {
  const movedBlocks = emitMovedBlocks(options.onDiskTemplateVersion ?? null);
  return [
    TERRAFORM_HEADER,
    `terraform {`,
    `  required_version = ">= 1.5"`,
    `  required_providers {`,
    `    google = {`,
    `      source  = "hashicorp/google"`,
    `      version = "~> 5.0"`,
    `    }`,
    `  }`,
    `}`,
    ``,
    `provider "google" {`,
    `  project = var.gcp_project_id`,
    `  region  = var.region`,
    ``,
    `  # user_project_override + billing_project tell the provider to bill API`,
    `  # quota against the project we're managing (not against ADC's separately-`,
    `  # configured quota project). Without this, calls to APIs like orgpolicy`,
    `  # fail with "API requires a quota project" because ADC defaults to whatever`,
    `  # the user last set via \`gcloud auth application-default set-quota-project\``,
    `  # — which a sugarmagic user should never have to think about. This makes`,
    `  # the terraform plan self-contained: it picks its own billing project from`,
    `  # the deployment variables, regardless of the user's local gcloud state.`,
    `  user_project_override = true`,
    `  billing_project       = var.gcp_project_id`,
    `}`,
    ``,
    `# Artifact Registry — Docker repo for Cloud Run gateway images.`,
    `resource "google_artifact_registry_repository" "gateway" {`,
    `  location      = var.region`,
    `  repository_id = var.service_name_prefix`,
    `  description   = "Cloud Run gateway images for \${var.service_name_prefix}"`,
    `  format        = "DOCKER"`,
    `}`,
    ``,
    `# Runtime service account — Cloud Run service runs as this identity at request time.`,
    `resource "google_service_account" "runtime" {`,
    `  account_id   = var.runtime_sa_account_id`,
    `  display_name = "Cloud Run runtime SA for \${var.service_name_prefix}"`,
    `}`,
    ``,
    `# Workload Identity Federation pool for GitHub Actions.`,
    `resource "google_iam_workload_identity_pool" "github" {`,
    `  workload_identity_pool_id = "\${var.service_name_prefix}-gh"`,
    `  display_name              = "GitHub OIDC pool"`,
    `  description               = "Lets GitHub Actions in \${var.github_repo} deploy this game"`,
    `}`,
    ``,
    `resource "google_iam_workload_identity_pool_provider" "github" {`,
    `  workload_identity_pool_id          = google_iam_workload_identity_pool.github.workload_identity_pool_id`,
    `  workload_identity_pool_provider_id = "github"`,
    `  display_name                       = "GitHub OIDC"`,
    ``,
    `  attribute_mapping = {`,
    `    "google.subject"       = "assertion.sub"`,
    `    "attribute.repository" = "assertion.repository"`,
    `    "attribute.actor"      = "assertion.actor"`,
    `  }`,
    ``,
    `  attribute_condition = "attribute.repository == \\"\${var.github_repo}\\""`,
    ``,
    `  oidc {`,
    `    issuer_uri = "https://token.actions.githubusercontent.com"`,
    `  }`,
    `}`,
    ``,
    `locals {`,
    `  github_principal = "principalSet://iam.googleapis.com/\${google_iam_workload_identity_pool.github.name}/attribute.repository/\${var.github_repo}"`,
    `}`,
    ``,
    `# GitHub deploy identity gets the roles needed to push images, deploy Cloud Run, and reference secrets.`,
    `resource "google_project_iam_member" "github_run_admin" {`,
    `  project = var.gcp_project_id`,
    `  role    = "roles/run.admin"`,
    `  member  = local.github_principal`,
    `}`,
    ``,
    `resource "google_project_iam_member" "github_artifactregistry_writer" {`,
    `  project = var.gcp_project_id`,
    `  role    = "roles/artifactregistry.writer"`,
    `  member  = local.github_principal`,
    `}`,
    ``,
    `resource "google_project_iam_member" "github_secretmanager_viewer" {`,
    `  project = var.gcp_project_id`,
    `  role    = "roles/secretmanager.viewer"`,
    `  member  = local.github_principal`,
    `}`,
    ``,
    `# GitHub identity can act-as the runtime SA so \`gcloud run deploy --service-account\` works.`,
    `resource "google_service_account_iam_member" "github_impersonates_runtime" {`,
    `  service_account_id = google_service_account.runtime.name`,
    `  role               = "roles/iam.serviceAccountUser"`,
    `  member             = local.github_principal`,
    `}`,
    ``,
    `# Story 46.10 — google-github-actions/auth@v2 with`,
    `# \`service_account: <runtime SA>\` impersonates that SA by calling`,
    `# iam.serviceAccounts.getAccessToken, which requires`,
    `# roles/iam.serviceAccountTokenCreator (NOT just serviceAccountUser).`,
    `# Without this binding the GHA job fails with`,
    `# "Permission 'iam.serviceAccounts.getAccessToken' denied".`,
    `resource "google_service_account_iam_member" "github_impersonates_runtime_token_creator" {`,
    `  service_account_id = google_service_account.runtime.name`,
    `  role               = "roles/iam.serviceAccountTokenCreator"`,
    `  member             = local.github_principal`,
    `}`,
    ``,
    `# Runtime SA can read Secret Manager values at request time.`,
    `resource "google_project_iam_member" "runtime_secret_accessor" {`,
    `  project = var.gcp_project_id`,
    `  role    = "roles/secretmanager.secretAccessor"`,
    `  member  = "serviceAccount:\${google_service_account.runtime.email}"`,
    `}`,
    ``,
    `# Empty Secret Manager containers — one per declared secret. Values are written separately`,
    `# via \`gcloud secrets versions add\` (Studio host action; never via terraform).`,
    `resource "google_secret_manager_secret" "containers" {`,
    `  for_each  = toset(var.secret_names)`,
    `  secret_id = each.value`,
    ``,
    `  replication {`,
    `    auto {}`,
    `  }`,
    `}`,
    ``,
    `# Story 45.5.7 — project-level org-policy override allowing the`,
    `# \`allUsers\` IAM member, so the Cloud Run gateway can be made`,
    `# publicly reachable. Requires \`roles/orgpolicy.policyAdmin\` at the`,
    `# org level for the deploying principal (granted by the`,
    `# create-gcp-project host action). The actual SERVICE-level binding`,
    `# (allUsers → roles/run.invoker on the deployed Cloud Run service)`,
    `# happens via deploy.sh's \`gcloud run deploy --allow-unauthenticated\``,
    `# flag — that's the only correct level for an allUsers binding`,
    `# (project-level IAM rejects allUsers with PROJECT_SET_IAM_DISALLOWED_MEMBER_TYPE).`,
    `# Without THIS org-policy override, that flag fails silently.`,
    `resource "google_org_policy_policy" "allow_public_invokers" {`,
    `  name   = "projects/\${var.gcp_project_id}/policies/iam.allowedPolicyMemberDomains"`,
    `  parent = "projects/\${var.gcp_project_id}"`,
    `  spec {`,
    `    rules {`,
    `      allow_all = "TRUE"`,
    `    }`,
    `  }`,
    `}`,
    movedBlocks
  ].filter((line) => line !== "" || true).join("\n");
}

export function buildCloudRunTerraformVariablesFile(): string {
  return [
    TERRAFORM_HEADER,
    `variable "gcp_project_id" {`,
    `  description = "GCP project hosting this game's deployment slot"`,
    `  type        = string`,
    `}`,
    ``,
    `variable "region" {`,
    `  description = "GCP region for Cloud Run and Artifact Registry"`,
    `  type        = string`,
    `}`,
    ``,
    `variable "service_name_prefix" {`,
    `  description = "Prefix for derived resource names (Artifact Registry repo, Secret Manager containers, WIF pool)"`,
    `  type        = string`,
    `}`,
    ``,
    `variable "runtime_sa_account_id" {`,
    `  description = "account_id (left of @) for the runtime service account"`,
    `  type        = string`,
    `}`,
    ``,
    `variable "github_repo" {`,
    `  description = "GitHub owner/repo authorized to deploy via Workload Identity Federation"`,
    `  type        = string`,
    `}`,
    ``,
    `variable "secret_names" {`,
    `  description = "Secret Manager secret IDs to create empty containers for"`,
    `  type        = list(string)`,
    `  default     = []`,
    `}`,
    ``,
    // Story 46.9 — gateway CORS-allowed origins (Netlify per-deploy
    // wildcard + alias + custom domain). Comma-joined and threaded to
    // the gateway via deploy.sh as SUGARMAGIC_GATEWAY_ALLOWED_ORIGINS.
    `variable "allowed_origins" {`,
    `  description = "Origins the gateway echoes in Access-Control-Allow-Origin. Patterns may contain a single '*' for the Netlify per-deploy subdomain wildcard."`,
    `  type        = list(string)`,
    `  default     = []`,
    `}`,
    ``
  ].join("\n");
}

export function buildCloudRunTerraformOutputsFile(): string {
  return [
    TERRAFORM_HEADER,
    `output "artifact_registry_url" {`,
    `  description = "Artifact Registry Docker URL prefix for pushing gateway images"`,
    `  value       = "\${var.region}-docker.pkg.dev/\${var.gcp_project_id}/\${google_artifact_registry_repository.gateway.repository_id}"`,
    `}`,
    ``,
    `output "runtime_sa_email" {`,
    `  description = "Runtime service account email for \`gcloud run deploy --service-account\`"`,
    `  value       = google_service_account.runtime.email`,
    `}`,
    ``,
    `output "github_wif_provider_name" {`,
    `  description = "Full WIF provider resource name for GitHub Actions \`workload_identity_provider\`"`,
    `  value       = google_iam_workload_identity_pool_provider.github.name`,
    `}`,
    ``,
    `output "secret_names" {`,
    `  description = "Secret Manager secret IDs created by terraform (empty containers; values written via gcloud)"`,
    `  value       = [for s in google_secret_manager_secret.containers : s.secret_id]`,
    `}`,
    ``,
    // Story 46.9 — echo `var.allowed_origins` as an output so
    // deploy.sh can read it via `terraform output -json` and forward
    // to the gateway as SUGARMAGIC_GATEWAY_ALLOWED_ORIGINS.
    `output "allowed_origins" {`,
    `  description = "Comma-joined list of origins the gateway should accept for CORS. Set on Cloud Run via deploy.sh --set-env-vars."`,
    `  value       = var.allowed_origins`,
    `}`,
    ``
  ].join("\n");
}

function tfStringLiteral(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function tfStringList(values: string[]): string {
  if (values.length === 0) return "[]";
  return `[\n${values.map((v) => `  ${tfStringLiteral(v)}`).join(",\n")}\n]`;
}

export function buildCloudRunTerraformTfvarsFile(
  plan: DeploymentPlan,
  overrides: GoogleCloudRunDeploymentTargetOverrides,
  // Story 46.9 — derived by `deriveGatewayAllowedOrigins(plan, gameProject)`
  // in the plan-build path; passed in so this generator stays pure
  // (no GameProject reach).
  allowedOrigins: string[] = []
): string {
  const secretKeys = collectUniqueSecretKeys(plan);
  const secretNames = secretKeys.map((key) =>
    resolveSecretManagerName(overrides.serviceNamePrefix, key)
  );
  const runtimeSaAccountId = resolveRuntimeServiceAccountId(overrides);
  return [
    TERRAFORM_HEADER,
    `gcp_project_id        = ${tfStringLiteral(overrides.projectId)}`,
    `region                = ${tfStringLiteral(overrides.region)}`,
    `service_name_prefix   = ${tfStringLiteral(overrides.serviceNamePrefix)}`,
    `runtime_sa_account_id = ${tfStringLiteral(runtimeSaAccountId)}`,
    `github_repo           = ${tfStringLiteral(overrides.githubRepo)}`,
    `secret_names          = ${tfStringList(secretNames)}`,
    `allowed_origins       = ${tfStringList(allowedOrigins)}`,
    ``
  ].join("\n");
}

export function buildCloudRunTerraformGitignore(): string {
  return [
    `# ${DEPLOYMENT_HEADER}`,
    `# Local terraform state and provider cache for this game's deployment slot.`,
    `# Remote-backend opt-in is a follow-up epic (see Plan 045).`,
    `.terraform/`,
    `terraform.tfstate`,
    `terraform.tfstate.backup`,
    `*.tfstate.lock.info`,
    ``
  ].join("\n");
}
