/**
 * SugarDeploy GitHub Actions workflow generator.
 *
 * Emits `.github/workflows/sugardeploy-deploy.yml` as a managed file
 * when at least one hosted deployment target is configured (Cloud Run
 * on the backend, Netlify on the frontend, or both). The workflow has
 * two jobs that the project chooses to render or skip based on which
 * targets are present:
 *
 *   - `deploy-backend`: WIF auth to GCP, docker build + push to
 *     Artifact Registry, gcloud run deploy via the deploy.sh from
 *     Plan 045 (we DO NOT duplicate its body — the workflow just
 *     invokes it).
 *   - `deploy-frontend`: read the deployed gateway URL via
 *     `gcloud run services describe`, build targets/web with the
 *     resolved env, then `netlify deploy --site=<id> ... --prod`.
 *
 * Triggers: `push.tags: ['v*']` AND `workflow_dispatch` (with a `ref`
 * input so an operator can deploy a specific commit). Both hit the
 * same jobs.
 *
 * Drift discipline: every regeneration stamps the `# SUGARMAGIC
 * WORKFLOW TEMPLATE VERSION: NN` line. The Studio probes that stamp on
 * mount; if the on-disk value is older than the current generator's
 * version, the Provision workspace shows a drift banner so the user
 * knows to save (or run Setup GitHub Workflow once 46.8 lands).
 *
 * Implements: Plan 046 story 46.7.
 */

import type { GameProject } from "@sugarmagic/domain";
import type { DeploymentPlan, ManagedProjectFile } from "./index";
import { normalizeGoogleCloudRunDeploymentTargetOverrides } from "./overrides";
import { normalizeNetlifyDeploymentTargetOverrides } from "./netlify";

/**
 * Template version stamped into every generated workflow YAML. Bump
 * whenever the YAML shape changes (new step, renamed job, different
 * trigger) and append an entry to `WORKFLOW_RENAME_LEDGER`. Drift
 * detection on the Studio side compares the on-disk stamp against
 * this constant.
 */
// Story 46.15 — bumped 4 → 5: deploy-backend job's env now carries
// non-secret runtime config keys declared by plugins (vector store
// id, model identifiers, target language). They flow through
// deploy.sh's --set-env-vars to Cloud Run alongside the existing
// SUGARMAGIC_ALLOWED_ORIGINS. Earlier history: v1 two-job workflow;
// v2 env-var injection so deploy.sh skips terraform on the runner;
// v3 dropped auth@v2 service_account: impersonation; v4 frontend
// job became thin checkout-and-netlify-deploy off the pre-baked
// .sugarmagic/published-web/ directory.
export const SUGARDEPLOY_WORKFLOW_TEMPLATE_VERSION = 5;

const WORKFLOW_HEADER = "GENERATED BY SUGARMAGIC - DO NOT EDIT";
const WORKFLOW_TEMPLATE_VERSION_STAMP_PREFIX =
  "# SUGARMAGIC WORKFLOW TEMPLATE VERSION:";

/**
 * Pure parser for the workflow stamp at the top of
 * `.github/workflows/sugardeploy-deploy.yml`. Returns null when the
 * stamp is missing — either the file isn't generated yet, or someone
 * hand-edited the header off. The Studio side calls this through a
 * host endpoint and surfaces the drift banner accordingly.
 */
export function parseWorkflowTemplateVersionStamp(
  workflowYamlContent: string | null
): number | null {
  if (!workflowYamlContent) return null;
  const match = workflowYamlContent.match(
    /^#\s*SUGARMAGIC WORKFLOW TEMPLATE VERSION:\s*(\d+)/m
  );
  if (!match) return null;
  const parsed = Number.parseInt(match[1], 10);
  return Number.isFinite(parsed) && parsed >= 1 ? parsed : null;
}

export interface WorkflowRenameMove {
  from: string;
  to: string;
}

export interface WorkflowRenameEntry {
  fromVersion: number;
  toVersion: number;
  moves: WorkflowRenameMove[];
}

/**
 * Empty for v1. Future bumps append entries here whenever a job/step
 * id rename happens, so the regeneration path can leave an audit
 * trail when an existing workflow is upgraded in place.
 */
export const WORKFLOW_RENAME_LEDGER: WorkflowRenameEntry[] = [];

const WORKFLOW_PATH = ".github/workflows/sugardeploy-deploy.yml";

interface BuildWorkflowInputs {
  /**
   * Cloud Run configured on the plan? Determines whether the
   * deploy-backend job appears.
   */
  hasBackend: boolean;
  /**
   * Netlify configured on the plan? Determines whether the
   * deploy-frontend job appears.
   */
  hasFrontend: boolean;
  /**
   * Story 46.15 — non-secret runtime config env keys + values to
   * inject into the deploy-backend job's env block so deploy.sh
   * sees them as process env and forwards via --set-env-vars to
   * Cloud Run. Keys whose value is empty are skipped at YAML-gen
   * time so the workflow doesn't carry obvious-empty stanzas.
   */
  runtimeConfigEnv: Record<string, string>;
  /** Sequential build inputs the YAML interpolates. */
  workflowName: string;
  projectId: string;
  region: string;
  serviceNamePrefix: string;
  gatewayServiceName: string;
  gatewayAuthMode: "none" | "bearer";
  majorVersion: number;
  versionedSlug: string;
  gameProjectSlug: string;
  netlifySiteId: string;
  netlifyProductionContext: "production" | "deploy-preview" | "branch-deploy";
  // Story 46.10 — values deploy.sh would normally read from
  // `terraform output -json`; injected into the workflow because GHA
  // runners don't have terraform state available. The plan + project
  // know all of them at workflow-gen time:
  //   - artifactRegistryUrl = "<region>-docker.pkg.dev/<projectId>/<serviceNamePrefix>"
  //   - allowedOriginsCsv = comma-joined deriveGatewayAllowedOrigins
  //   (runtime SA email already lives in vars.SUGARMAGIC_RUNTIME_SA_EMAIL)
  artifactRegistryUrl: string;
  allowedOriginsCsv: string;
}

function buildHeader(workflowName: string): string[] {
  return [
    `# ${WORKFLOW_HEADER}`,
    `${WORKFLOW_TEMPLATE_VERSION_STAMP_PREFIX} ${SUGARDEPLOY_WORKFLOW_TEMPLATE_VERSION}`,
    "",
    `name: ${workflowName}`
  ];
}

function buildTriggers(): string[] {
  return [
    "on:",
    "  push:",
    "    tags:",
    "      - 'v*'",
    "  workflow_dispatch:",
    "    inputs:",
    "      ref:",
    "        description: 'Git ref (branch / tag / sha) to deploy. Defaults to the workflow_dispatch ref.'",
    "        required: false",
    "        default: ''"
  ];
}

function buildPermissions(): string[] {
  return [
    "permissions:",
    "  contents: read",
    "  id-token: write"
  ];
}

function buildBackendJob(inputs: BuildWorkflowInputs): string[] {
  const {
    projectId,
    region,
    serviceNamePrefix,
    artifactRegistryUrl,
    allowedOriginsCsv,
    runtimeConfigEnv
  } = inputs;
  const runtimeConfigLines = Object.keys(runtimeConfigEnv)
    .sort()
    .filter((key) => runtimeConfigEnv[key].length > 0)
    .map((key) => `          ${key}: ${JSON.stringify(runtimeConfigEnv[key])}`);
  return [
    "  deploy-backend:",
    "    name: Deploy backend to Cloud Run",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - name: Checkout",
    "        uses: actions/checkout@v4",
    "        with:",
    "          ref: ${{ github.event.inputs.ref || github.ref }}",
    "      - name: Authenticate to GCP via WIF",
    "        uses: google-github-actions/auth@v2",
    "        with:",
    "          workload_identity_provider: ${{ vars.SUGARMAGIC_WIF_PROVIDER }}",
    // Story 46.10 — NO `service_account:` here. With it set, auth@v2
    // impersonates the runtime SA for ALL subsequent gcloud/docker
    // calls — including the docker push to Artifact Registry, which
    // the runtime SA isn't permissioned for (and shouldn't be — it's
    // the runtime identity, not a deploy identity). Leaving it off
    // keeps the WIF principal as the active identity for build+push
    // (it has `artifactregistry.writer` + `run.admin`); the runtime
    // SA is attached to the Cloud Run service via the
    // `gcloud run deploy --service-account=...` flag in deploy.sh,
    // which works because the WIF principal has `serviceAccountUser`
    // on the runtime SA.
    "      - name: Set up gcloud",
    "        uses: google-github-actions/setup-gcloud@v2",
    "      - name: Configure docker for Artifact Registry",
    `        run: gcloud auth configure-docker ${region}-docker.pkg.dev --quiet`,
    "      - name: Run deploy.sh",
    "        working-directory: deployment/google-cloud-run",
    "        env:",
    `          SUGARMAGIC_GCP_PROJECT_ID: ${projectId}`,
    `          SUGARMAGIC_GCP_REGION: ${region}`,
    `          SUGARMAGIC_SERVICE_NAME_PREFIX: ${serviceNamePrefix}`,
    // Story 46.10 — deploy.sh prefers these env vars over terraform
    // when they're set. Avoids needing terraform installed on the
    // GHA runner (and avoids the state-not-on-runner problem).
    "          SUGARMAGIC_RUNTIME_SA_EMAIL: ${{ vars.SUGARMAGIC_RUNTIME_SA_EMAIL }}",
    `          SUGARMAGIC_ARTIFACT_REGISTRY_URL: ${artifactRegistryUrl}`,
    `          SUGARMAGIC_ALLOWED_ORIGINS: ${JSON.stringify(allowedOriginsCsv)}`,
    ...runtimeConfigLines,
    "        run: bash deploy.sh"
  ];
}

function buildFrontendJob(inputs: BuildWorkflowInputs): string[] {
  const { hasBackend, netlifySiteId, netlifyProductionContext } = inputs;
  const deployFlags =
    netlifyProductionContext === "deploy-preview"
      ? "--alias=preview"
      : netlifyProductionContext === "branch-deploy"
        ? "--alias=branch"
        : "--prod";
  // Story 46.10 follow-up — frontend job is now a thin
  // checkout-and-netlify-deploy. The `.sugarmagic/published-web/`
  // directory is pre-baked: `boot.json` regenerates on every
  // SugarDeploy save (managed file); `dist/` refreshes when the
  // Build Frontend button is clicked in Provision (multi-second
  // vite build, intentionally out-of-band of save). Both files live
  // in the wordlark repo; the workflow just hands the directory to
  // netlify-cli. No engine clone / pnpm install / vite build
  // happens on the runner.
  const job: string[] = [
    "  deploy-frontend:",
    "    name: Deploy frontend to Netlify",
    "    runs-on: ubuntu-latest"
  ];
  if (hasBackend) {
    // When the backend job is in this workflow, gate frontend on it
    // so a backend-deploy failure aborts the frontend deploy too.
    job.push("    needs: deploy-backend");
  }
  job.push(
    "    steps:",
    "      - name: Checkout",
    "        uses: actions/checkout@v4",
    "        with:",
    "          ref: ${{ github.event.inputs.ref || github.ref }}",
    "      - name: Verify pre-baked frontend bundle exists",
    "        run: |",
    "          if [ ! -f .sugarmagic/published-web/boot.json ]; then",
    "            echo \"::error::.sugarmagic/published-web/boot.json missing — re-save the project in Studio and commit before re-dispatching.\"",
    "            exit 1",
    "          fi",
    "          if [ ! -d .sugarmagic/published-web/dist ]; then",
    "            echo \"::error::.sugarmagic/published-web/dist missing — click Build Frontend in Provision and commit before re-dispatching.\"",
    "            exit 1",
    "          fi",
    "      - name: Stage boot.json next to the bundle",
    "        run: cp .sugarmagic/published-web/boot.json .sugarmagic/published-web/dist/boot.json",
    "      - name: Deploy to Netlify",
    "        env:",
    "          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}",
    `          NETLIFY_SITE_ID: ${netlifySiteId}`,
    "        run: |",
    `          npx -y netlify-cli@17 deploy --site="$NETLIFY_SITE_ID" --dir=.sugarmagic/published-web/dist --message="SugarDeploy $GITHUB_REF_NAME" ${deployFlags}`
  );
  return job;
}

function buildWorkflowYaml(inputs: BuildWorkflowInputs): string {
  const lines: string[] = [];
  lines.push(...buildHeader(inputs.workflowName));
  lines.push("");
  lines.push(...buildTriggers());
  lines.push("");
  lines.push(...buildPermissions());
  lines.push("");
  lines.push("jobs:");
  if (inputs.hasBackend) {
    lines.push(...buildBackendJob(inputs));
  }
  if (inputs.hasFrontend) {
    if (inputs.hasBackend) lines.push("");
    lines.push(...buildFrontendJob(inputs));
  }
  // Trailing newline (POSIX text-file convention; matches the other generated files).
  return `${lines.join("\n")}\n`;
}

/**
 * Decide whether the workflow should be generated for this plan.
 * Local-only backend doesn't need it (docker-compose runs on the dev
 * machine), and a project with no hosted target at all is the same
 * story. The frontend (Netlify) alone IS enough to warrant the
 * workflow — the frontend job stands on its own.
 */
export function planNeedsGithubWorkflow(plan: DeploymentPlan): boolean {
  const hasBackend = plan.backendDeploymentTargetId === "google-cloud-run";
  const hasFrontend = plan.frontendDeploymentTargetId === "netlify";
  return hasBackend || hasFrontend;
}

export function buildSugarDeployGithubWorkflowFile(
  plan: DeploymentPlan,
  gameProject: GameProject,
  // Story 46.10 — caller (planGameDeployment) already runs
  // deriveGatewayAllowedOrigins for the terraform tfvars + env-var
  // injection; pass it through so the workflow can inject the same
  // comma-joined list directly into deploy.sh as
  // SUGARMAGIC_ALLOWED_ORIGINS. Avoids a circular import with index.ts.
  allowedOrigins: string[] = [],
  // Story 46.15 — non-secret runtime config env vars (vector store
  // id, model identifiers, target language) the gateway needs at
  // request time. Resolved by Studio's host endpoint from the
  // sugarmagic-root .env at save time and passed through here.
  runtimeConfigEnv: Record<string, string> = {}
): ManagedProjectFile | null {
  if (!planNeedsGithubWorkflow(plan)) return null;

  const hasBackend = plan.backendDeploymentTargetId === "google-cloud-run";
  const hasFrontend = plan.frontendDeploymentTargetId === "netlify";

  const cloudRunOverrides = hasBackend
    ? normalizeGoogleCloudRunDeploymentTargetOverrides(
        plan.targetOverrides,
        gameProject
      )
    : null;
  const netlifyOverrides = hasFrontend
    ? normalizeNetlifyDeploymentTargetOverrides(plan.frontendTargetOverrides)
    : null;

  const gameProjectSlug = gameProject.identity.id || "sugarmagic-game";
  // Cloud Run resource names use the serviceNamePrefix; the gateway
  // service unit is always `sugarmagic-gateway` (Plan 045's baseline).
  const gatewayServiceName = cloudRunOverrides
    ? `${cloudRunOverrides.serviceNamePrefix}-sugarmagic-gateway`
    : "sugarmagic-gateway";

  const region = cloudRunOverrides?.region ?? "us-central1";
  const projectId = cloudRunOverrides?.projectId ?? "";
  const serviceNamePrefix =
    cloudRunOverrides?.serviceNamePrefix ?? gameProjectSlug;
  // Same formula as terraform's outputs.tf `artifact_registry_url`:
  // ${region}-docker.pkg.dev/${projectId}/${repository_id}
  // where repository_id == var.service_name_prefix.
  const artifactRegistryUrl = projectId
    ? `${region}-docker.pkg.dev/${projectId}/${serviceNamePrefix}`
    : "";

  const inputs: BuildWorkflowInputs = {
    hasBackend,
    hasFrontend,
    workflowName: `SugarDeploy — ${gameProjectSlug} v${gameProject.majorVersion}`,
    projectId,
    region,
    serviceNamePrefix,
    gatewayServiceName,
    gatewayAuthMode: cloudRunOverrides?.gatewayAuthMode ?? "none",
    majorVersion: gameProject.majorVersion,
    versionedSlug: serviceNamePrefix,
    gameProjectSlug,
    netlifySiteId: netlifyOverrides?.siteId ?? "",
    netlifyProductionContext:
      netlifyOverrides?.productionContext ?? "production",
    artifactRegistryUrl,
    allowedOriginsCsv: allowedOrigins.join(","),
    runtimeConfigEnv
  };

  return {
    relativePath: WORKFLOW_PATH,
    content: buildWorkflowYaml(inputs),
    contentType: "text"
  };
}

export function getSugarDeployGithubWorkflowPath(): string {
  return WORKFLOW_PATH;
}
