/**
 * SugarDeploy GitHub Actions workflow generator.
 *
 * Emits `.github/workflows/sugardeploy-deploy.yml` as a managed file
 * when at least one hosted deployment target is configured (Cloud Run
 * on the backend, Netlify on the frontend, or both). The workflow has
 * two jobs that the project chooses to render or skip based on which
 * targets are present:
 *
 *   - `deploy-backend`: WIF auth to GCP, docker build + push to
 *     Artifact Registry, gcloud run deploy via the deploy.sh from
 *     Plan 045 (we DO NOT duplicate its body — the workflow just
 *     invokes it).
 *   - `deploy-frontend`: read the deployed gateway URL via
 *     `gcloud run services describe`, build targets/web with the
 *     resolved env, then `netlify deploy --site=<id> ... --prod`.
 *
 * Triggers: `push.tags: ['v*']` AND `workflow_dispatch` (with a `ref`
 * input so an operator can deploy a specific commit). Both hit the
 * same jobs.
 *
 * Drift discipline: every regeneration stamps the `# SUGARMAGIC
 * WORKFLOW TEMPLATE VERSION: NN` line. The Studio probes that stamp on
 * mount; if the on-disk value is older than the current generator's
 * version, the Provision workspace shows a drift banner so the user
 * knows to save (or run Setup GitHub Workflow once 46.8 lands).
 *
 * Implements: Plan 046 story 46.7.
 */

import type { GameProject } from "@sugarmagic/domain";
import type { DeploymentPlan, ManagedProjectFile } from "./index";
import { normalizeGoogleCloudRunDeploymentTargetOverrides } from "./overrides";
import { normalizeNetlifyDeploymentTargetOverrides } from "./netlify";

/**
 * Template version stamped into every generated workflow YAML. Bump
 * whenever the YAML shape changes (new step, renamed job, different
 * trigger) and append an entry to `WORKFLOW_RENAME_LEDGER`. Drift
 * detection on the Studio side compares the on-disk stamp against
 * this constant.
 */
export const SUGARDEPLOY_WORKFLOW_TEMPLATE_VERSION = 1;

const WORKFLOW_HEADER = "GENERATED BY SUGARMAGIC - DO NOT EDIT";
const WORKFLOW_TEMPLATE_VERSION_STAMP_PREFIX =
  "# SUGARMAGIC WORKFLOW TEMPLATE VERSION:";

/**
 * Pure parser for the workflow stamp at the top of
 * `.github/workflows/sugardeploy-deploy.yml`. Returns null when the
 * stamp is missing — either the file isn't generated yet, or someone
 * hand-edited the header off. The Studio side calls this through a
 * host endpoint and surfaces the drift banner accordingly.
 */
export function parseWorkflowTemplateVersionStamp(
  workflowYamlContent: string | null
): number | null {
  if (!workflowYamlContent) return null;
  const match = workflowYamlContent.match(
    /^#\s*SUGARMAGIC WORKFLOW TEMPLATE VERSION:\s*(\d+)/m
  );
  if (!match) return null;
  const parsed = Number.parseInt(match[1], 10);
  return Number.isFinite(parsed) && parsed >= 1 ? parsed : null;
}

export interface WorkflowRenameMove {
  from: string;
  to: string;
}

export interface WorkflowRenameEntry {
  fromVersion: number;
  toVersion: number;
  moves: WorkflowRenameMove[];
}

/**
 * Empty for v1. Future bumps append entries here whenever a job/step
 * id rename happens, so the regeneration path can leave an audit
 * trail when an existing workflow is upgraded in place.
 */
export const WORKFLOW_RENAME_LEDGER: WorkflowRenameEntry[] = [];

const WORKFLOW_PATH = ".github/workflows/sugardeploy-deploy.yml";

interface BuildWorkflowInputs {
  /**
   * Cloud Run configured on the plan? Determines whether the
   * deploy-backend job appears.
   */
  hasBackend: boolean;
  /**
   * Netlify configured on the plan? Determines whether the
   * deploy-frontend job appears.
   */
  hasFrontend: boolean;
  /** Sequential build inputs the YAML interpolates. */
  workflowName: string;
  projectId: string;
  region: string;
  serviceNamePrefix: string;
  gatewayServiceName: string;
  gatewayAuthMode: "none" | "bearer";
  majorVersion: number;
  versionedSlug: string;
  gameProjectSlug: string;
  netlifySiteId: string;
  netlifyProductionContext: "production" | "deploy-preview" | "branch-deploy";
}

function buildHeader(workflowName: string): string[] {
  return [
    `# ${WORKFLOW_HEADER}`,
    `${WORKFLOW_TEMPLATE_VERSION_STAMP_PREFIX} ${SUGARDEPLOY_WORKFLOW_TEMPLATE_VERSION}`,
    "",
    `name: ${workflowName}`
  ];
}

function buildTriggers(): string[] {
  return [
    "on:",
    "  push:",
    "    tags:",
    "      - 'v*'",
    "  workflow_dispatch:",
    "    inputs:",
    "      ref:",
    "        description: 'Git ref (branch / tag / sha) to deploy. Defaults to the workflow_dispatch ref.'",
    "        required: false",
    "        default: ''"
  ];
}

function buildPermissions(): string[] {
  return [
    "permissions:",
    "  contents: read",
    "  id-token: write"
  ];
}

function buildBackendJob(inputs: BuildWorkflowInputs): string[] {
  const { projectId, region, serviceNamePrefix } = inputs;
  return [
    "  deploy-backend:",
    "    name: Deploy backend to Cloud Run",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - name: Checkout",
    "        uses: actions/checkout@v4",
    "        with:",
    "          ref: ${{ github.event.inputs.ref || github.ref }}",
    "      - name: Authenticate to GCP via WIF",
    "        uses: google-github-actions/auth@v2",
    "        with:",
    "          workload_identity_provider: ${{ vars.SUGARMAGIC_WIF_PROVIDER }}",
    "          service_account: ${{ vars.SUGARMAGIC_RUNTIME_SA_EMAIL }}",
    "      - name: Set up gcloud",
    "        uses: google-github-actions/setup-gcloud@v2",
    "      - name: Configure docker for Artifact Registry",
    `        run: gcloud auth configure-docker ${region}-docker.pkg.dev --quiet`,
    "      - name: Run deploy.sh",
    "        working-directory: deployment/google-cloud-run",
    "        env:",
    `          SUGARMAGIC_GCP_PROJECT_ID: ${projectId}`,
    `          SUGARMAGIC_GCP_REGION: ${region}`,
    `          SUGARMAGIC_SERVICE_NAME_PREFIX: ${serviceNamePrefix}`,
    "        run: bash deploy.sh"
  ];
}

function buildFrontendJob(inputs: BuildWorkflowInputs): string[] {
  const {
    hasBackend,
    projectId,
    region,
    gatewayServiceName,
    gatewayAuthMode,
    majorVersion,
    versionedSlug,
    netlifySiteId,
    netlifyProductionContext
  } = inputs;
  const deployFlags =
    netlifyProductionContext === "deploy-preview"
      ? "--alias=preview"
      : netlifyProductionContext === "branch-deploy"
        ? "--alias=branch"
        : "--prod";
  const job: string[] = [
    "  deploy-frontend:",
    "    name: Deploy frontend to Netlify",
    "    runs-on: ubuntu-latest"
  ];
  if (hasBackend) {
    // Backend goes first so the frontend can read the freshly-deployed
    // gateway URL. If there's no backend job in this workflow the
    // frontend still runs; it just falls back to vars.SUGARMAGIC_GATEWAY_URL.
    job.push("    needs: deploy-backend");
  }
  job.push(
    "    steps:",
    "      - name: Checkout",
    "        uses: actions/checkout@v4",
    "        with:",
    "          ref: ${{ github.event.inputs.ref || github.ref }}"
  );
  if (hasBackend) {
    job.push(
      "      - name: Authenticate to GCP via WIF",
      "        uses: google-github-actions/auth@v2",
      "        with:",
      "          workload_identity_provider: ${{ vars.SUGARMAGIC_WIF_PROVIDER }}",
      "          service_account: ${{ vars.SUGARMAGIC_RUNTIME_SA_EMAIL }}",
      "      - name: Set up gcloud",
      "        uses: google-github-actions/setup-gcloud@v2",
      "      - name: Resolve gateway URL from Cloud Run",
      "        id: gateway",
      `        run: |`,
      `          URL=$(gcloud run services describe ${gatewayServiceName} --project=${projectId} --region=${region} --format='value(status.url)')`,
      `          echo "url=$URL" >> "$GITHUB_OUTPUT"`
    );
  }
  job.push(
    "      - name: Set up pnpm",
    "        uses: pnpm/action-setup@v3",
    "        with:",
    "          version: 9",
    "      - name: Set up Node",
    "        uses: actions/setup-node@v4",
    "        with:",
    "          node-version: 22",
    "          cache: pnpm",
    "      - name: Install dependencies",
    "        run: pnpm install --frozen-lockfile",
    "      - name: Build @sugarmagic/target-web",
    "        env:",
    hasBackend
      ? "          SUGARMAGIC_GATEWAY_URL: ${{ steps.gateway.outputs.url }}"
      : "          SUGARMAGIC_GATEWAY_URL: ${{ vars.SUGARMAGIC_GATEWAY_URL }}"
  );
  if (gatewayAuthMode === "bearer") {
    job.push(
      "          SUGARMAGIC_GATEWAY_BEARER_TOKEN: ${{ secrets.SUGARMAGIC_GATEWAY_BEARER_TOKEN }}"
    );
  }
  job.push(
    `          SUGARMAGIC_MAJOR_VERSION: "${majorVersion}"`,
    `          SUGARMAGIC_VERSIONED_SLUG: ${versionedSlug}`,
    "          SUGARMAGIC_GIT_SHA: ${{ github.sha }}",
    "        run: pnpm --filter @sugarmagic/target-web build",
    "      - name: Deploy to Netlify",
    "        env:",
    "          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}",
    `          NETLIFY_SITE_ID: ${netlifySiteId}`,
    "        run: |",
    `          npx -y netlify-cli@17 deploy --site="$NETLIFY_SITE_ID" --dir=targets/web/dist --message="SugarDeploy $GITHUB_REF_NAME" ${deployFlags}`
  );
  return job;
}

function buildWorkflowYaml(inputs: BuildWorkflowInputs): string {
  const lines: string[] = [];
  lines.push(...buildHeader(inputs.workflowName));
  lines.push("");
  lines.push(...buildTriggers());
  lines.push("");
  lines.push(...buildPermissions());
  lines.push("");
  lines.push("jobs:");
  if (inputs.hasBackend) {
    lines.push(...buildBackendJob(inputs));
  }
  if (inputs.hasFrontend) {
    if (inputs.hasBackend) lines.push("");
    lines.push(...buildFrontendJob(inputs));
  }
  // Trailing newline (POSIX text-file convention; matches the other generated files).
  return `${lines.join("\n")}\n`;
}

/**
 * Decide whether the workflow should be generated for this plan.
 * Local-only backend doesn't need it (docker-compose runs on the dev
 * machine), and a project with no hosted target at all is the same
 * story. The frontend (Netlify) alone IS enough to warrant the
 * workflow — the frontend job stands on its own.
 */
export function planNeedsGithubWorkflow(plan: DeploymentPlan): boolean {
  const hasBackend = plan.backendDeploymentTargetId === "google-cloud-run";
  const hasFrontend = plan.frontendDeploymentTargetId === "netlify";
  return hasBackend || hasFrontend;
}

export function buildSugarDeployGithubWorkflowFile(
  plan: DeploymentPlan,
  gameProject: GameProject
): ManagedProjectFile | null {
  if (!planNeedsGithubWorkflow(plan)) return null;

  const hasBackend = plan.backendDeploymentTargetId === "google-cloud-run";
  const hasFrontend = plan.frontendDeploymentTargetId === "netlify";

  const cloudRunOverrides = hasBackend
    ? normalizeGoogleCloudRunDeploymentTargetOverrides(
        plan.targetOverrides,
        gameProject
      )
    : null;
  const netlifyOverrides = hasFrontend
    ? normalizeNetlifyDeploymentTargetOverrides(plan.frontendTargetOverrides)
    : null;

  const gameProjectSlug = gameProject.identity.id || "sugarmagic-game";
  // Cloud Run resource names use the serviceNamePrefix; the gateway
  // service unit is always `sugarmagic-gateway` (Plan 045's baseline).
  const gatewayServiceName = cloudRunOverrides
    ? `${cloudRunOverrides.serviceNamePrefix}-sugarmagic-gateway`
    : "sugarmagic-gateway";

  const inputs: BuildWorkflowInputs = {
    hasBackend,
    hasFrontend,
    workflowName: `SugarDeploy — ${gameProjectSlug} v${gameProject.majorVersion}`,
    projectId: cloudRunOverrides?.projectId ?? "",
    region: cloudRunOverrides?.region ?? "us-central1",
    serviceNamePrefix: cloudRunOverrides?.serviceNamePrefix ?? gameProjectSlug,
    gatewayServiceName,
    gatewayAuthMode: cloudRunOverrides?.gatewayAuthMode ?? "none",
    majorVersion: gameProject.majorVersion,
    versionedSlug: cloudRunOverrides?.serviceNamePrefix ?? gameProjectSlug,
    gameProjectSlug,
    netlifySiteId: netlifyOverrides?.siteId ?? "",
    netlifyProductionContext: netlifyOverrides?.productionContext ?? "production"
  };

  return {
    relativePath: WORKFLOW_PATH,
    content: buildWorkflowYaml(inputs),
    contentType: "text"
  };
}

export function getSugarDeployGithubWorkflowPath(): string {
  return WORKFLOW_PATH;
}
