/**
 * Netlify frontend deployment generators.
 *
 * Emits the managed files SugarDeploy lays down under
 * `deployment/netlify/` when `frontendDeploymentTargetId` is set to
 * `"netlify"`:
 *
 *   - `netlify.toml` — Netlify build config (publish dir + SPA
 *     redirect)
 *   - `build-config.json` — non-secret build inputs consumed by the
 *     GHA deploy workflow (story 46.7+)
 *   - `README.md` — what's here + what's NOT (secrets live elsewhere)
 *
 * Every generated file carries the `# GENERATED BY SUGARMAGIC` header
 * and the `# SUGARMAGIC FRONTEND TEMPLATE VERSION: NN` stamp so future
 * regenerations can detect drift the same way Cloud Run terraform does
 * (parallel to CLOUD_RUN_TEMPLATE_VERSION).
 */

import type { GameProject } from "@sugarmagic/domain";
import type { DeploymentPlan, ManagedProjectFile } from "./index";

/**
 * Template version stamped into every Netlify managed file. Bump
 * whenever any generated file's shape changes and append an entry to
 * `FRONTEND_RENAME_LEDGER` (parallel to terraform's rename ledger) so
 * existing games get a non-destructive upgrade path on regeneration.
 */
export const NETLIFY_TEMPLATE_VERSION = 1;

const FRONTEND_HEADER = "GENERATED BY SUGARMAGIC - DO NOT EDIT";
const FRONTEND_TEMPLATE_VERSION_STAMP_PREFIX =
  "# SUGARMAGIC FRONTEND TEMPLATE VERSION:";

const TOML_HEADER = [
  `# ${FRONTEND_HEADER}`,
  `${FRONTEND_TEMPLATE_VERSION_STAMP_PREFIX} ${NETLIFY_TEMPLATE_VERSION}`,
  ""
].join("\n");

export interface FrontendRenameMove {
  from: string;
  to: string;
}

export interface FrontendRenameEntry {
  fromVersion: number;
  toVersion: number;
  moves: FrontendRenameMove[];
}

/**
 * Empty for v1. Future bumps to NETLIFY_TEMPLATE_VERSION append entries
 * here when generated paths or resource names change, so the upgrade
 * path can leave a `moves: [{from, to}]` audit trail for projects
 * mid-migration.
 */
export const FRONTEND_RENAME_LEDGER: FrontendRenameEntry[] = [];

export type NetlifyProductionContext = "production" | "deploy-preview" | "branch-deploy";

export interface NetlifyDeploymentTargetOverrides {
  siteId: string;
  siteName: string;
  productionContext: NetlifyProductionContext;
}

// Netlify site IDs are typically UUIDs, but some legacy sites use
// shorter slugs. Loose validation: lowercase hex + dashes, 8+ chars.
// Empty string is allowed too (user hasn't filled it in yet) — the GHA
// workflow surfaces the actual error if it tries to deploy without it.
const NETLIFY_SITE_ID_REGEX = /^[a-f0-9-]{8,}$/i;

export function isValidNetlifySiteId(value: string): boolean {
  return value.length === 0 || NETLIFY_SITE_ID_REGEX.test(value.trim());
}

function asTrimmedString(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}

function normalizeProductionContext(value: unknown): NetlifyProductionContext {
  return value === "deploy-preview" || value === "branch-deploy"
    ? value
    : "production";
}

export function normalizeNetlifyDeploymentTargetOverrides(
  input: Record<string, unknown> | null | undefined
): NetlifyDeploymentTargetOverrides {
  const rawSiteId = asTrimmedString(input?.siteId);
  return {
    siteId: NETLIFY_SITE_ID_REGEX.test(rawSiteId) ? rawSiteId : "",
    siteName: asTrimmedString(input?.siteName),
    productionContext: normalizeProductionContext(input?.productionContext)
  };
}

function asTextFile(relativePath: string, content: string): ManagedProjectFile {
  return { relativePath, content, contentType: "text" };
}

function asJsonFile(
  relativePath: string,
  payload: Record<string, unknown>
): ManagedProjectFile {
  return {
    relativePath,
    content: `${JSON.stringify(payload, null, 2)}\n`,
    contentType: "json"
  };
}

function buildNetlifyToml(): string {
  const buildCommand = "pnpm --filter @sugarmagic/target-web build";
  const publishDir = "targets/web/dist";
  const body = [
    "[build]",
    `  command = "${buildCommand}"`,
    `  publish = "${publishDir}"`,
    "",
    "[context.production]",
    `  command = "${buildCommand}"`,
    "",
    "[[redirects]]",
    '  from = "/*"',
    '  to = "/index.html"',
    "  status = 200",
    ""
  ].join("\n");
  return `${TOML_HEADER}\n${body}`;
}

function buildReadme(args: {
  gameProjectSlug: string;
  majorVersion: number;
  overrides: NetlifyDeploymentTargetOverrides;
}): string {
  const { gameProjectSlug, majorVersion, overrides } = args;
  const site = overrides.siteId
    ? `\`${overrides.siteName || overrides.siteId}\``
    : "_(not configured — set siteId in the Netlify target settings)_";
  return [
    `# ${FRONTEND_HEADER}`,
    `${FRONTEND_TEMPLATE_VERSION_STAMP_PREFIX} ${NETLIFY_TEMPLATE_VERSION}`,
    "",
    `# Netlify deployment for ${gameProjectSlug} (v${majorVersion})`,
    "",
    `Target site: ${site}`,
    "",
    "## What's generated",
    "",
    "- `netlify.toml` — Netlify build config (publish dir + SPA redirects).",
    "- `build-config.json` — non-secret build inputs the GHA deploy workflow reads at deploy time.",
    "- `README.md` — this file.",
    "",
    "## What's NOT generated here",
    "",
    "- Gateway bearer token. Supplied at build time from GitHub Secrets by the deploy workflow (story 46.7+).",
    "- `.netlify/` link directory. `netlify link --id <siteId>` runs from CI.",
    "",
    "## Manual fix-up",
    "",
    "If you're deploying by hand without the GHA workflow:",
    "",
    "```sh",
    `pnpm --filter @sugarmagic/target-web build`,
    `netlify deploy --prod --dir=targets/web/dist`,
    "```",
    "",
    "Set `SUGARMAGIC_GATEWAY_URL` (and `SUGARMAGIC_GATEWAY_BEARER_TOKEN` when",
    "gatewayAuthMode is `bearer`) as build-time env in the Netlify site",
    "dashboard. The GHA workflow injects them automatically when wired up.",
    ""
  ].join("\n");
}

function buildBuildConfigJson(args: {
  plan: DeploymentPlan;
  gameProjectSlug: string;
  majorVersion: number;
  overrides: NetlifyDeploymentTargetOverrides;
}): Record<string, unknown> {
  const { plan, gameProjectSlug, majorVersion, overrides } = args;
  return {
    generator: "sugarmagic",
    note: FRONTEND_HEADER,
    templateVersion: NETLIFY_TEMPLATE_VERSION,
    publishTargetId: plan.publishTargetId,
    frontendDeploymentTargetId: plan.frontendDeploymentTargetId,
    backendDeploymentTargetId: plan.backendDeploymentTargetId,
    gameProjectSlug,
    majorVersion,
    build: {
      command: "pnpm --filter @sugarmagic/target-web build",
      publishDir: "targets/web/dist"
    },
    site: {
      siteId: overrides.siteId,
      siteName: overrides.siteName,
      productionContext: overrides.productionContext
    }
  };
}

export function buildNetlifyManagedFiles(
  plan: DeploymentPlan,
  gameProject: GameProject
): ManagedProjectFile[] {
  const overrides = normalizeNetlifyDeploymentTargetOverrides(
    plan.frontendTargetOverrides
  );
  const gameProjectSlug = gameProject.identity.id || "sugarmagic-game";
  const majorVersion = gameProject.majorVersion;
  return [
    asTextFile("deployment/netlify/netlify.toml", buildNetlifyToml()),
    asJsonFile(
      "deployment/netlify/build-config.json",
      buildBuildConfigJson({
        plan,
        gameProjectSlug,
        majorVersion,
        overrides
      })
    ),
    asTextFile(
      "deployment/netlify/README.md",
      buildReadme({ gameProjectSlug, majorVersion, overrides })
    )
  ];
}

export function collectNetlifyWarnings(plan: DeploymentPlan): string[] {
  const warnings: string[] = [];
  const overrides = normalizeNetlifyDeploymentTargetOverrides(
    plan.frontendTargetOverrides
  );
  if (overrides.siteId.length === 0) {
    warnings.push(
      "Netlify target is selected but no `siteId` override is set; the GHA deploy workflow will fail until a Netlify site id is filled in."
    );
  }
  return warnings;
}
