import type { GameProject } from "@sugarmagic/domain";

export interface LocalDeploymentTargetOverrides {
  workingDirectory: string;
  composeProjectName: string;
  gatewayHostPortBase: number;
}

export type GoogleCloudRunIngress =
  | "all"
  | "internal"
  | "internal-and-cloud-load-balancing";

export interface GoogleCloudRunDeploymentTargetOverrides {
  workingDirectory: string;
  projectId: string;
  region: string;
  serviceNamePrefix: string;
  containerPort: number;
  minInstances: number;
  maxInstances: number;
  ingress: GoogleCloudRunIngress;
  allowUnauthenticated: boolean;
  // Persisted exactly as `owner/repo` (matches GitHub OIDC `repository` claim).
  // Drives the Workload Identity Federation binding generated by terraform.
  // Empty string until the user fills it in via the SugarDeploy Cloud Run section.
  githubRepo: string;
  // Optional explicit name override for the runtime service account. When empty,
  // terraform derives `${serviceNamePrefix}-runtime`.
  runtimeServiceAccountName: string;
}

function slugify(input: string): string {
  const value = input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-+/g, "-");
  return value || "sugarmagic";
}

function clampInteger(
  value: unknown,
  fallback: number,
  options?: { min?: number; max?: number }
): number {
  const numeric =
    typeof value === "number"
      ? value
      : typeof value === "string" && value.trim().length > 0
        ? Number(value)
        : Number.NaN;
  if (!Number.isFinite(numeric)) {
    return fallback;
  }
  const floored = Math.floor(numeric);
  const min = options?.min ?? Number.MIN_SAFE_INTEGER;
  const max = options?.max ?? Number.MAX_SAFE_INTEGER;
  return Math.max(min, Math.min(max, floored));
}

function asNonEmptyString(value: unknown, fallback: string): string {
  return typeof value === "string" && value.trim().length > 0
    ? value.trim()
    : fallback;
}

// All derived identifiers (slug, GCP project id, service name prefix, secret
// container names, etc.) MUST flow from `identity.id`, which is the stable
// normalized slug assigned at project creation time. `displayName` is for UI
// display ONLY and can change without breaking cloud resource identity.
function defaultDeploymentSlug(gameProject: Pick<GameProject, "identity">): string {
  return slugify(gameProject.identity.id || "sugarmagic-game");
}

function resolveMajorVersion(
  gameProject: Pick<GameProject, "majorVersion"> | undefined
): number {
  const raw = gameProject?.majorVersion;
  return typeof raw === "number" && Number.isFinite(raw) && raw >= 1
    ? Math.floor(raw)
    : 1;
}

function defaultVersionedDeploymentSlug(
  gameProject: Pick<
    GameProject,
    "identity" | "majorVersion" | "versionedProjectIdentifiers"
  >
): string {
  const slug = defaultDeploymentSlug(gameProject);
  const major = resolveMajorVersion(gameProject);
  // Story 45.4.7 — collision-resistant suffix. When the project has a recorded
  // suffix for the current major version (set lazily by the SugarDeploy form
  // on first mount, or by Cut New Major Version per 45.8), include it in the
  // derivation: `${slug}-v${major}-${suffix}`. When absent — older project
  // files that haven't been opened in SugarDeploy yet, or non-Cloud-Run
  // targets — fall back to the pre-45.4.7 `${slug}-v${major}` form so
  // existing GCP projects remain reachable until the form mounts and
  // generates a suffix.
  const suffix = gameProject.versionedProjectIdentifiers?.[`v${major}`];
  return suffix ? `${slug}-v${major}-${suffix}` : `${slug}-v${major}`;
}

export function normalizeLocalDeploymentTargetOverrides(
  input: Record<string, unknown> | null | undefined,
  gameProject?: Pick<GameProject, "identity">
): LocalDeploymentTargetOverrides {
  const fallbackSlug = gameProject
    ? defaultDeploymentSlug(gameProject)
    : "sugarmagic-local";
  return {
    workingDirectory:
      typeof input?.workingDirectory === "string" ? input.workingDirectory.trim() : "",
    composeProjectName: slugify(
      asNonEmptyString(input?.composeProjectName, `${fallbackSlug}-local`)
    ),
    gatewayHostPortBase: clampInteger(input?.gatewayHostPortBase, 8787, {
      min: 1024,
      max: 65535
    })
  };
}

export function normalizeGoogleCloudRunDeploymentTargetOverrides(
  input: Record<string, unknown> | null | undefined,
  gameProject?: Pick<
    GameProject,
    "identity" | "majorVersion" | "versionedProjectIdentifiers"
  >
): GoogleCloudRunDeploymentTargetOverrides {
  const versionedSlug = gameProject
    ? defaultVersionedDeploymentSlug(gameProject)
    : `sugarmagic-v${resolveMajorVersion(gameProject)}`;
  const ingress =
    input?.ingress === "internal" ||
    input?.ingress === "internal-and-cloud-load-balancing" ||
    input?.ingress === "all"
      ? input.ingress
      : "all";
  return {
    workingDirectory:
      typeof input?.workingDirectory === "string" ? input.workingDirectory.trim() : "",
    projectId: slugify(asNonEmptyString(input?.projectId, versionedSlug)),
    region: asNonEmptyString(input?.region, "us-central1"),
    serviceNamePrefix: slugify(
      asNonEmptyString(input?.serviceNamePrefix, versionedSlug)
    ),
    containerPort: clampInteger(input?.containerPort, 8080, {
      min: 1024,
      max: 65535
    }),
    // Story 45.5 right-sized defaults: gateway is a thin HTTP proxy now that
    // LLM + vector DB are external, so `min-instances=1` keeps in-game dialog
    // snappy (no cold start) and `max-instances=4` matches the prior wordlark
    // shape that ran fine under real load. CPU throttling collapses the idle
    // bill; see deploy.sh for the cpu/memory/throttling bake-in.
    minInstances: clampInteger(input?.minInstances, 1, { min: 0, max: 100 }),
    maxInstances: clampInteger(input?.maxInstances, 4, { min: 1, max: 100 }),
    ingress,
    allowUnauthenticated: input?.allowUnauthenticated !== false,
    githubRepo: normalizeGithubRepoOverride(input?.githubRepo),
    runtimeServiceAccountName:
      typeof input?.runtimeServiceAccountName === "string"
        ? input.runtimeServiceAccountName.trim()
        : ""
  };
}

// Canonical GitHub `owner/repo` shape. Single source of truth used by both the
// override normalizer (for tfvars / persistence) and the Studio field (for
// inline validation feedback). GitHub OIDC's `repository` claim and terraform's
// `attribute.repository == "..."` condition both expect this exact form.
export const GITHUB_REPO_REGEX = /^[A-Za-z0-9._-]+\/[A-Za-z0-9._-]+$/;

// Paste-forgiveness for GitHub references: strip the prefix/suffix variants
// users commonly paste (browser URL, https clone URL, ssh clone URL) and return
// what's left. Validation is the caller's job — this is only the trim step.
// Single source of truth used by the override normalizer below AND by the
// Studio form field's onChange handler.
export function stripGithubRepoPrefixes(value: string): string {
  let trimmed = value.trim();
  trimmed = trimmed.replace(/^https?:\/\/github\.com\//i, "");
  trimmed = trimmed.replace(/^git@github\.com:/i, "");
  trimmed = trimmed.replace(/\.git$/i, "");
  return trimmed;
}

// Strip then validate as owner/repo. Empty / unparseable values become "" so
// terraform validate still passes against the un-filled-in state; the actual
// deploy-time requirement is enforced by the host action that runs
// `terraform apply`.
function normalizeGithubRepoOverride(value: unknown): string {
  if (typeof value !== "string") return "";
  const stripped = stripGithubRepoPrefixes(value);
  if (stripped.length === 0) return "";
  return GITHUB_REPO_REGEX.test(stripped) ? stripped : "";
}
