import type { GameProject } from "@sugarmagic/domain";

export interface LocalDeploymentTargetOverrides {
  workingDirectory: string;
  composeProjectName: string;
  gatewayHostPortBase: number;
}

export type GoogleCloudRunIngress =
  | "all"
  | "internal"
  | "internal-and-cloud-load-balancing";

export interface GoogleCloudRunDeploymentTargetOverrides {
  workingDirectory: string;
  projectId: string;
  region: string;
  serviceNamePrefix: string;
  containerPort: number;
  minInstances: number;
  maxInstances: number;
  ingress: GoogleCloudRunIngress;
  allowUnauthenticated: boolean;
  // Persisted exactly as `owner/repo` (matches GitHub OIDC `repository` claim).
  // Drives the Workload Identity Federation binding generated by terraform.
  // Empty string until the user fills it in via the SugarDeploy Cloud Run section.
  githubRepo: string;
  // Optional explicit name override for the runtime service account. When empty,
  // terraform derives `${serviceNamePrefix}-runtime`.
  runtimeServiceAccountName: string;
}

function slugify(input: string): string {
  const value = input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-+/g, "-");
  return value || "sugarmagic";
}

function clampInteger(
  value: unknown,
  fallback: number,
  options?: { min?: number; max?: number }
): number {
  const numeric =
    typeof value === "number"
      ? value
      : typeof value === "string" && value.trim().length > 0
        ? Number(value)
        : Number.NaN;
  if (!Number.isFinite(numeric)) {
    return fallback;
  }
  const floored = Math.floor(numeric);
  const min = options?.min ?? Number.MIN_SAFE_INTEGER;
  const max = options?.max ?? Number.MAX_SAFE_INTEGER;
  return Math.max(min, Math.min(max, floored));
}

function asNonEmptyString(value: unknown, fallback: string): string {
  return typeof value === "string" && value.trim().length > 0
    ? value.trim()
    : fallback;
}

// All derived identifiers (slug, GCP project id, service name prefix, secret
// container names, etc.) MUST flow from `identity.id`, which is the stable
// normalized slug assigned at project creation time. `displayName` is for UI
// display ONLY and can change without breaking cloud resource identity.
function defaultDeploymentSlug(gameProject: Pick<GameProject, "identity">): string {
  return slugify(gameProject.identity.id || "sugarmagic-game");
}

function resolveMajorVersion(
  gameProject: Pick<GameProject, "majorVersion"> | undefined
): number {
  const raw = gameProject?.majorVersion;
  return typeof raw === "number" && Number.isFinite(raw) && raw >= 1
    ? Math.floor(raw)
    : 1;
}

function defaultVersionedDeploymentSlug(
  gameProject: Pick<GameProject, "identity" | "majorVersion">
): string {
  return `${defaultDeploymentSlug(gameProject)}-v${resolveMajorVersion(gameProject)}`;
}

export function normalizeLocalDeploymentTargetOverrides(
  input: Record<string, unknown> | null | undefined,
  gameProject?: Pick<GameProject, "identity">
): LocalDeploymentTargetOverrides {
  const fallbackSlug = gameProject
    ? defaultDeploymentSlug(gameProject)
    : "sugarmagic-local";
  return {
    workingDirectory:
      typeof input?.workingDirectory === "string" ? input.workingDirectory.trim() : "",
    composeProjectName: slugify(
      asNonEmptyString(input?.composeProjectName, `${fallbackSlug}-local`)
    ),
    gatewayHostPortBase: clampInteger(input?.gatewayHostPortBase, 8787, {
      min: 1024,
      max: 65535
    })
  };
}

export function normalizeGoogleCloudRunDeploymentTargetOverrides(
  input: Record<string, unknown> | null | undefined,
  gameProject?: Pick<GameProject, "identity" | "majorVersion">
): GoogleCloudRunDeploymentTargetOverrides {
  const versionedSlug = gameProject
    ? defaultVersionedDeploymentSlug(gameProject)
    : `sugarmagic-v${resolveMajorVersion(gameProject)}`;
  const ingress =
    input?.ingress === "internal" ||
    input?.ingress === "internal-and-cloud-load-balancing" ||
    input?.ingress === "all"
      ? input.ingress
      : "all";
  return {
    workingDirectory:
      typeof input?.workingDirectory === "string" ? input.workingDirectory.trim() : "",
    projectId: slugify(asNonEmptyString(input?.projectId, versionedSlug)),
    region: asNonEmptyString(input?.region, "us-central1"),
    serviceNamePrefix: slugify(
      asNonEmptyString(input?.serviceNamePrefix, versionedSlug)
    ),
    containerPort: clampInteger(input?.containerPort, 8080, {
      min: 1024,
      max: 65535
    }),
    minInstances: clampInteger(input?.minInstances, 0, { min: 0, max: 100 }),
    maxInstances: clampInteger(input?.maxInstances, 2, { min: 1, max: 100 }),
    ingress,
    allowUnauthenticated: input?.allowUnauthenticated !== false,
    githubRepo: normalizeGithubRepoOverride(input?.githubRepo),
    runtimeServiceAccountName:
      typeof input?.runtimeServiceAccountName === "string"
        ? input.runtimeServiceAccountName.trim()
        : ""
  };
}

// Strip common paste forms (https://github.com/, git@github.com:, trailing .git)
// then validate as owner/repo. Empty / unparseable values become "" so terraform
// validate still passes against the un-filled-in state; the actual deploy-time
// requirement is enforced by the host action that runs `terraform apply`.
function normalizeGithubRepoOverride(value: unknown): string {
  if (typeof value !== "string") return "";
  let trimmed = value.trim();
  if (trimmed.length === 0) return "";
  trimmed = trimmed.replace(/^https?:\/\/github\.com\//i, "");
  trimmed = trimmed.replace(/^git@github\.com:/i, "");
  trimmed = trimmed.replace(/\.git$/i, "");
  return /^[A-Za-z0-9._-]+\/[A-Za-z0-9._-]+$/.test(trimmed) ? trimmed : "";
}
