import type { GameProject } from "@sugarmagic/domain";

import {
  getDeploymentSettings,
  getVersionedProjectIdentifiers,
  type DeployStateInput
} from "./plugin-state";

export interface LocalDeploymentTargetOverrides {
  workingDirectory: string;
  composeProjectName: string;
  gatewayHostPortBase: number;
}

export type GoogleCloudRunIngress =
  | "all"
  | "internal"
  | "internal-and-cloud-load-balancing";

/**
 * Auth mode the deployed gateway runs in.
 *
 * - `"none"` (45.5.7) — gateway is publicly reachable with no app-layer check.
 *   Fine for verification or zero-cost endpoints; dangerous for plugin routes
 *   that cost money (LLM proxy, etc.) because anyone with the URL can drain
 *   the budget.
 * - `"bearer"` (45.5.8) — gateway requires `Authorization: Bearer <token>` on
 *   every request except `/health`. The token is a deployment secret
 *   (`gateway-shared-token`, exposed as `SUGARMAGIC_GATEWAY_SHARED_TOKEN`) the
 *   user sets via the existing Set Value modal. Single shared token across
 *   all callers — appropriate for solo-dev alpha where the threat model is
 *   drive-by abuse, not malicious authenticated users.
 *
 * When [Plan 047](047-sugarprofile-user-management-plugin-epic.md) lands the
 * proper identity-provider plugin model, this enum expands to include real
 * provider ids (`"supabase"`, `"auth0"`, etc.) and the gateway middleware
 * switches based on the value. `"bearer"` retroactively becomes the first
 * concrete provider in that SDK.
 */
export type GatewayAuthMode = "none" | "bearer";

/**
 * Story 47.9 — runtime-only superset of GatewayAuthMode. Persisted
 * overrides keep `"none" | "bearer"` (so old project files load
 * unchanged); the planner promotes a user-selected `"bearer"` to
 * `"supabase-jwt"` when SugarProfile is enabled, and passes the
 * effective mode to the codegen. Codegen doesn't need to know
 * which user toggle produced `"supabase-jwt"` — just that it
 * should emit the JWT verifier instead of the shared-token check.
 */
export type EffectiveGatewayAuthMode = GatewayAuthMode | "supabase-jwt";

const SUGARPROFILE_PLUGIN_ID = "sugarprofile";

function isSugarProfileLoginEnabled(gameProject: GameProject): boolean {
  const configuration = gameProject.pluginConfigurations.find(
    (entry) => entry.pluginId === SUGARPROFILE_PLUGIN_ID
  );
  if (!configuration || !configuration.enabled) return false;
  const config = (configuration.config ?? {}) as Record<string, unknown>;
  return config.enableLogin === true;
}

/**
 * Story 47.9 — given the persisted Cloud Run overrides + the
 * game project, return the effective gateway auth mode the
 * gateway will run in:
 *
 *   - persisted "none"   → "none"
 *   - persisted "bearer" + SugarProfile login DISABLED → "bearer"
 *   - persisted "bearer" + SugarProfile login ENABLED  → "supabase-jwt"
 *
 * "supabase-jwt" supersedes the shared-token path: the Supabase
 * JWT carries per-user identity (`sub` = userId), removing the
 * need for a single shared bearer token.
 */
export function deriveEffectiveGatewayAuthMode(
  persistedMode: GatewayAuthMode,
  gameProject: GameProject
): EffectiveGatewayAuthMode {
  if (persistedMode !== "bearer") return persistedMode;
  return isSugarProfileLoginEnabled(gameProject) ? "supabase-jwt" : "bearer";
}

export interface GoogleCloudRunDeploymentTargetOverrides {
  workingDirectory: string;
  projectId: string;
  region: string;
  serviceNamePrefix: string;
  containerPort: number;
  minInstances: number;
  maxInstances: number;
  ingress: GoogleCloudRunIngress;
  // Persisted exactly as `owner/repo` (matches GitHub OIDC `repository` claim).
  // Drives the Workload Identity Federation binding generated by terraform.
  // Empty string until the user fills it in via the SugarDeploy Cloud Run section.
  githubRepo: string;
  // Optional explicit name override for the runtime service account. When empty,
  // terraform derives `${serviceNamePrefix}-runtime`.
  runtimeServiceAccountName: string;
  // Story 45.5.7 — see GatewayAuthMode docstring. Plan 047 expands this.
  gatewayAuthMode: GatewayAuthMode;
}

function slugify(input: string): string {
  const value = input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-+/g, "-");
  return value || "sugarmagic";
}

function clampInteger(
  value: unknown,
  fallback: number,
  options?: { min?: number; max?: number }
): number {
  const numeric =
    typeof value === "number"
      ? value
      : typeof value === "string" && value.trim().length > 0
        ? Number(value)
        : Number.NaN;
  if (!Number.isFinite(numeric)) {
    return fallback;
  }
  const floored = Math.floor(numeric);
  const min = options?.min ?? Number.MIN_SAFE_INTEGER;
  const max = options?.max ?? Number.MAX_SAFE_INTEGER;
  return Math.max(min, Math.min(max, floored));
}

function asNonEmptyString(value: unknown, fallback: string): string {
  return typeof value === "string" && value.trim().length > 0
    ? value.trim()
    : fallback;
}

// All derived identifiers (slug, GCP project id, service name prefix, secret
// container names, etc.) MUST flow from `identity.id`, which is the stable
// normalized slug assigned at project creation time. `displayName` is for UI
// display ONLY and can change without breaking cloud resource identity.
function defaultDeploymentSlug(gameProject: Pick<GameProject, "identity">): string {
  return slugify(gameProject.identity.id || "sugarmagic-game");
}

function resolveMajorVersion(
  gameProject: Pick<GameProject, "majorVersion"> | undefined
): number {
  const raw = gameProject?.majorVersion;
  return typeof raw === "number" && Number.isFinite(raw) && raw >= 1
    ? Math.floor(raw)
    : 1;
}

// Story 45.7.5 — gameProjects passed to the normalizers carry the
// SugarDeploy plugin state in their pluginConfigurations slot (new
// shape) and/or in legacy top-level fields (mid-migration projects).
// The plugin-state helpers handle both transparently. The Pick<>
// signatures below widen to `pluginConfigurations` so the helpers can
// inspect the slot, with the legacy fields still listed during the
// migration window so old fixtures continue to compile.
type GameProjectForVersionedSlug = Pick<
  GameProject,
  "identity" | "majorVersion" | "pluginConfigurations"
>;

function defaultVersionedDeploymentSlug(
  gameProject: GameProjectForVersionedSlug
): string {
  const slug = defaultDeploymentSlug(gameProject);
  const major = resolveMajorVersion(gameProject);
  // Story 45.4.7 — collision-resistant suffix. When the project has a recorded
  // suffix for the current major version (set lazily by the SugarDeploy form
  // on first mount, or by Cut New Major Version per 45.8), include it in the
  // derivation: `${slug}-v${major}-${suffix}`. When absent — older project
  // files that haven't been opened in SugarDeploy yet, or non-Cloud-Run
  // targets — fall back to the pre-45.4.7 `${slug}-v${major}` form so
  // existing GCP projects remain reachable until the form mounts and
  // generates a suffix.
  const identifiers = getVersionedProjectIdentifiers(gameProject);
  const suffix = identifiers[`v${major}`];
  return suffix ? `${slug}-v${major}-${suffix}` : `${slug}-v${major}`;
}

export function normalizeLocalDeploymentTargetOverrides(
  input: Record<string, unknown> | null | undefined,
  gameProject?: Pick<GameProject, "identity" | "pluginConfigurations">
): LocalDeploymentTargetOverrides {
  const fallbackSlug = gameProject
    ? defaultDeploymentSlug(gameProject)
    : "sugarmagic-local";
  const deploymentSettings = gameProject
    ? getDeploymentSettings(gameProject as DeployStateInput)
    : null;
  return {
    // Story 45.8.5 — workingDirectory lives on DeploymentSettings, not in
    // per-target overrides. Old project files persisted it here too; read
    // the project-level value first, fall back to the per-target value so
    // those still load cleanly.
    workingDirectory:
      deploymentSettings?.workingDirectory.trim() ||
      (typeof input?.workingDirectory === "string"
        ? input.workingDirectory.trim()
        : ""),
    composeProjectName: slugify(
      asNonEmptyString(input?.composeProjectName, `${fallbackSlug}-local`)
    ),
    gatewayHostPortBase: clampInteger(input?.gatewayHostPortBase, 8787, {
      min: 1024,
      max: 65535
    })
  };
}

export function normalizeGoogleCloudRunDeploymentTargetOverrides(
  input: Record<string, unknown> | null | undefined,
  gameProject?: Pick<
    GameProject,
    "identity" | "majorVersion" | "pluginConfigurations"
  >
): GoogleCloudRunDeploymentTargetOverrides {
  const versionedSlug = gameProject
    ? defaultVersionedDeploymentSlug(gameProject)
    : `sugarmagic-v${resolveMajorVersion(gameProject)}`;
  const deploymentSettings = gameProject
    ? getDeploymentSettings(gameProject as DeployStateInput)
    : null;
  const ingress =
    input?.ingress === "internal" ||
    input?.ingress === "internal-and-cloud-load-balancing" ||
    input?.ingress === "all"
      ? input.ingress
      : "all";
  return {
    // Story 45.8.5 — see Local normalizer above. Project-level value first.
    workingDirectory:
      deploymentSettings?.workingDirectory.trim() ||
      (typeof input?.workingDirectory === "string"
        ? input.workingDirectory.trim()
        : ""),
    projectId: slugify(asNonEmptyString(input?.projectId, versionedSlug)),
    region: asNonEmptyString(input?.region, "us-central1"),
    serviceNamePrefix: slugify(
      asNonEmptyString(input?.serviceNamePrefix, versionedSlug)
    ),
    containerPort: clampInteger(input?.containerPort, 8080, {
      min: 1024,
      max: 65535
    }),
    // Story 45.5 right-sized defaults: gateway is a thin HTTP proxy now that
    // LLM + vector DB are external, so `min-instances=1` keeps in-game dialog
    // snappy (no cold start) and `max-instances=4` matches the prior wordlark
    // shape that ran fine under real load. CPU throttling collapses the idle
    // bill; see deploy.sh for the cpu/memory/throttling bake-in.
    minInstances: clampInteger(input?.minInstances, 1, { min: 0, max: 100 }),
    maxInstances: clampInteger(input?.maxInstances, 4, { min: 1, max: 100 }),
    ingress,
    // Story 45.8.5 — githubRepo lives on DeploymentSettings, not in
    // per-target overrides. Old project files persisted it here; read
    // the project-level value first, fall back to the per-target value.
    githubRepo:
      normalizeGithubRepoOverride(deploymentSettings?.githubRepo) ||
      normalizeGithubRepoOverride(input?.githubRepo),
    runtimeServiceAccountName:
      typeof input?.runtimeServiceAccountName === "string"
        ? input.runtimeServiceAccountName.trim()
        : "",
    // Story 45.5.8 — "none" | "bearer". Anything else normalizes to "none"
    // so old project files load cleanly when the enum expands in Plan 047.
    gatewayAuthMode:
      input?.gatewayAuthMode === "bearer" ? "bearer" : "none"
  };
}

// Canonical GitHub `owner/repo` shape. Single source of truth used by both the
// override normalizer (for tfvars / persistence) and the Studio field (for
// inline validation feedback). GitHub OIDC's `repository` claim and terraform's
// `attribute.repository == "..."` condition both expect this exact form.
export const GITHUB_REPO_REGEX = /^[A-Za-z0-9._-]+\/[A-Za-z0-9._-]+$/;

// Paste-forgiveness for GitHub references: strip the prefix/suffix variants
// users commonly paste (browser URL, https clone URL, ssh clone URL) and return
// what's left. Validation is the caller's job — this is only the trim step.
// Single source of truth used by the override normalizer below AND by the
// Studio form field's onChange handler.
export function stripGithubRepoPrefixes(value: string): string {
  let trimmed = value.trim();
  trimmed = trimmed.replace(/^https?:\/\/github\.com\//i, "");
  trimmed = trimmed.replace(/^git@github\.com:/i, "");
  trimmed = trimmed.replace(/\.git$/i, "");
  return trimmed;
}

// Strip then validate as owner/repo. Empty / unparseable values become "" so
// terraform validate still passes against the un-filled-in state; the actual
// deploy-time requirement is enforced by the host action that runs
// `terraform apply`.
function normalizeGithubRepoOverride(value: unknown): string {
  if (typeof value !== "string") return "";
  const stripped = stripGithubRepoPrefixes(value);
  if (stripped.length === 0) return "";
  return GITHUB_REPO_REGEX.test(stripped) ? stripped : "";
}
