/**
 * Published-web managed-file generators.
 *
 * Owns the per-game artifacts SugarDeploy lays down under
 * `.sugarmagic/published-web/` for the Netlify deploy:
 *
 *   - `boot.json` — serialized `WebRuntimeStartState`-shaped payload
 *     the deployed page fetches at runtime. This is the per-game data
 *     (project authoring slice + content library snapshot). Game-
 *     agnostic JS/HTML shell lives next to it in `dist/` and is laid
 *     down by a separate host action (`/__sugardeploy/build-published-web`)
 *     because it requires a `vite build` shell-out.
 *
 *   - `README.md` — drift-resistant note explaining what's here, what
 *     SugarDeploy regenerates on save, and what the Build Frontend
 *     button refreshes.
 *
 * The frontend GHA workflow's deploy step just does
 * `netlify deploy --dir=.sugarmagic/published-web/` — both files are
 * already in the repo, so no engine clone / install / build is needed
 * inside the workflow.
 *
 * Story 46.10 follow-up; see `docs/plans/046-story-046.14-*.md` for
 * the GHCR-published-prebuilt refactor that will eventually replace
 * the local-build-+-commit shape.
 */

import type {
  ContentLibrarySnapshot,
  GameProject,
  RegionDocument
} from "@sugarmagic/domain";
import type { ManagedProjectFile } from "./index";

/**
 * Schema version stamped onto every boot.json. Bumped when the
 * fetched payload shape changes meaningfully. Target-web's runtime
 * checks this and fails fast (with a clear message) on mismatch.
 */
export const BOOT_JSON_SCHEMA_VERSION = 1;

const PUBLISHED_WEB_DIRECTORY = ".sugarmagic/published-web";
const PUBLISHED_WEB_README = `.sugarmagic/published-web/README.md`;

const PUBLISHED_WEB_HEADER = "GENERATED BY SUGARMAGIC - DO NOT EDIT";

function asJsonFile(
  relativePath: string,
  payload: Record<string, unknown>
): ManagedProjectFile {
  return {
    relativePath,
    content: `${JSON.stringify(payload, null, 2)}\n`,
    contentType: "json"
  };
}

function asTextFile(
  relativePath: string,
  content: string
): ManagedProjectFile {
  return { relativePath, content, contentType: "text" };
}

/**
 * Story 46.10 follow-up — the full payload target-web's runtime
 * loads at boot. Mirrors `WebRuntimeStartState` from
 * `@sugarmagic/target-web`. Studio's save call passes the live
 * in-memory data; non-Studio callers (e.g. test fixtures) get
 * empty defaults so the runtime can still load to a "no content"
 * state instead of throwing on missing fields.
 */
export interface PublishedWebRuntimeSnapshot {
  regions: RegionDocument[];
  contentLibrary: ContentLibrarySnapshot;
  /** Maps asset references (typically asset definition ids) to URLs the
   * deployed page can fetch them from. Stays empty for now — asset
   * hosting itself is a separate follow-up. */
  assetSources: Record<string, string>;
  activeRegionId?: string | null;
  activeEnvironmentId?: string | null;
}

function emptySnapshot(): PublishedWebRuntimeSnapshot {
  return {
    regions: [],
    contentLibrary: { items: [] } as unknown as ContentLibrarySnapshot,
    assetSources: {},
    activeRegionId: null,
    activeEnvironmentId: null
  };
}

/**
 * Build the boot.json payload from a game project + the in-memory
 * runtime snapshot Studio has loaded. The shape mirrors
 * `WebRuntimeStartState`; mismatches between this shape and the
 * runtime's expectation are guarded by `BOOT_JSON_SCHEMA_VERSION`.
 */
function buildBootJsonPayload(
  gameProject: GameProject,
  snapshot: PublishedWebRuntimeSnapshot
): Record<string, unknown> {
  const activeRegionId =
    snapshot.activeRegionId !== undefined
      ? snapshot.activeRegionId
      : snapshot.regions[0]?.identity.id ?? null;
  return {
    note: PUBLISHED_WEB_HEADER,
    schemaVersion: BOOT_JSON_SCHEMA_VERSION,
    gameProjectIdentity: gameProject.identity,
    gameProjectMajorVersion: gameProject.majorVersion,
    installedPluginIds: gameProject.pluginConfigurations
      .filter((entry) => entry.enabled)
      .map((entry) => entry.pluginId),
    pluginConfigurations: gameProject.pluginConfigurations,
    regions: snapshot.regions,
    activeRegionId,
    activeEnvironmentId: snapshot.activeEnvironmentId ?? null,
    contentLibrary: snapshot.contentLibrary,
    mechanics: gameProject.mechanics,
    playerDefinition: gameProject.playerDefinition,
    spellDefinitions: gameProject.spellDefinitions,
    itemDefinitions: gameProject.itemDefinitions,
    documentDefinitions: gameProject.documentDefinitions,
    npcDefinitions: gameProject.npcDefinitions,
    dialogueDefinitions: gameProject.dialogueDefinitions,
    questDefinitions: gameProject.questDefinitions,
    menuDefinitions: gameProject.menuDefinitions,
    hudDefinition: gameProject.hudDefinition,
    uiTheme: gameProject.uiTheme,
    soundEventBindings: gameProject.soundEventBindings,
    audioMixer: gameProject.audioMixer,
    assetSources: snapshot.assetSources
  };
}

export function buildPublishedWebManagedFiles(
  gameProject: GameProject,
  snapshot: PublishedWebRuntimeSnapshot = emptySnapshot()
): ManagedProjectFile[] {
  const files: ManagedProjectFile[] = [];
  files.push(
    asJsonFile(
      `${PUBLISHED_WEB_DIRECTORY}/boot.json`,
      buildBootJsonPayload(gameProject, snapshot)
    )
  );
  files.push(
    asTextFile(
      PUBLISHED_WEB_README,
      [
        `# ${PUBLISHED_WEB_HEADER}`,
        "",
        "# Published-web bundle root",
        "",
        "This directory is the per-game artifact root that the GHA",
        "`deploy-frontend` job hands to `netlify deploy --dir=...`.",
        "",
        "## Generated on save",
        "",
        "- `boot.json` — per-game runtime payload (schemaVersion " +
          BOOT_JSON_SCHEMA_VERSION +
          "). Regenerated every time you save the project.",
        "- `README.md` — this file.",
        "",
        "## Generated by the Build Frontend button",
        "",
        "- `dist/` — `@sugarmagic/target-web` static bundle. Game-",
        "  agnostic; only changes when the sugarmagic engine itself",
        "  changes. Run Build Frontend (Provision workspace) to",
        "  refresh; commit the result alongside `boot.json` so the",
        "  Netlify deploy can ship both together.",
        "",
        "## How it ships",
        "",
        "`deploy.sh`'s GHA-side counterpart calls",
        "`npx -y netlify-cli@17 deploy --dir=.sugarmagic/published-web/",
        " --site=$NETLIFY_SITE_ID --prod`. No engine clone, no install,",
        "no build. Boot.json is fetched from the deployed origin at",
        "runtime by `target-web/src/App.tsx`.",
        ""
      ].join("\n")
    )
  );
  return files;
}

export function getPublishedWebDirectory(): string {
  return PUBLISHED_WEB_DIRECTORY;
}
