/**
 * Published-web managed-file generators.
 *
 * Owns the per-game artifacts SugarDeploy lays down under
 * `.sugarmagic/published-web/` for the Netlify deploy:
 *
 *   - `boot.json` — serialized `WebRuntimeStartState`-shaped payload
 *     the deployed page fetches at runtime. This is the per-game data
 *     (project authoring slice + content library snapshot). Game-
 *     agnostic JS/HTML shell lives next to it in `dist/` and is laid
 *     down by a separate host action (`/__sugardeploy/build-published-web`)
 *     because it requires a `vite build` shell-out.
 *
 *   - `README.md` — drift-resistant note explaining what's here, what
 *     SugarDeploy regenerates on save, and what the Build Frontend
 *     button refreshes.
 *
 * The frontend GHA workflow's deploy step just does
 * `netlify deploy --dir=.sugarmagic/published-web/` — both files are
 * already in the repo, so no engine clone / install / build is needed
 * inside the workflow.
 *
 * Story 46.10 follow-up; see `docs/plans/046-story-046.14-*.md` for
 * the GHCR-published-prebuilt refactor that will eventually replace
 * the local-build-+-commit shape.
 */

import type { GameProject } from "@sugarmagic/domain";
import type { ManagedProjectFile } from "./index";

/**
 * Schema version stamped onto every boot.json. Bumped when the
 * fetched payload shape changes meaningfully. Target-web's runtime
 * checks this and fails fast (with a clear message) on mismatch.
 */
export const BOOT_JSON_SCHEMA_VERSION = 1;

const PUBLISHED_WEB_DIRECTORY = ".sugarmagic/published-web";
const PUBLISHED_WEB_README = `.sugarmagic/published-web/README.md`;

const PUBLISHED_WEB_HEADER = "GENERATED BY SUGARMAGIC - DO NOT EDIT";

function asJsonFile(
  relativePath: string,
  payload: Record<string, unknown>
): ManagedProjectFile {
  return {
    relativePath,
    content: `${JSON.stringify(payload, null, 2)}\n`,
    contentType: "json"
  };
}

function asTextFile(
  relativePath: string,
  content: string
): ManagedProjectFile {
  return { relativePath, content, contentType: "text" };
}

/**
 * Build the boot.json payload from a game project. For now this
 * mirrors the slice of `WebRuntimeStartState` that lives on
 * `GameProject` directly; full content (regions + content library
 * snapshot) lands in a follow-up that wires the on-disk files into
 * the build path.
 */
function buildBootJsonPayload(gameProject: GameProject): Record<string, unknown> {
  return {
    note: PUBLISHED_WEB_HEADER,
    schemaVersion: BOOT_JSON_SCHEMA_VERSION,
    gameProjectIdentity: gameProject.identity,
    gameProjectMajorVersion: gameProject.majorVersion,
    // Per-runtime fields. Slots not yet baked from the on-disk
    // sources default to empty so the deployed page can still boot
    // and surface a clear "no content" state instead of throwing.
    installedPluginIds: gameProject.pluginConfigurations
      .filter((entry) => entry.enabled)
      .map((entry) => entry.pluginId),
    pluginConfigurations: gameProject.pluginConfigurations,
    regions: [],
    activeRegionId: null,
    activeEnvironmentId: null,
    contentLibrary: { items: [] },
    mechanics: gameProject.mechanics,
    playerDefinition: gameProject.playerDefinition,
    spellDefinitions: gameProject.spellDefinitions,
    itemDefinitions: gameProject.itemDefinitions,
    documentDefinitions: gameProject.documentDefinitions,
    npcDefinitions: gameProject.npcDefinitions,
    dialogueDefinitions: gameProject.dialogueDefinitions,
    questDefinitions: gameProject.questDefinitions,
    menuDefinitions: gameProject.menuDefinitions,
    hudDefinition: gameProject.hudDefinition,
    uiTheme: gameProject.uiTheme,
    soundEventBindings: gameProject.soundEventBindings,
    audioMixer: gameProject.audioMixer,
    assetSources: {}
  };
}

export function buildPublishedWebManagedFiles(
  gameProject: GameProject
): ManagedProjectFile[] {
  const files: ManagedProjectFile[] = [];
  files.push(
    asJsonFile(
      `${PUBLISHED_WEB_DIRECTORY}/boot.json`,
      buildBootJsonPayload(gameProject)
    )
  );
  files.push(
    asTextFile(
      PUBLISHED_WEB_README,
      [
        `# ${PUBLISHED_WEB_HEADER}`,
        "",
        "# Published-web bundle root",
        "",
        "This directory is the per-game artifact root that the GHA",
        "`deploy-frontend` job hands to `netlify deploy --dir=...`.",
        "",
        "## Generated on save",
        "",
        "- `boot.json` — per-game runtime payload (schemaVersion " +
          BOOT_JSON_SCHEMA_VERSION +
          "). Regenerated every time you save the project.",
        "- `README.md` — this file.",
        "",
        "## Generated by the Build Frontend button",
        "",
        "- `dist/` — `@sugarmagic/target-web` static bundle. Game-",
        "  agnostic; only changes when the sugarmagic engine itself",
        "  changes. Run Build Frontend (Provision workspace) to",
        "  refresh; commit the result alongside `boot.json` so the",
        "  Netlify deploy can ship both together.",
        "",
        "## How it ships",
        "",
        "`deploy.sh`'s GHA-side counterpart calls",
        "`npx -y netlify-cli@17 deploy --dir=.sugarmagic/published-web/",
        " --site=$NETLIFY_SITE_ID --prod`. No engine clone, no install,",
        "no build. Boot.json is fetched from the deployed origin at",
        "runtime by `target-web/src/App.tsx`.",
        ""
      ].join("\n")
    )
  );
  return files;
}

export function getPublishedWebDirectory(): string {
  return PUBLISHED_WEB_DIRECTORY;
}
