/**
 * Published-web managed-file generators.
 *
 * Owns the per-game artifacts SugarDeploy lays down under
 * `.sugarmagic/published-web/` for the Netlify deploy:
 *
 *   - `boot.json` — serialized `WebRuntimeStartState`-shaped payload
 *     the deployed page fetches at runtime. Per-game data (project
 *     authoring slice + content library snapshot). Regenerated on
 *     every Studio save; committed in the game repo.
 *
 *   - `README.md` — drift-resistant note explaining what's here and
 *     how `dist/` regenerates inside the GHA deploy-frontend job at
 *     deploy time. Committed alongside boot.json.
 *
 * The `dist/` engine bundle is NOT a managed file — Plan 053.2 moved
 * the build into the GHA `deploy-frontend` job, which checks out
 * sugarmagic, runs `pnpm --filter @sugarmagic/target-web build`,
 * then copies the result to `.sugarmagic/published-web/dist/` inside
 * the runner before `netlify deploy --dir=...`. The game repo's
 * `.gitignore` covers the directory via the top-level `dist` rule.
 *
 * Story 46.10 follow-up; Plan 053 reshape (053.2 + 053.3 + 053.4)
 * removed the local-build-+-commit stopgap entirely.
 */

import type {
  ContentLibrarySnapshot,
  GameProject,
  RegionDocument
} from "@sugarmagic/domain";
import {
  collectFileBackedAssetPaths,
  normalizeCreditsDefinition
} from "@sugarmagic/domain";
import type { ManagedProjectFile } from "./index";

/**
 * Schema version stamped onto every boot.json. Bumped when the
 * fetched payload shape changes meaningfully. Target-web's runtime
 * checks this and fails fast (with a clear message) on mismatch.
 */
export const BOOT_JSON_SCHEMA_VERSION = 1;

const PUBLISHED_WEB_DIRECTORY = ".sugarmagic/published-web";
const PUBLISHED_WEB_README = `.sugarmagic/published-web/README.md`;

const PUBLISHED_WEB_HEADER = "GENERATED BY SUGARMAGIC - DO NOT EDIT";

function asJsonFile(
  relativePath: string,
  payload: Record<string, unknown>
): ManagedProjectFile {
  return {
    relativePath,
    content: `${JSON.stringify(payload, null, 2)}\n`,
    contentType: "json"
  };
}

function asTextFile(
  relativePath: string,
  content: string
): ManagedProjectFile {
  return { relativePath, content, contentType: "text" };
}

/**
 * Story 46.10 follow-up — the full payload target-web's runtime
 * loads at boot. Mirrors `WebRuntimeStartState` from
 * `@sugarmagic/target-web`. Studio's save call passes the live
 * in-memory data; non-Studio callers (e.g. test fixtures) get
 * empty defaults so the runtime can still load to a "no content"
 * state instead of throwing on missing fields.
 */
export interface PublishedWebRuntimeSnapshot {
  regions: RegionDocument[];
  contentLibrary: ContentLibrarySnapshot;
  /** Maps asset references (typically asset definition ids) to URLs the
   * deployed page can fetch them from. Stays empty for now — asset
   * hosting itself is a separate follow-up. */
  assetSources: Record<string, string>;
  activeRegionId?: string | null;
  activeEnvironmentId?: string | null;
}

function emptySnapshot(): PublishedWebRuntimeSnapshot {
  return {
    regions: [],
    contentLibrary: { items: [] } as unknown as ContentLibrarySnapshot,
    assetSources: {},
    activeRegionId: null,
    activeEnvironmentId: null
  };
}

/**
 * Build the boot.json payload from a game project + the in-memory
 * runtime snapshot Studio has loaded. The shape mirrors
 * `WebRuntimeStartState`; mismatches between this shape and the
 * runtime's expectation are guarded by `BOOT_JSON_SCHEMA_VERSION`.
 */
function buildBootJsonPayload(
  gameProject: GameProject,
  snapshot: PublishedWebRuntimeSnapshot
): Record<string, unknown> {
  const activeRegionId =
    snapshot.activeRegionId !== undefined
      ? snapshot.activeRegionId
      : snapshot.regions[0]?.identity.id ?? null;
  return {
    note: PUBLISHED_WEB_HEADER,
    schemaVersion: BOOT_JSON_SCHEMA_VERSION,
    gameProjectIdentity: gameProject.identity,
    gameProjectMajorVersion: gameProject.majorVersion,
    installedPluginIds: gameProject.pluginConfigurations
      .filter((entry) => entry.enabled)
      .map((entry) => entry.pluginId),
    pluginConfigurations: gameProject.pluginConfigurations,
    regions: snapshot.regions,
    // Plan 058 §058.1 — narrative Scenes ship in the bundle
    // (bake-everything model; the runtime composes only unlocked
    // Scenes' overlays). Regions above are the shrunk base shape.
    scenes: gameProject.scenes,
    scenesUiLabel: gameProject.scenesUiLabel,
    activeRegionId,
    activeEnvironmentId: snapshot.activeEnvironmentId ?? null,
    contentLibrary: snapshot.contentLibrary,
    mechanics: gameProject.mechanics,
    playerDefinition: gameProject.playerDefinition,
    spellDefinitions: gameProject.spellDefinitions,
    itemDefinitions: gameProject.itemDefinitions,
    documentDefinitions: gameProject.documentDefinitions,
    npcDefinitions: gameProject.npcDefinitions,
    dialogueDefinitions: gameProject.dialogueDefinitions,
    questDefinitions: gameProject.questDefinitions,
    menuDefinitions: gameProject.menuDefinitions,
    hudDefinition: gameProject.hudDefinition,
    uiTheme: gameProject.uiTheme,
    soundEventBindings: gameProject.soundEventBindings,
    audioMixer: gameProject.audioMixer,
    // Plan 059 §059.1 — project music slots.
    musicBindings: gameProject.musicBindings,
    // Plan 059 §059.2 — credits roll content, normalized at
    // publish (the live session preserves editor text verbatim).
    creditsDefinition: normalizeCreditsDefinition(
      gameProject.creditsDefinition
    ),
    // Plan 059 §059.3 — entry title sequence's first card.
    gameTitle: gameProject.displayName,
    // 2026-07-05 fix — the deployed game fetches file-backed
    // assets (audio clips, models, textures, thumbnails) from the
    // site itself: the deploy workflow ships the project's
    // `assets/` directory next to boot.json, and this map points
    // every known relativeAssetPath at its site-relative URL.
    // (Previously baked `{}` — Studio's blob-URL map can't
    // survive a deploy — which silently broke ALL file-backed
    // assets in prod; deployed music was the first to notice.)
    // A non-empty snapshot map (tests, future CDN hosting) wins.
    assetSources:
      Object.keys(snapshot.assetSources).length > 0
        ? snapshot.assetSources
        : Object.fromEntries(
            collectFileBackedAssetPaths({
              contentLibrary: snapshot.contentLibrary,
              itemDefinitions: gameProject.itemDefinitions,
              documentDefinitions: gameProject.documentDefinitions
            }).map((path) => [path, `/${path}`])
          ),
    // Story 47.10.5 — authored fresh-start record. When a returning
    // player loads with no save (or just clicked New Game + reset),
    // the runtime spawns at these values instead of the implicit
    // playerPresence defaults. `null` for projects that haven't
    // curated a value.
    defaultGameSavePayload: gameProject.defaultGameSavePayload
  };
}

export function buildPublishedWebManagedFiles(
  gameProject: GameProject,
  snapshot: PublishedWebRuntimeSnapshot = emptySnapshot()
): ManagedProjectFile[] {
  const files: ManagedProjectFile[] = [];
  files.push(
    asJsonFile(
      `${PUBLISHED_WEB_DIRECTORY}/boot.json`,
      buildBootJsonPayload(gameProject, snapshot)
    )
  );
  // Plan 060 §060.2 — Netlify `_headers`: authored assets get a
  // day of caching (Netlify's default is max-age=0, so every
  // visit re-downloaded every mp3/GLB). One day, not immutable:
  // authored asset paths are NOT content-hashed, so a redeploy
  // that changes a file's bytes under the same path must be able
  // to reach returning players within a day. Revisit trigger:
  // content-hashed asset filenames (Plan 058's load-per-Scene
  // distribution defer) unlock max-age=31536000,immutable here.
  // boot.json is listed explicitly to pin its must-revalidate
  // behavior even if broader rules join this file later.
  files.push(
    asTextFile(
      `${PUBLISHED_WEB_DIRECTORY}/_headers`,
      [
        `# ${PUBLISHED_WEB_HEADER}`,
        "/assets/*",
        "  Cache-Control: public, max-age=86400",
        "/boot.json",
        "  Cache-Control: public, max-age=0, must-revalidate",
        ""
      ].join("\n")
    )
  );
  files.push(
    asTextFile(
      PUBLISHED_WEB_README,
      [
        `# ${PUBLISHED_WEB_HEADER}`,
        "",
        "# Published-web bundle root",
        "",
        "This directory is the per-game artifact root that the GHA",
        "`deploy-frontend` job hands to `netlify deploy --dir=...`.",
        "",
        "## Generated on save",
        "",
        "- `boot.json` — per-game runtime payload (schemaVersion " +
          BOOT_JSON_SCHEMA_VERSION +
          "). Regenerated every time you save the project.",
        "- `_headers` — Netlify cache rules for the deployed site",
        "  (authored assets cache for a day; boot.json always",
        "  revalidates). Copied into `dist/` at deploy time.",
        "- `README.md` — this file.",
        "",
        "## Generated at deploy time (gitignored)",
        "",
        "- `dist/` — `@sugarmagic/target-web` static bundle. Built",
        "  fresh on every deploy by the GHA `deploy-frontend` job",
        "  off whatever sugarmagic ref the dispatch was pinned to",
        "  (default: sugarmagic `main`). NOT committed; the game",
        "  repo's `.gitignore` covers it via the top-level `dist`",
        "  rule. Plan 053.2 + 053.3 ripped this out of the game",
        "  repo so the only thing the author commits between",
        "  content changes is `boot.json`.",
        "",
        "## How it ships",
        "",
        "Click Deploy in Studio's SugarDeploy workspace. Studio",
        "auto-commits + auto-pushes both the game repo and",
        "sugarmagic, then dispatches the GHA workflow. The",
        "`deploy-frontend` job checks out sugarmagic into its own",
        "subdirectory, runs `pnpm --filter @sugarmagic/target-web",
        "build`, copies the dist here, overlays `boot.json`, and",
        "runs `netlify-cli deploy`. Boot.json is fetched from the",
        "deployed origin at runtime by `target-web/src/App.tsx`.",
        ""
      ].join("\n")
    )
  );
  return files;
}

export function getPublishedWebDirectory(): string {
  return PUBLISHED_WEB_DIRECTORY;
}
