/**
 * packages/plugins/src/deployment/supabase.ts
 *
 * Purpose: Generates SugarProfile's Supabase managed files
 * (deployment/supabase/config.toml + the SQL migrations directory)
 * into the game project on save. The Supabase CLI's `db push`
 * consumes these to apply schema changes against the configured
 * project; the host endpoint `/__sugarprofile/run-migration` wraps
 * the CLI invocation.
 *
 * Emission is gated on SugarProfile being enabled AND its config
 * carrying a non-empty `supabaseUrl`. Without those, no Supabase
 * files get emitted — games that don't use SugarProfile don't get
 * a stray `deployment/supabase/` directory.
 *
 * Implements: Plan 047 §Story 47.8
 *
 * Status: active
 */

import type { GameProject } from "@sugarmagic/domain";
import type { ManagedProjectFile } from "./index";

export const SUPABASE_MIGRATIONS_TEMPLATE_VERSION = 1;
const TEMPLATE_VERSION_STAMP_PREFIX = "-- SUGARMAGIC SUPABASE MIGRATIONS TEMPLATE VERSION:";

const GENERATED_HEADER = "GENERATED BY SUGARMAGIC - DO NOT EDIT";

const SUGARPROFILE_PLUGIN_ID = "sugarprofile";

/**
 * Pulls the Supabase project ref out of a project URL. Supabase
 * URLs follow `https://<project-ref>.supabase.co`; we lop the
 * scheme + `.supabase.co` suffix. Returns null when the URL
 * doesn't match the expected shape.
 */
export function extractSupabaseProjectRef(url: string): string | null {
  if (typeof url !== "string") return null;
  const trimmed = url.trim();
  if (trimmed.length === 0) return null;
  const match = /^https?:\/\/([a-z0-9-]+)\.supabase\.co(?:\/|$)/i.exec(trimmed);
  return match ? match[1] : null;
}

interface SugarProfileConfigShape {
  enableLogin: boolean;
  supabaseUrl: string;
}

function readSugarProfileConfig(
  gameProject: GameProject
): SugarProfileConfigShape | null {
  const configuration = gameProject.pluginConfigurations.find(
    (entry) => entry.pluginId === SUGARPROFILE_PLUGIN_ID
  );
  if (!configuration || !configuration.enabled) return null;
  const config = (configuration.config ?? {}) as Record<string, unknown>;
  return {
    enableLogin: config.enableLogin === true,
    supabaseUrl:
      typeof config.supabaseUrl === "string" ? config.supabaseUrl.trim() : ""
  };
}

/**
 * Story 47.8 — initial migration. Creates `public.saves` +
 * `public.profiles` with RLS policies + an auto-create-profile
 * trigger on `auth.users` INSERT. The trigger function is
 * `security definer` so it bypasses RLS on the profile insert
 * (necessary — when the trigger fires, the user is the row owner
 * being created, so they can't satisfy `auth.uid() = user_id` yet).
 */
function buildInitialMigrationSql(): string {
  return [
    `-- ${GENERATED_HEADER}`,
    `${TEMPLATE_VERSION_STAMP_PREFIX} ${SUPABASE_MIGRATIONS_TEMPLATE_VERSION}`,
    "",
    "-- Plan 047 §47.8 — SugarProfile's owned schema.",
    "-- public.saves: cross-plugin player state (region, position, quest)",
    "-- public.profiles: per-user authored data (display_name, locale, preferences)",
    "-- on_auth_user_created trigger: every new auth.users row gets a profiles row",
    "",
    "create table if not exists public.saves (",
    "  user_id uuid primary key references auth.users(id) on delete cascade,",
    "  last_played timestamptz not null default now(),",
    "  schema_version integer not null default 1,",
    "  payload jsonb not null default '{}'::jsonb",
    ");",
    "",
    "alter table public.saves enable row level security;",
    "",
    "create policy \"users select own saves\" on public.saves",
    "  for select using (auth.uid() = user_id);",
    "create policy \"users insert own saves\" on public.saves",
    "  for insert with check (auth.uid() = user_id);",
    "create policy \"users update own saves\" on public.saves",
    "  for update using (auth.uid() = user_id);",
    "create policy \"users delete own saves\" on public.saves",
    "  for delete using (auth.uid() = user_id);",
    "",
    "create table if not exists public.profiles (",
    "  user_id uuid primary key references auth.users(id) on delete cascade,",
    "  display_name text,",
    "  locale text not null default 'en',",
    "  preferences jsonb not null default '{}'::jsonb,",
    "  updated_at timestamptz not null default now()",
    ");",
    "",
    "alter table public.profiles enable row level security;",
    "",
    "create policy \"users select own profile\" on public.profiles",
    "  for select using (auth.uid() = user_id);",
    "create policy \"users insert own profile\" on public.profiles",
    "  for insert with check (auth.uid() = user_id);",
    "create policy \"users update own profile\" on public.profiles",
    "  for update using (auth.uid() = user_id);",
    "",
    "create or replace function public.handle_new_user()",
    "  returns trigger",
    "  language plpgsql",
    "  security definer",
    "  set search_path = public",
    "as $$",
    "begin",
    "  insert into public.profiles (user_id)",
    "    values (new.id)",
    "    on conflict (user_id) do nothing;",
    "  return new;",
    "end;",
    "$$;",
    "",
    "drop trigger if exists on_auth_user_created on auth.users;",
    "create trigger on_auth_user_created",
    "  after insert on auth.users",
    "  for each row execute function public.handle_new_user();",
    ""
  ].join("\n");
}

/**
 * Story 47.8 — Supabase CLI config. `project_id` links the
 * directory to a specific Supabase project so `supabase db push`
 * targets the right one without the user running `supabase link`
 * manually. The user still needs to `supabase login` once on their
 * dev machine (caches an access token in `~/.supabase/access-token`)
 * before the Apply Migration button works.
 */
function buildConfigToml(projectRef: string): string {
  return [
    `# ${GENERATED_HEADER}`,
    `# Project ref linked to https://${projectRef}.supabase.co`,
    `project_id = "${projectRef}"`,
    ""
  ].join("\n");
}

/**
 * Story 47.8 — manage the supabase migration directory contents.
 * Returns an empty array when SugarProfile is not enabled or has no
 * configured Supabase URL — those games shouldn't grow a stray
 * `deployment/supabase/` directory just because the plugin is
 * registered.
 */
export function buildSupabaseManagedFiles(
  gameProject: GameProject
): ManagedProjectFile[] {
  const sugarProfile = readSugarProfileConfig(gameProject);
  if (!sugarProfile || !sugarProfile.enableLogin) return [];
  const projectRef = extractSupabaseProjectRef(sugarProfile.supabaseUrl);
  if (!projectRef) return [];
  return [
    {
      relativePath: "deployment/supabase/config.toml",
      content: buildConfigToml(projectRef),
      contentType: "text"
    },
    {
      relativePath: "deployment/supabase/migrations/0001_initial.sql",
      content: buildInitialMigrationSql(),
      contentType: "text"
    }
  ];
}

export function getSugarProfileMigrationDirectory(): string {
  return "deployment/supabase";
}

/**
 * Story 47.9 — env-var name the generated gateway reads to derive
 * the Supabase project's JWKS endpoint
 * (`<url>/auth/v1/.well-known/jwks.json`). Already populated as a
 * build-time / runtime env in 47.6's deployment requirements, so no
 * additional secret-injection plumbing is needed here.
 */
export const SUPABASE_URL_ENV_VAR = "SUGARMAGIC_SUGARPROFILE_SUPABASE_URL";

/**
 * Function name emitted into the gateway's server.mjs. Asserted
 * against in tests as the marker that `"supabase-jwt"` mode was
 * actually wired into the generated source.
 */
export const SUPABASE_JWT_VERIFIER_FUNCTION_NAME = "verifySupabaseJwt";

// Story 071.9 — buildSupabaseJwtVerifierSource() deleted. JWT verifier now lives
// in packages/plugins/src/deployment/gateway/supabase-jwt.ts (typechecked TS),
// bundled into GATEWAY_CORE_COMPILED_SOURCE.
