/**
 * packages/plugins/src/deployment/supabase.ts
 *
 * Purpose: Generates SugarProfile's Supabase managed files
 * (deployment/supabase/config.toml + the SQL migrations directory)
 * into the game project on save. The Supabase CLI's `db push`
 * consumes these to apply schema changes against the configured
 * project; the host endpoint `/__sugarprofile/run-migration` wraps
 * the CLI invocation.
 *
 * Emission is gated on SugarProfile being enabled AND its config
 * carrying a non-empty `supabaseUrl`. Without those, no Supabase
 * files get emitted — games that don't use SugarProfile don't get
 * a stray `deployment/supabase/` directory.
 *
 * Implements: Plan 047 §Story 47.8
 *
 * Status: active
 */

import type { GameProject } from "@sugarmagic/domain";
import type { ManagedProjectFile } from "./index";

export const SUPABASE_MIGRATIONS_TEMPLATE_VERSION = 1;
const TEMPLATE_VERSION_STAMP_PREFIX = "-- SUGARMAGIC SUPABASE MIGRATIONS TEMPLATE VERSION:";

const GENERATED_HEADER = "GENERATED BY SUGARMAGIC - DO NOT EDIT";

const SUGARPROFILE_PLUGIN_ID = "sugarprofile";

/**
 * Pulls the Supabase project ref out of a project URL. Supabase
 * URLs follow `https://<project-ref>.supabase.co`; we lop the
 * scheme + `.supabase.co` suffix. Returns null when the URL
 * doesn't match the expected shape.
 */
export function extractSupabaseProjectRef(url: string): string | null {
  if (typeof url !== "string") return null;
  const trimmed = url.trim();
  if (trimmed.length === 0) return null;
  const match = /^https?:\/\/([a-z0-9-]+)\.supabase\.co(?:\/|$)/i.exec(trimmed);
  return match ? match[1] : null;
}

interface SugarProfileConfigShape {
  enableLogin: boolean;
  supabaseUrl: string;
}

function readSugarProfileConfig(
  gameProject: GameProject
): SugarProfileConfigShape | null {
  const configuration = gameProject.pluginConfigurations.find(
    (entry) => entry.pluginId === SUGARPROFILE_PLUGIN_ID
  );
  if (!configuration || !configuration.enabled) return null;
  const config = (configuration.config ?? {}) as Record<string, unknown>;
  return {
    enableLogin: config.enableLogin === true,
    supabaseUrl:
      typeof config.supabaseUrl === "string" ? config.supabaseUrl.trim() : ""
  };
}

/**
 * Story 47.8 — initial migration. Creates `public.saves` +
 * `public.profiles` with RLS policies + an auto-create-profile
 * trigger on `auth.users` INSERT. The trigger function is
 * `security definer` so it bypasses RLS on the profile insert
 * (necessary — when the trigger fires, the user is the row owner
 * being created, so they can't satisfy `auth.uid() = user_id` yet).
 */
function buildInitialMigrationSql(): string {
  return [
    `-- ${GENERATED_HEADER}`,
    `${TEMPLATE_VERSION_STAMP_PREFIX} ${SUPABASE_MIGRATIONS_TEMPLATE_VERSION}`,
    "",
    "-- Plan 047 §47.8 — SugarProfile's owned schema.",
    "-- public.saves: cross-plugin player state (region, position, quest)",
    "-- public.profiles: per-user authored data (display_name, locale, preferences)",
    "-- on_auth_user_created trigger: every new auth.users row gets a profiles row",
    "",
    "create table if not exists public.saves (",
    "  user_id uuid primary key references auth.users(id) on delete cascade,",
    "  last_played timestamptz not null default now(),",
    "  schema_version integer not null default 1,",
    "  payload jsonb not null default '{}'::jsonb",
    ");",
    "",
    "alter table public.saves enable row level security;",
    "",
    "create policy \"users select own saves\" on public.saves",
    "  for select using (auth.uid() = user_id);",
    "create policy \"users insert own saves\" on public.saves",
    "  for insert with check (auth.uid() = user_id);",
    "create policy \"users update own saves\" on public.saves",
    "  for update using (auth.uid() = user_id);",
    "create policy \"users delete own saves\" on public.saves",
    "  for delete using (auth.uid() = user_id);",
    "",
    "create table if not exists public.profiles (",
    "  user_id uuid primary key references auth.users(id) on delete cascade,",
    "  display_name text,",
    "  locale text not null default 'en',",
    "  preferences jsonb not null default '{}'::jsonb,",
    "  updated_at timestamptz not null default now()",
    ");",
    "",
    "alter table public.profiles enable row level security;",
    "",
    "create policy \"users select own profile\" on public.profiles",
    "  for select using (auth.uid() = user_id);",
    "create policy \"users insert own profile\" on public.profiles",
    "  for insert with check (auth.uid() = user_id);",
    "create policy \"users update own profile\" on public.profiles",
    "  for update using (auth.uid() = user_id);",
    "",
    "create or replace function public.handle_new_user()",
    "  returns trigger",
    "  language plpgsql",
    "  security definer",
    "  set search_path = public",
    "as $$",
    "begin",
    "  insert into public.profiles (user_id)",
    "    values (new.id)",
    "    on conflict (user_id) do nothing;",
    "  return new;",
    "end;",
    "$$;",
    "",
    "drop trigger if exists on_auth_user_created on auth.users;",
    "create trigger on_auth_user_created",
    "  after insert on auth.users",
    "  for each row execute function public.handle_new_user();",
    ""
  ].join("\n");
}

/**
 * Story 47.8 — Supabase CLI config. `project_id` links the
 * directory to a specific Supabase project so `supabase db push`
 * targets the right one without the user running `supabase link`
 * manually. The user still needs to `supabase login` once on their
 * dev machine (caches an access token in `~/.supabase/access-token`)
 * before the Apply Migration button works.
 */
function buildConfigToml(projectRef: string): string {
  return [
    `# ${GENERATED_HEADER}`,
    `# Project ref linked to https://${projectRef}.supabase.co`,
    `project_id = "${projectRef}"`,
    ""
  ].join("\n");
}

/**
 * Story 47.8 — manage the supabase migration directory contents.
 * Returns an empty array when SugarProfile is not enabled or has no
 * configured Supabase URL — those games shouldn't grow a stray
 * `deployment/supabase/` directory just because the plugin is
 * registered.
 */
export function buildSupabaseManagedFiles(
  gameProject: GameProject
): ManagedProjectFile[] {
  const sugarProfile = readSugarProfileConfig(gameProject);
  if (!sugarProfile || !sugarProfile.enableLogin) return [];
  const projectRef = extractSupabaseProjectRef(sugarProfile.supabaseUrl);
  if (!projectRef) return [];
  return [
    {
      relativePath: "deployment/supabase/config.toml",
      content: buildConfigToml(projectRef),
      contentType: "text"
    },
    {
      relativePath: "deployment/supabase/migrations/0001_initial.sql",
      content: buildInitialMigrationSql(),
      contentType: "text"
    }
  ];
}

export function getSugarProfileMigrationDirectory(): string {
  return "deployment/supabase";
}

/**
 * Story 47.9 — env-var name the generated gateway reads to derive
 * the Supabase project's JWKS endpoint
 * (`<url>/auth/v1/.well-known/jwks.json`). Already populated as a
 * build-time / runtime env in 47.6's deployment requirements, so no
 * additional secret-injection plumbing is needed here.
 */
export const SUPABASE_URL_ENV_VAR = "SUGARMAGIC_SUGARPROFILE_SUPABASE_URL";

/**
 * Function name emitted into the gateway's server.mjs. Asserted
 * against in tests as the marker that `"supabase-jwt"` mode was
 * actually wired into the generated source.
 */
export const SUPABASE_JWT_VERIFIER_FUNCTION_NAME = "verifySupabaseJwt";

/**
 * Story 47.9 — Supabase JWT verifier source emitted inline into the
 * gateway's generated server.mjs when the effective auth mode is
 * `"supabase-jwt"`. Fetches the project's JWKS at
 * `<supabaseUrl>/auth/v1/.well-known/jwks.json` (Supabase exposes
 * the public keys of the current + standby signing keys there),
 * caches the response with a 10-minute TTL, finds the JWT's `kid`
 * in the JWKS, and verifies the signature with the appropriate
 * algorithm:
 *
 *   - ES256 (P-256 ECC) — Supabase's default for projects migrated
 *     to the new asymmetric signing-keys system. JWT carries the
 *     signature in raw concat r||s; Node's `crypto.verify` wants
 *     DER, so we convert in-process.
 *   - HS256 (legacy shared-secret) — still emitted by Supabase
 *     projects that haven't migrated; the JWK is `{kty: "oct", k:
 *     "<base64-secret>"}` and we verify with HMAC-SHA256 +
 *     `timingSafeEqual`.
 *
 * Returns `null` on any failure (missing header, kid not found,
 * bad signature, expired, wrong audience, missing sub), or
 * `{ userId, email }` on success. The caller attaches the result
 * to `req.user` for downstream route handlers.
 *
 * Async because the JWKS fetch is async on cold cache. The gate
 * site `await`s the call before deciding whether to 401.
 *
 * Emitted as a source string rather than imported from a runtime
 * module because the gateway runs as a standalone server.mjs
 * inside a minimal Cloud Run container — it can't `import` from
 * `@sugarmagic/plugins`. Behavior tests cover the emitted source
 * by writing it to a temp file + dynamic-importing it.
 */
export function buildSupabaseJwtVerifierSource(): string {
  return `function decodeBase64Url(segment) {
  // Supabase tokens are base64url; Buffer.from(..., "base64") accepts
  // base64url-style input on Node 18+, but we normalize defensively
  // so older runtimes still decode cleanly.
  const normalized = segment.replace(/-/g, "+").replace(/_/g, "/");
  const padding = normalized.length % 4 === 0 ? 0 : 4 - (normalized.length % 4);
  return Buffer.from(normalized + "=".repeat(padding), "base64");
}

// Module-level JWKS cache. 10-minute TTL covers normal key rotation
// without thrashing the upstream; a manual restart drops the cache
// faster if needed.
const __jwksCache = { url: "", expiresAt: 0, keys: [] };
const __JWKS_TTL_MS = 10 * 60 * 1000;

async function __fetchJwks(jwksUrl) {
  const now = Date.now();
  if (__jwksCache.url === jwksUrl && __jwksCache.expiresAt > now) {
    return __jwksCache.keys;
  }
  let response;
  try {
    response = await fetch(jwksUrl);
  } catch (error) {
    logError("supabase-jwt:jwks-fetch-failed", error, { jwksUrl });
    return null;
  }
  if (!response.ok) {
    logError(
      "supabase-jwt:jwks-non-2xx",
      new Error("status " + response.status),
      { jwksUrl, status: response.status }
    );
    return null;
  }
  let body;
  try {
    body = await response.json();
  } catch (error) {
    logError("supabase-jwt:jwks-bad-json", error, { jwksUrl });
    return null;
  }
  const keys = Array.isArray(body && body.keys) ? body.keys : [];
  __jwksCache.url = jwksUrl;
  __jwksCache.expiresAt = now + __JWKS_TTL_MS;
  __jwksCache.keys = keys;
  return keys;
}

// Convert a JWS-format ES256 signature (raw concat r||s, 64 bytes
// total) to DER-encoded ECDSA signature, which is what Node's
// crypto.verify expects.
function __jwsSigToDer(rawSig) {
  if (rawSig.length !== 64) return null;
  const r = rawSig.slice(0, 32);
  const s = rawSig.slice(32);
  function trim(buf) {
    let i = 0;
    while (i < buf.length - 1 && buf[i] === 0) i++;
    let trimmed = buf.slice(i);
    if (trimmed[0] & 0x80) {
      trimmed = Buffer.concat([Buffer.from([0]), trimmed]);
    }
    return trimmed;
  }
  const rTrimmed = trim(r);
  const sTrimmed = trim(s);
  const seqBody = Buffer.concat([
    Buffer.from([0x02, rTrimmed.length]),
    rTrimmed,
    Buffer.from([0x02, sTrimmed.length]),
    sTrimmed
  ]);
  return Buffer.concat([Buffer.from([0x30, seqBody.length]), seqBody]);
}

async function ${SUPABASE_JWT_VERIFIER_FUNCTION_NAME}(req) {
  const supabaseUrl = (process.env.${SUPABASE_URL_ENV_VAR} || "").trim();
  if (!supabaseUrl) return null;
  const jwksUrl = supabaseUrl.replace(/\\/+$/, "") + "/auth/v1/.well-known/jwks.json";

  const authHeader = (req.headers && req.headers["authorization"]) || "";
  const prefix = "Bearer ";
  if (typeof authHeader !== "string" || !authHeader.startsWith(prefix)) return null;
  const token = authHeader.slice(prefix.length).trim();
  if (!token) return null;
  const parts = token.split(".");
  if (parts.length !== 3) return null;
  const [headerB64, payloadB64, signatureB64] = parts;

  let jwtHeader;
  try {
    jwtHeader = JSON.parse(decodeBase64Url(headerB64).toString("utf8"));
  } catch {
    return null;
  }
  if (!jwtHeader || typeof jwtHeader !== "object") return null;
  const alg = jwtHeader.alg;
  const kid = jwtHeader.kid;
  if (typeof alg !== "string" || typeof kid !== "string" || !kid) return null;
  if (alg !== "ES256" && alg !== "HS256") return null;

  const keys = await __fetchJwks(jwksUrl);
  if (!keys) return null;
  const jwk = keys.find((entry) => entry && entry.kid === kid);
  if (!jwk) return null;
  if (jwk.alg && jwk.alg !== alg) return null;

  let signature;
  try {
    signature = decodeBase64Url(signatureB64);
  } catch {
    return null;
  }
  const signingInput = Buffer.from(headerB64 + "." + payloadB64, "utf8");

  if (alg === "ES256") {
    if (jwk.kty !== "EC" || jwk.crv !== "P-256") return null;
    let publicKey;
    try {
      publicKey = createPublicKey({ key: jwk, format: "jwk" });
    } catch (error) {
      logError("supabase-jwt:jwk-import-failed", error, { kid });
      return null;
    }
    const derSig = __jwsSigToDer(signature);
    if (!derSig) return null;
    let valid;
    try {
      valid = cryptoVerify("SHA256", signingInput, publicKey, derSig);
    } catch {
      return null;
    }
    if (!valid) return null;
  } else {
    if (jwk.kty !== "oct" || typeof jwk.k !== "string") return null;
    let secretBytes;
    try {
      secretBytes = decodeBase64Url(jwk.k);
    } catch {
      return null;
    }
    const expectedSig = createHmac("sha256", secretBytes)
      .update(signingInput)
      .digest();
    if (expectedSig.length !== signature.length) return null;
    try {
      if (!timingSafeEqual(expectedSig, signature)) return null;
    } catch {
      return null;
    }
  }

  let payload;
  try {
    payload = JSON.parse(decodeBase64Url(payloadB64).toString("utf8"));
  } catch {
    return null;
  }
  if (payload === null || typeof payload !== "object") return null;
  if (payload.aud !== "authenticated") return null;
  const nowSeconds = Math.floor(Date.now() / 1000);
  if (typeof payload.exp !== "number" || payload.exp <= nowSeconds) return null;
  if (typeof payload.sub !== "string" || !payload.sub) return null;

  return {
    userId: payload.sub,
    email: typeof payload.email === "string" ? payload.email : null
  };
}`;
}
