/**
 * Single enforcer for the frame-art contract: the repeating-slice cut sizes
 * in the frame geometry tables must match the pixel dimensions of the PNG
 * files the web target ships. The DOM assembler stretches each file to the
 * cut's size, so a drift (geometry tuned without re-running the slice
 * generator and re-copying its output) silently distorts the art - nothing
 * else fails.
 *
 * The files are generated by docs/prototypes/caster-frame-slices.py and
 * copied into targets/web/src/ui/frame-art/.
 */
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import {
  CASTER_FRAME_GEOMETRY,
  PLAIN_FRAME_GEOMETRY,
  REPEATING_SLICE_ART,
  type FrameGeometry
} from "@sugarmagic/runtime-core";

const ART_DIR = resolve(
  import.meta.dirname,
  "../../../targets/web/src/ui/frame-art"
);

/** Width and height from a PNG's IHDR header (big-endian at offsets 16/20). */
function pngDimensions(filePath: string): { width: number; height: number } {
  const bytes = readFileSync(filePath);
  return {
    width: bytes.readUInt32BE(16),
    height: bytes.readUInt32BE(20)
  };
}

interface VariantFiles {
  geometry: FrameGeometry;
  sheet: string;
  slices: Record<keyof typeof REPEATING_SLICE_ART, string>;
}

const VARIANTS: Record<string, VariantFiles> = {
  caster: {
    geometry: CASTER_FRAME_GEOMETRY,
    sheet: "caster-frame-sheet.png",
    slices: {
      railLeft: "rail-left.png",
      railRight: "rail-right.png",
      topStretch: "top-stretch.png",
      bottomStretch: "bottom-stretch.png",
      parchment: "parchment.png"
    }
  },
  plain: {
    geometry: PLAIN_FRAME_GEOMETRY,
    sheet: "plain-frame-sheet.png",
    slices: {
      railLeft: "plain-rail-left.png",
      railRight: "plain-rail-right.png",
      topStretch: "plain-top-stretch.png",
      bottomStretch: "plain-bottom-stretch.png",
      parchment: "plain-parchment.png"
    }
  }
};

describe.each(Object.entries(VARIANTS))(
  "%s frame art files",
  (_variant, files) => {
    it("sheet matches the geometry's sheet dimensions", () => {
      const dimensions = pngDimensions(resolve(ART_DIR, files.sheet));
      expect(dimensions).toEqual({
        width: files.geometry.sheet.width,
        height: files.geometry.sheet.height
      });
    });

    it("every repeating slice file matches its cut's dimensions", () => {
      for (const [sliceName, fileName] of Object.entries(files.slices)) {
        const cut = files.geometry.slices[sliceName]!;
        // The parchment file is the cut mirrored into a 2x2 quilt.
        const factor = sliceName === "parchment" ? 2 : 1;
        const dimensions = pngDimensions(resolve(ART_DIR, fileName));
        expect(dimensions, `${fileName} vs slice ${sliceName}`).toEqual({
          width: (cut.x1 - cut.x0) * factor,
          height: (cut.y1 - cut.y0) * factor
        });
      }
    });
  }
);
