/**
 * packages/runtime-core/src/framed-panel/geometry.ts
 *
 * Purpose: Source-pixel geometry for the ornate framed panel (the caster
 *   UI frame). Every rectangle is a cut from one painted sheet; the DOM
 *   assembler in ./index.ts positions the cuts, and tests assert the cuts
 *   stay contiguous and inside the sheet.
 *
 * The sheet is the painted mockup: a wood frame with gold corner caps, a top
 * rail carrying the battery pill, a center medallion and the resonance pill,
 * side rails with gem clusters, a bottom rail with a gem emblem, and a
 * parchment interior with corner flourishes.
 *
 * Coordinates are SOURCE pixels of that sheet. The frame's outer edge starts
 * at ORIGIN, so panel-local coordinates are source minus ORIGIN. The DOM
 * layer multiplies by a display scale.
 *
 * Slices come in two kinds:
 *   - fixed pieces, shown via background-position into the full sheet;
 *   - repeating/stretching pieces (side rails, plain rail strips, parchment
 *     tile), which need their own image files because CSS tiles a whole
 *     image, never a sheet sub-region.
 *
 * Exports:
 *   - FRAME_SHEET, FRAME_ORIGIN, FRAME_WIDTH, FRAME_NATURAL_HEIGHT
 *   - FRAME_SLICES, TOP_BAND, BOTTOM_BAND, METER_RECTS, MEDALLION_CIRCLE
 *   - topBandSegments, bottomBandSegments, clampRatio, frameHeightForContent
 *
 * Relationships:
 *   - Pure data and math. No DOM. ./index.ts renders it.
 *   - The slice cuts were settled in docs/prototypes/caster-frame.html; the
 *     repeating slice files are generated by docs/prototypes/
 *     caster-frame-slices.py from the same table.
 *
 * Status: active
 */

/** One rectangle cut from the sheet, in source pixels. */
export interface FrameSlice {
  x0: number;
  y0: number;
  x1: number;
  y1: number;
}

export const FRAME_SHEET = { width: 1536, height: 1024 } as const;

/** The frame's outer wood edge inside the sheet (the rest is empty margin). */
export const FRAME_ORIGIN = { x: 6, y: 31 } as const;

/** Panel-local frame width in source pixels. */
export const FRAME_WIDTH = 1522;

/** Panel-local frame height in source pixels at the sheet's natural size. */
export const FRAME_NATURAL_HEIGHT = 968;

const slice = (x0: number, y0: number, x1: number, y1: number): FrameSlice => ({
  x0,
  y0,
  x1,
  y1
});

/**
 * The cut table. Top band cuts keep y 31..206: the rail wood plus the
 * hardware overhang and the baked top pinstripe. Corner cuts stop at 140
 * so they do not clip the parchment flourishes, which are separate
 * overlay cuts.
 */
export const FRAME_SLICES = {
  cornerTL: slice(6, 31, 146, 171),
  cornerTR: slice(1388, 31, 1528, 171),
  cornerBL: slice(6, 859, 146, 999),
  cornerBR: slice(1388, 859, 1528, 999),
  /** Battery circle + pill + flanking gems. Contiguous with cornerTL/medallion. */
  topBattery: slice(146, 31, 668, 206),
  /** Center medallion with its ring pins. */
  topMedallion: slice(668, 31, 868, 206),
  /** Flanking gems + resonance pill + circle. Contiguous with medallion/cornerTR. */
  topResonance: slice(868, 31, 1388, 206),
  /**
   * Plain rail column between the top-left corner and the battery circle,
   * WOOD ROWS ONLY - no full-height column in the top band is free of
   * hardware shadows below the rail, so the strip stops at the wood's
   * underside and the parchment fill shows beneath it. STRETCHED (never
   * tiled) to fill leftover band width - tiling a few-pixel strip shreds
   * the wood grain into ribs.
   */
  topStretch: slice(150, 31, 162, 122),
  /** Bottom gem emblem with its gold leaves. */
  bottomEmblem: slice(620, 830, 908, 999),
  /** Plain bottom rail column, includes the baked bottom pinstripe. */
  bottomStretch: slice(400, 860, 432, 999),
  /** Side rail slices, repeat vertically; include the baked vertical pinstripe. */
  railLeft: slice(6, 690, 110, 722),
  railRight: slice(1424, 690, 1528, 722),
  /** Fixed side gem clusters, vertically centered on the rails. */
  gemLeft: slice(6, 356, 110, 652),
  gemRight: slice(1424, 356, 1528, 652),
  /** Parchment corner flourishes; carry the pinstripe corner rounding. */
  flourishTL: slice(70, 125, 300, 315),
  flourishTR: slice(1236, 125, 1466, 315),
  /**
   * Same top flourishes trimmed to start below the meter hardware: the
   * full cuts include the bottoms of the battery/resonance circles, which
   * the meter segments paint over in caster mode but nothing covers when
   * the meters are hidden. The baked pinstripe (y ~176) survives the trim.
   */
  flourishTLNoMeters: slice(70, 172, 300, 315),
  flourishTRNoMeters: slice(1236, 172, 1466, 315),
  flourishBL: slice(60, 740, 290, 910),
  flourishBR: slice(1246, 740, 1476, 910),
  /**
   * Parchment fill tile, sampled just below the top band where the art's
   * vignette matches the parchment baked into the frame pieces. The shipped
   * file is this cut mirrored into a 2x2 quilt so tile edges always match.
   */
  parchment: slice(320, 212, 600, 352)
} as const;

export type FrameSliceName = keyof typeof FRAME_SLICES;

export function sliceWidth(name: FrameSliceName): number {
  const s = FRAME_SLICES[name];
  return s.x1 - s.x0;
}

export function sliceHeight(name: FrameSliceName): number {
  const s = FRAME_SLICES[name];
  return s.y1 - s.y0;
}

/** Corner piece height; the side rails run between the corners. */
export const CORNER_HEIGHT = 140;

/** Top band height (rail + hardware overhang + baked pinstripe). */
export const TOP_BAND_HEIGHT = 175;

/** Bottom band height (emblem overhang above the rail). */
export const BOTTOM_BAND_HEIGHT = 169;

/**
 * Interior insets of the usable content area on the parchment, panel-local
 * source pixels: clear of the hardware overhang and the pinstripe border.
 */
export const CONTENT_INSETS = {
  top: 215,
  right: 120,
  bottom: 125,
  left: 120
} as const;

/**
 * The two pill trough interiors (inside the gold rims), panel-local source
 * pixels. The DOM layer covers them - the sheet has them painted full - and
 * draws the live fill.
 */
export const METER_RECTS = {
  battery: { x: 286, y: 63, width: 270, height: 49 },
  resonance: { x: 962, y: 63, width: 274, height: 49 }
} as const;

/** Medallion interior circle (inside the gold ring), panel-local source pixels. */
export const MEDALLION_CIRCLE = { cx: 762, cy: 81, r: 70 } as const;

/**
 * Top band composition, left to right. Stretch entries have zero natural
 * width: at the natural panel width the fixed segments already sum to
 * FRAME_WIDTH, so stretches only take up room when meter segments are
 * omitted or the panel is wider than natural.
 */
export function topBandSegments(
  showMeters: boolean
): Array<{ slice: FrameSliceName; stretch: boolean }> {
  return [
    { slice: "cornerTL", stretch: false },
    { slice: "topStretch", stretch: true },
    ...(showMeters
      ? [{ slice: "topBattery" as const, stretch: false }]
      : []),
    { slice: "topStretch", stretch: true },
    { slice: "topMedallion", stretch: false },
    { slice: "topStretch", stretch: true },
    ...(showMeters
      ? [{ slice: "topResonance" as const, stretch: false }]
      : []),
    { slice: "topStretch", stretch: true },
    { slice: "cornerTR", stretch: false }
  ];
}

/** Bottom band composition, left to right. */
export function bottomBandSegments(): Array<{
  slice: FrameSliceName;
  stretch: boolean;
}> {
  return [
    { slice: "cornerBL", stretch: false },
    { slice: "bottomStretch", stretch: true },
    { slice: "bottomEmblem", stretch: false },
    { slice: "bottomStretch", stretch: true },
    { slice: "cornerBR", stretch: false }
  ];
}

/** Clamp a meter value to the renderable 0..1 range. NaN clamps to 0. */
export function clampRatio(value: number): number {
  if (!Number.isFinite(value)) return 0;
  return Math.min(1, Math.max(0, value));
}

/**
 * Panel height (source pixels) that gives the content area
 * `contentSourceHeight` source pixels of room.
 */
export function frameHeightForContent(contentSourceHeight: number): number {
  return Math.max(
    FRAME_NATURAL_HEIGHT,
    Math.ceil(contentSourceHeight) + CONTENT_INSETS.top + CONTENT_INSETS.bottom
  );
}
