/**
 * packages/runtime-core/src/framed-panel/geometry.ts
 *
 * Purpose: Source-pixel geometry for the ornate framed panels. Two painted
 *   sheets share one assembly scheme: the CASTER frame (top rail carries the
 *   battery pill, center medallion and resonance pill) and the PLAIN frame
 *   (bare rails, used by the inventory list). Every rectangle is a cut from
 *   its sheet; the DOM assembler in ./index.ts positions the cuts, and tests
 *   assert the cuts stay contiguous and inside their sheet.
 *
 * Coordinates are SOURCE pixels of each sheet. A frame's outer edge starts
 * at its `origin`, so panel-local coordinates are source minus origin. The
 * DOM layer multiplies by a display scale.
 *
 * Slices come in two kinds:
 *   - fixed pieces, shown via background-position into the full sheet;
 *   - repeating/stretching pieces (side rails, plain rail strips, parchment
 *     tile), which need their own image files because CSS tiles a whole
 *     image, never a sheet sub-region. These are the keys of
 *     REPEATING_SLICE_ART.
 *
 * Exports:
 *   - FrameGeometry, FrameSlice, MeterRect, REPEATING_SLICE_ART
 *   - CASTER_FRAME_GEOMETRY, PLAIN_FRAME_GEOMETRY, MEDALLION_CIRCLE
 *   - clampRatio, frameHeightForContent
 *
 * Relationships:
 *   - Pure data and math. No DOM. ./index.ts renders it.
 *   - The cuts were settled in docs/prototypes/caster-frame.html and
 *     plain-frame.html; the repeating slice files are generated by
 *     docs/prototypes/caster-frame-slices.py from the same tables.
 *
 * Status: active
 */

/** One rectangle cut from a sheet, in source pixels. */
export interface FrameSlice {
  x0: number;
  y0: number;
  x1: number;
  y1: number;
}

export interface MeterRect {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface FrameBandSegment {
  slice: string;
  stretch: boolean;
}

export interface FrameGeometry {
  sheet: { width: number; height: number };
  /** The frame's outer wood edge inside the sheet (the rest is margin). */
  origin: { x: number; y: number };
  /** Panel-local frame width in source pixels. */
  frameWidth: number;
  /** Panel-local frame height in source pixels at the sheet's natural size. */
  naturalHeight: number;
  /** Corner piece height; the side rails run between the corners. */
  cornerHeight: number;
  topBandHeight: number;
  bottomBandHeight: number;
  /**
   * Interior insets of the usable content area on the parchment,
   * panel-local source pixels: clear of any hardware overhang and the
   * pinstripe border.
   */
  contentInsets: { top: number; right: number; bottom: number; left: number };
  slices: Record<string, FrameSlice>;
  /**
   * Top band composition, left to right. Stretch entries scale their strip
   * to the flexed width (never tiled) and collapse to zero when the fixed
   * segments already sum to the frame width.
   */
  topBand: ReadonlyArray<FrameBandSegment>;
  bottomBand: ReadonlyArray<FrameBandSegment>;
  /** Live meter overlays covering painted pill troughs; null = no meters. */
  meters: { battery: MeterRect; resonance: MeterRect } | null;
}

/**
 * Slice keys that repeat or stretch and therefore ship as standalone image
 * files, mapped to their field on FramedPanelArt (see ./index.ts).
 */
export const REPEATING_SLICE_ART = {
  railLeft: "railLeftUrl",
  railRight: "railRightUrl",
  topStretch: "topStretchUrl",
  bottomStretch: "bottomStretchUrl",
  parchment: "parchmentUrl"
} as const;

const slice = (x0: number, y0: number, x1: number, y1: number): FrameSlice => ({
  x0,
  y0,
  x1,
  y1
});

/**
 * The caster frame. Top band cuts keep y 31..206: the rail wood plus the
 * meter/medallion hardware overhang and the baked top pinstripe. Corner
 * cuts stop at 140 so they do not clip the parchment flourishes, which are
 * separate overlay cuts.
 */
export const CASTER_FRAME_GEOMETRY: FrameGeometry = {
  sheet: { width: 1536, height: 1024 },
  origin: { x: 6, y: 31 },
  frameWidth: 1522,
  naturalHeight: 968,
  cornerHeight: 140,
  topBandHeight: 175,
  bottomBandHeight: 169,
  contentInsets: { top: 215, right: 120, bottom: 125, left: 120 },
  slices: {
    cornerTL: slice(6, 31, 146, 171),
    cornerTR: slice(1388, 31, 1528, 171),
    cornerBL: slice(6, 859, 146, 999),
    cornerBR: slice(1388, 859, 1528, 999),
    /** Battery circle + pill + flanking gems. Contiguous with cornerTL/medallion. */
    topBattery: slice(146, 31, 668, 206),
    /** Center medallion with its ring pins. */
    topMedallion: slice(668, 31, 868, 206),
    /** Flanking gems + resonance pill + circle. Contiguous with medallion/cornerTR. */
    topResonance: slice(868, 31, 1388, 206),
    /**
     * Plain rail column between the top-left corner and the battery circle,
     * WOOD ROWS ONLY - no full-height top-band column is free of hardware
     * shadows, so the strip stops at the wood's underside and the parchment
     * fill shows beneath it.
     */
    topStretch: slice(150, 31, 162, 122),
    bottomEmblem: slice(620, 830, 908, 999),
    bottomStretch: slice(400, 860, 432, 999),
    railLeft: slice(6, 690, 110, 722),
    railRight: slice(1424, 690, 1528, 722),
    gemLeft: slice(6, 356, 110, 652),
    gemRight: slice(1424, 356, 1528, 652),
    flourishTL: slice(70, 125, 300, 315),
    flourishTR: slice(1236, 125, 1466, 315),
    flourishBL: slice(60, 740, 290, 910),
    flourishBR: slice(1246, 740, 1476, 910),
    /**
     * Parchment fill tile, sampled just below the top band where the art's
     * vignette matches the parchment baked into the frame pieces. The
     * shipped file is this cut mirrored into a 2x2 quilt.
     */
    parchment: slice(320, 212, 600, 352)
  },
  topBand: [
    { slice: "cornerTL", stretch: false },
    { slice: "topStretch", stretch: true },
    { slice: "topBattery", stretch: false },
    { slice: "topStretch", stretch: true },
    { slice: "topMedallion", stretch: false },
    { slice: "topStretch", stretch: true },
    { slice: "topResonance", stretch: false },
    { slice: "topStretch", stretch: true },
    { slice: "cornerTR", stretch: false }
  ],
  bottomBand: [
    { slice: "cornerBL", stretch: false },
    { slice: "bottomStretch", stretch: true },
    { slice: "bottomEmblem", stretch: false },
    { slice: "bottomStretch", stretch: true },
    { slice: "cornerBR", stretch: false }
  ],
  /** Pill trough interiors (inside the gold rims), panel-local source px. */
  meters: {
    battery: { x: 286, y: 63, width: 270, height: 49 },
    resonance: { x: 962, y: 63, width: 274, height: 49 }
  }
};

/**
 * Medallion interior circle on the caster frame (inside the gold ring),
 * panel-local source pixels.
 */
export const MEDALLION_CIRCLE = { cx: 762, cy: 81, r: 70 } as const;

/**
 * The plain frame: bare rails, no hardware. Its top band mirrors the
 * bottom's construction - corners plus a full-height stretch strip that
 * carries the baked pinstripe.
 */
export const PLAIN_FRAME_GEOMETRY: FrameGeometry = {
  sheet: { width: 1536, height: 1024 },
  origin: { x: 6, y: 38 },
  frameWidth: 1523,
  naturalHeight: 961,
  cornerHeight: 140,
  topBandHeight: 140,
  bottomBandHeight: 144,
  contentInsets: { top: 150, right: 130, bottom: 130, left: 130 },
  slices: {
    cornerTL: slice(6, 38, 146, 178),
    cornerTR: slice(1389, 38, 1529, 178),
    cornerBL: slice(6, 859, 146, 999),
    cornerBR: slice(1389, 859, 1529, 999),
    topStretch: slice(400, 38, 412, 178),
    bottomEmblem: slice(620, 855, 916, 999),
    bottomStretch: slice(300, 855, 332, 999),
    railLeft: slice(6, 690, 126, 722),
    railRight: slice(1410, 690, 1530, 722),
    gemLeft: slice(6, 350, 100, 660),
    gemRight: slice(1436, 350, 1530, 660),
    flourishTL: slice(80, 120, 300, 320),
    flourishTR: slice(1236, 120, 1456, 320),
    flourishBL: slice(70, 750, 300, 910),
    flourishBR: slice(1236, 750, 1466, 910),
    parchment: slice(400, 200, 680, 340)
  },
  topBand: [
    { slice: "cornerTL", stretch: false },
    { slice: "topStretch", stretch: true },
    { slice: "cornerTR", stretch: false }
  ],
  bottomBand: [
    { slice: "cornerBL", stretch: false },
    { slice: "bottomStretch", stretch: true },
    { slice: "bottomEmblem", stretch: false },
    { slice: "bottomStretch", stretch: true },
    { slice: "cornerBR", stretch: false }
  ],
  meters: null
};

/** Clamp a meter value to the renderable 0..1 range. NaN clamps to 0. */
export function clampRatio(value: number): number {
  if (!Number.isFinite(value)) return 0;
  return Math.min(1, Math.max(0, value));
}

/**
 * Panel height (source pixels) that gives the content area
 * `contentSourceHeight` source pixels of room on the given frame.
 */
export function frameHeightForContent(
  geometry: FrameGeometry,
  contentSourceHeight: number
): number {
  return Math.max(
    geometry.naturalHeight,
    Math.ceil(contentSourceHeight) +
      geometry.contentInsets.top +
      geometry.contentInsets.bottom
  );
}
