// Compiles core.ts (+ supabase-jwt.ts bundled inline) to a JS string constant
// and writes it to src/deployment/gateway/core.compiled.ts.
// Run via: pnpm --filter @sugarmagic/plugins build:gateway-source
import { build } from "esbuild";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dir = dirname(fileURLToPath(import.meta.url));
const gatewayDir = join(__dir, "../src/deployment/gateway");
const coreTs = join(gatewayDir, "core.ts");
const outputFile = join(gatewayDir, "core.compiled.ts");

const result = await build({
  entryPoints: [coreTs],
  bundle: true,
  write: false,
  format: "esm",
  target: "es2022",
  platform: "node",
  external: ["node:*"],
  // Preserve /*! ... */ legal comments so the __GATEWAY_AUTH_GATE__
  // placeholder survives for buildGatewayServerFile to inject into.
  legalComments: "inline",
  minify: false,
  // Disable tree-shaking so verifySupabaseJwt and the JWKS helpers
  // are included in all auth modes. They're dead code in none/bearer
  // but the auth gate injection in buildGatewayServerFile may call
  // them, and the compiled string can't retroactively add them.
  treeShaking: false,
});

const compiled = result.outputFiles?.[0]?.text ?? "";

writeFileSync(
  outputFile,
  [
    "// Generated by scripts/build-gateway-source.mts",
    "// Source: packages/plugins/src/deployment/gateway/core.ts (+ supabase-jwt.ts)",
    "// DO NOT EDIT — edit core.ts / supabase-jwt.ts and re-run build:gateway-source",
    "export const GATEWAY_CORE_COMPILED_SOURCE = " + JSON.stringify(compiled) + ";",
    ""
  ].join("\n"),
  "utf8"
);

console.log("Generated", outputFile, `(${compiled.length} chars)`);
